////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.bingen;

/**
 * Decodes a value of type {@code T} from a {@link DecodingContext}.
 */
public interface BinDecoder<T> {
    T decode(DecodingContext ctx);
}
