////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.bingen;

/**
 * One pulled stream element: the field it belongs to and its value (which is
 * null for a nil field, and carries an index/key for flattened collections).
 */
public record BingenElement(BingenFieldInfo field, BingenValue value) {
}
