////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.bingen;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.Iterator;
import java.util.NoSuchElementException;
import java.util.Spliterator;
import java.util.Spliterators;
import java.util.concurrent.SynchronousQueue;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

/**
 * Adapts a push streamer ({@code <T>Streamer::stream}) into a pull
 * {@link Iterable}/{@link Stream} of {@link BingenElement}. The push streamer
 * runs on a virtual thread and hands each element across a {@link
 * SynchronousQueue}, so exactly one element is in flight — the producer blocks
 * until the consumer pulls, matching go's cooperative streaming.
 *
 * <p>Single use. Always close it (try-with-resources) if you do not iterate to
 * the end, otherwise the producer virtual thread is left parked.
 */
public final class BingenPullStream implements Iterable<BingenElement>, AutoCloseable {

    private static final Object DONE = new Object();
    private static final Object FAIL = new Object();

    private final SynchronousQueue<Object> queue = new SynchronousQueue<>();
    private volatile boolean closed;
    private volatile Throwable error;
    private final Thread producer;

    private BingenPullStream(InputStream in, BingenStreamFn fn) {
        this.producer = Thread.ofVirtual().name("bingen-pull-stream").start(() -> run(in, fn));
    }

    /** 
     * Creates a pull stream driving the push streamer over an in-memory payload. 
     */
    public static BingenPullStream of(byte[] data, BingenStreamFn fn) {
        return new BingenPullStream(new ByteArrayInputStream(data), fn);
    }

    /**
     * Creates a pull stream driving the push streamer over a stream read
     * incrementally (socket, file, ...). The caller retains ownership of the
     * stream.
     */
    public static BingenPullStream of(InputStream in, BingenStreamFn fn) {
        return new BingenPullStream(in, fn);
    }

    private void run(InputStream in, BingenStreamFn fn) {
        try {
            fn.stream(in, (fi, value) -> {
                if (closed) {
                    return false;
                }
                try {
                    queue.put(new BingenElement(fi, value));
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    return false;
                }
                return !closed;
            });
            if (!closed) {
                queue.put(DONE);
            }
        } catch (InterruptedException e) {
            // interrupted during the terminal handoff while closing; nothing to do.
        } catch (Throwable t) {
            error = t;
            if (!closed) {
                try {
                    queue.put(FAIL);
                } catch (InterruptedException ignored) {
                    Thread.currentThread().interrupt();
                }
            }
        }
    }

    @Override
    public Iterator<BingenElement> iterator() {
        return new Iterator<>() {
            private BingenElement next;
            private boolean done;

            @Override
            public boolean hasNext() {
                if (done) {
                    return false;
                }
                if (next != null) {
                    return true;
                }
                Object msg;
                try {
                    msg = queue.take();
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    done = true;
                    return false;
                }
                if (msg == DONE) {
                    done = true;
                    return false;
                }
                if (msg == FAIL) {
                    done = true;
                    throw new BingenStreamException(error);
                }
                next = (BingenElement) msg;
                return true;
            }

            @Override
            public BingenElement next() {
                if (!hasNext()) {
                    throw new NoSuchElementException();
                }
                BingenElement element = next;
                next = null;
                return element;
            }
        };
    }

    /** 
     * A sequential {@link Stream}; closing it closes this pull stream. 
     */
    public Stream<BingenElement> stream() {
        Spliterator<BingenElement> spliterator =
            Spliterators.spliteratorUnknownSize(iterator(), Spliterator.ORDERED);
            
        return StreamSupport.stream(spliterator, false).onClose(this::close);
    }

    @Override
    public void close() {
        closed = true;
        producer.interrupt();
    }
}
