////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.bingen;

import java.io.InputStream;

/**
 * A generated {@code <T>Streamer.stream(InputStream, BingenConsumer)} entry
 * point, so a push streamer can be adapted into a pull stream (see {@link
 * BingenPullStream}).
 */
@FunctionalInterface
public interface BingenStreamFn {
    void stream(InputStream in, BingenConsumer consumer);
}
