////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.bingen;

/**
 * Receives each streamed field (and each flattened collection element). Return
 * {@code false} to stop streaming early, mirroring go's yield contract. A null
 * {@link BingenValue} indicates a nil field value.
 */
@FunctionalInterface
public interface BingenConsumer {
    boolean accept(BingenFieldInfo field, BingenValue value);
}
