////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.bingen;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Assigns each distinct string an insertion-ordered index and writes the table,
 * prefixed with the {@code BGST} tag, ahead of the payload.
 */
public final class StringTableWriter {

    private static final byte[] TAG = {'B', 'G', 'S', 'T'};

    private final Map<String, Integer> indices = new LinkedHashMap<>();
    private int next = 0;

    /** Returns the existing index for {@code s}, or assigns and returns a new one. */
    public int addOrGet(String s) {
        Integer existing = indices.get(s);
        if (existing != null) {
            return existing;
        }
        int current = next++;
        indices.put(s, current);
        return current;
    }

    /** Writes the tag, the string count, and each string in index order. */
    public void writeTo(WriteBuffer buff) {
        buff.writeBytes(TAG);

        String[] ordered = new String[next];
        for (Map.Entry<String, Integer> entry : indices.entrySet()) {
            ordered[entry.getValue()] = entry.getKey();
        }

        buff.writeInt(ordered.length);
        for (String s : ordered) {
            buff.writeString(s);
        }
    }
}
