////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package aliases

import (
	"fmt"
	"io"
	"iter"
	"os"
	"reflect"
	"strings"
	"sync"

	"github.com/opencost/bingen/tests/shared"

	bstream "github.com/opencost/bingen/pkg/stream"
	stringtable "github.com/opencost/bingen/pkg/table"
	util "github.com/opencost/bingen/pkg/util"
)

const (
	// GeneratorPackageName is the package the generator is targetting
	GeneratorPackageName string = "aliases"

	// DefaultCodecVersion is used for any resources listed in the Default version set
	DefaultCodecVersion uint8 = 16
)

//--------------------------------------------------------------------------
//  Configuration
//--------------------------------------------------------------------------

var (
	bingenConfigLock sync.RWMutex
	bingenConfig     *BingenConfiguration = DefaultBingenConfiguration()
)

// BingenConfiguration is used to set any custom configuration in the way files are encoded
// or decoded.
type BingenConfiguration struct {
	// FileBackedStringTableEnabled enables the use of file-backed string tables for streaming
	// bingen decoding.
	FileBackedStringTableEnabled bool

	// FileBackedStringTableDir is the directory to write the string table files for reading.
	FileBackedStringTableDir string

	// FileBackedStringTableMemoMaxBytes limits in-memory memoization for file-backed table lookups.
	// 0 disables memoization.
	FileBackedStringTableMemoMaxBytes int64
}

// DefaultBingenConfiguration creates the default implementation of the bingen configuration
// and returns it.
func DefaultBingenConfiguration() *BingenConfiguration {
	return &BingenConfiguration{
		FileBackedStringTableEnabled:      false,
		FileBackedStringTableDir:          os.TempDir(),
		FileBackedStringTableMemoMaxBytes: 0,
	}
}

// ConfigureBingen accepts a new *BingenConfiguration instance which updates the internal decoder
// and encoder behavior.
func ConfigureBingen(config *BingenConfiguration) {
	bingenConfigLock.Lock()
	defer bingenConfigLock.Unlock()

	if config == nil {
		config = DefaultBingenConfiguration()
	}
	bingenConfig = config
}

// IsBingenFileBackedStringTableEnabled accessor for file backed string table configuration
func IsBingenFileBackedStringTableEnabled() bool {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableEnabled
}

// BingenFileBackedStringTableDir returns the directory configured for file backed string tables.
func BingenFileBackedStringTableDir() string {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableDir
}

// BingenFileBackedStringTableMemoMaxBytes returns the maximum bytes used for file-backed memo cache.
func BingenFileBackedStringTableMemoMaxBytes() int64 {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableMemoMaxBytes
}

//--------------------------------------------------------------------------
//  Type Map
//--------------------------------------------------------------------------

// Generated type map for resolving interface implementations to to concrete types
var typeMap map[string]reflect.Type = map[string]reflect.Type{
	"Info":   reflect.TypeFor[Info](),
	"Parent": reflect.TypeFor[Parent](),
}

//--------------------------------------------------------------------------
//  Type Helpers
//--------------------------------------------------------------------------

// isBinaryTag returns true when the first bytes in the provided binary matches the tag
func isBinaryTag(data []byte, tag string) bool {
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// isReaderBinaryTag is used to peek the header for an io.Reader Buffer
func isReaderBinaryTag(buff *util.Buffer, tag string) bool {
	data, err := buff.Peek(len(tag))
	if err != nil && err != io.EOF {
		panic(fmt.Sprintf("called Peek() on a non buffered reader: %s", err))
	}
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// typeToString determines the basic properties of the type, the qualifier, package path, and
// type name, and returns the qualified type
func typeToString(f interface{}) string {
	qual := ""
	t := reflect.TypeOf(f)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
		qual = "*"
	}

	return fmt.Sprintf("%s%s.%s", qual, t.PkgPath(), t.Name())
}

// resolveType uses the name of a type and returns the package, base type name, and whether
// or not it's a pointer.
func resolveType(t string) (pkg string, name string, isPtr bool) {
	isPtr = t[:1] == "*"
	if isPtr {
		t = t[1:]
	}

	slashIndex := strings.LastIndex(t, "/")
	if slashIndex >= 0 {
		t = t[slashIndex+1:]
	}
	parts := strings.Split(t, ".")
	if parts[0] == GeneratorPackageName {
		parts[0] = ""
	}

	pkg = parts[0]
	name = parts[1]
	return
}

//--------------------------------------------------------------------------
//  Stream Helpers
//--------------------------------------------------------------------------

// StreamFactoryFunc is an alias for a func that creates a BingenStream implementation.
type StreamFactoryFunc func(io.Reader) bstream.BingenStream

// Generated streamable factory map for finding the specific new stream methods
// by T type
var streamFactoryMap map[reflect.Type]StreamFactoryFunc = map[reflect.Type]StreamFactoryFunc{
	reflect.TypeFor[Parent](): NewParentStream,
}

// NewStreamFor accepts an io.Reader, and returns a new BingenStream for the generic T
// type provided _if_ it is a registered bingen type that is annotated as 'streamable'. See
// the streamFactoryMap for generated type listings.
func NewStreamFor[T any](reader io.Reader) (bstream.BingenStream, error) {
	typeKey := reflect.TypeFor[T]()

	factory, ok := streamFactoryMap[typeKey]
	if !ok {
		return nil, fmt.Errorf("the type: %s is not a registered bingen streamable type", typeKey.Name())
	}

	return factory(reader), nil
}

//--------------------------------------------------------------------------
//  Codec Context
//--------------------------------------------------------------------------

// EncodingContext is a context object passed to the encoders to ensure reuse of buffer
// and table data
type EncodingContext struct {
	Buffer *util.Buffer
	Table  stringtable.StringTableWriter
}

// NewEncodingContext creates a new EncodingContext instance that will create a new []byte buffer
// for writing, and return the context
func NewEncodingContext(tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: util.NewBuffer(),
		Table:  tableWriter,
	}
}

// NewEncodingContextFromWriter creates a new EncodingContext instance that will create a new Buffer
// from the provided io.Writer and StringTableWriter.
func NewEncodingContextFromWriter(writer io.Writer, tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: util.NewBufferFromWriter(writer),
		Table:  tableWriter,
	}
}

// NewEncodingContextFromBuffer creates a new EncodingContext instance that will leverage an existing
// Buffer and StringTableWriter.
func NewEncodingContextFromBuffer(buffer *util.Buffer, tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: buffer,
		Table:  tableWriter,
	}
}

// ToBytes returns the encoded string table bytes (if applicable) combined with the encoded buffer bytes. If
// a string table is being used, the string table bytes will be written first to ensure correct ordering for
// decoding.
func (ec *EncodingContext) ToBytes() []byte {
	encBytes := ec.Buffer.Bytes()
	if ec.Table != nil {
		buff := util.NewBuffer()
		ec.Table.WriteTo(buff)
		buff.WriteBytes(encBytes)
		return buff.Bytes()
	}

	return encBytes
}

// IsStringTable returns true if the table is available
func (ec *EncodingContext) IsStringTable() bool {
	return ec.Table != nil
}

// DecodingContext is a context object passed to the decoders to ensure parent objects
// reuse as much data as possible
type DecodingContext struct {
	Buffer *util.Buffer
	Table  stringtable.StringTableReader
}

// NewDecodingContextFromBytes creates a new DecodingContext instance using an byte slice
func NewDecodingContextFromBytes(data []byte) *DecodingContext {
	var table stringtable.StringTableReader

	buff := util.NewBufferFromBytes(data)

	// string table header validation
	if isBinaryTag(data, stringtable.BinaryTagStringTable) {
		buff.ReadBytes(len(stringtable.BinaryTagStringTable)) // strip tag length

		// always use a slice string table with a byte array since the
		// data is already in memory
		table = stringtable.NewSliceStringTableReaderFrom(buff)
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}
}

// NewDecodingContextFromReader creates a new DecodingContext instance using an io.Reader
// implementation
func NewDecodingContextFromReader(reader io.Reader) *DecodingContext {
	var table stringtable.StringTableReader

	buff := util.NewBufferFromReader(reader)

	if isReaderBinaryTag(buff, stringtable.BinaryTagStringTable) {
		buff.ReadBytes(len(stringtable.BinaryTagStringTable)) // strip tag length

		// create correct string table implementation
		if IsBingenFileBackedStringTableEnabled() {
			table = stringtable.NewFileStringTableReaderFrom(buff, BingenFileBackedStringTableDir(), GeneratorPackageName, BingenFileBackedStringTableMemoMaxBytes())
		} else {
			table = stringtable.NewSliceStringTableReaderFrom(buff)
		}
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}
}

// IsStringTable returns true if the table is available
func (dc *DecodingContext) IsStringTable() bool {
	return dc.Table != nil && dc.Table.Len() > 0
}

// Close will ensure that any string table resources and buffer resources are
// cleaned up.
func (dc *DecodingContext) Close() {
	if dc.Table != nil {
		_ = dc.Table.Close()
		dc.Table = nil
	}
}

//--------------------------------------------------------------------------
//  Binary Codec
//--------------------------------------------------------------------------

// BinEncoder is an encoding interface which defines a context based marshal contract.
type BinEncoder interface {
	MarshalBinaryWithContext(*EncodingContext) error
}

// BinDecoder is a decoding interface which defines a context based unmarshal contract.
type BinDecoder interface {
	UnmarshalBinaryWithContext(*DecodingContext) error
}

//--------------------------------------------------------------------------
//  Info
//--------------------------------------------------------------------------

// MarshalBinary serializes the internal properties of this Info instance
// into a byte array
func (target *Info) MarshalBinary() (data []byte, err error) {
	ctx := NewEncodingContext(nil)

	e := target.MarshalBinaryWithContext(ctx)
	if e != nil {
		return nil, e
	}

	return ctx.ToBytes(), nil
}

// MarshalBinary serializes the internal properties of this Info instance
// into an io.Writer.
func (target *Info) MarshalBinaryTo(writer io.Writer) error {
	buff := util.NewBufferFromWriter(writer)
	defer buff.Flush()

	ctx := NewEncodingContextFromBuffer(buff, nil)

	return target.MarshalBinaryWithContext(ctx)
}

// MarshalBinaryWithContext serializes the internal properties of this Info instance
// into a byte array leveraging a predefined context.
func (target *Info) MarshalBinaryWithContext(ctx *EncodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	buff.WriteUInt8(DefaultCodecVersion) // version

	if ctx.IsStringTable() {
		v0 := ctx.Table.AddOrGet(target.Name)
		buff.WriteInt(v0) // write table index
	} else {
		buff.WriteString(target.Name) // write string
	}
	buff.WriteUInt(target.Age)

	return nil
}

// UnmarshalBinary uses the data passed byte array to set all the internal properties of
// the Info type
func (target *Info) UnmarshalBinary(data []byte) error {
	ctx := NewDecodingContextFromBytes(data)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryFromReader uses the io.Reader data to set all the internal properties of
// the Info type
func (target *Info) UnmarshalBinaryFromReader(reader io.Reader) error {
	ctx := NewDecodingContextFromReader(reader)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryWithContext uses the context containing a string table and binary buffer to set all the internal properties of
// the Info type
func (target *Info) UnmarshalBinaryWithContext(ctx *DecodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	version := buff.ReadUInt8()

	if version > DefaultCodecVersion {
		return fmt.Errorf("Invalid Version Unmarshalling Info. Expected %d or less, got %d", DefaultCodecVersion, version)
	}

	var v0 string
	if ctx.IsStringTable() {
		v1 := buff.ReadInt() // read string index
		v0 = ctx.Table.At(v1)
	} else {
		v0 = buff.ReadString() // read string
	}
	target.Name = v0
	var v2 uint
	v2 = buff.ReadUInt()
	target.Age = v2

	return nil
}

//--------------------------------------------------------------------------
//  Parent
//--------------------------------------------------------------------------

// MarshalBinary serializes the internal properties of this Parent instance
// into a byte array
func (target *Parent) MarshalBinary() (data []byte, err error) {
	ctx := NewEncodingContext(stringtable.NewIndexedStringTableWriter())

	e := target.MarshalBinaryWithContext(ctx)
	if e != nil {
		return nil, e
	}

	return ctx.ToBytes(), nil
}

// MarshalBinary serializes the internal properties of this Parent instance
// into an io.Writer.
func (target *Parent) MarshalBinaryTo(writer io.Writer) error {
	buff := util.NewBufferFromWriter(writer)
	defer buff.Flush()

	// run a pre-pass to collect all strings into the string table and discard all writes to the main
	// buffer. Then, we write the string table, sorted by number of repeated uses (descending), to the
	// main buffer, and use the resulting table as part of the context for the main pass.
	prepass := stringtable.NewPrepassStringTableWriter()
	prepassCtx := NewEncodingContextFromWriter(io.Discard, prepass)

	e := target.MarshalBinaryWithContext(prepassCtx)
	if e != nil {
		return e
	}

	tableWriter := prepass.WriteSortedTo(buff)
	ctx := NewEncodingContextFromBuffer(buff, tableWriter)

	return target.MarshalBinaryWithContext(ctx)
}

// MarshalBinaryWithContext serializes the internal properties of this Parent instance
// into a byte array leveraging a predefined context.
func (target *Parent) MarshalBinaryWithContext(ctx *EncodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	buff.WriteUInt8(DefaultCodecVersion) // version

	if target.Name == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte
		// --- [begin][write][alias](shared.Name) ---
		if ctx.IsStringTable() {
			v0 := ctx.Table.AddOrGet(string(*target.Name))
			buff.WriteInt(v0) // write table index
		} else {
			buff.WriteString(string(*target.Name)) // write string
		}
		// --- [end][write][alias](shared.Name) ---
	}
	if target.Age == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte
		// --- [begin][write][alias](shared.Age) ---
		if ((*int)(*target.Age)) == nil {
			buff.WriteUInt8(uint8(0)) // write nil byte
		} else {
			buff.WriteUInt8(uint8(1)) // write non-nil byte
			buff.WriteInt(*((*int)(*target.Age)))
		}
		// --- [end][write][alias](shared.Age) ---
	}
	// --- [begin][write][alias](Child) ---
	if ctx.IsStringTable() {
		v1 := ctx.Table.AddOrGet(string(target.FirstChild))
		buff.WriteInt(v1) // write table index
	} else {
		buff.WriteString(string(target.FirstChild)) // write string
	}
	// --- [end][write][alias](Child) ---
	// --- [begin][write][alias](ChildInfo) ---
	if ((*Info)(target.FirstChildInfo)) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte
		// --- [begin][write][struct](Info) ---
		buff.WriteInt(0) // [compatibility, unused]
		v2 := ((*Info)(target.FirstChildInfo)).MarshalBinaryWithContext(ctx)
		if v2 != nil {
			return v2
		}
		// --- [end][write][struct](Info) ---
	}
	// --- [end][write][alias](ChildInfo) ---
	if target.Children == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte
		// --- [begin][write][slice]([]Child) ---
		buff.WriteInt(len(target.Children)) // slice length
		for v3 := range target.Children {
			// --- [begin][write][alias](Child) ---
			if ctx.IsStringTable() {
				v4 := ctx.Table.AddOrGet(string(target.Children[v3]))
				buff.WriteInt(v4) // write table index
			} else {
				buff.WriteString(string(target.Children[v3])) // write string
			}
			// --- [end][write][alias](Child) ---
		}
		// --- [end][write][slice]([]Child) ---
	}
	// --- [begin][write][alias](OtherChildInfo) ---
	if []ChildInfo(target.ChildrenInfo) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte
		// --- [begin][write][slice]([]ChildInfo) ---
		buff.WriteInt(len([]ChildInfo(target.ChildrenInfo))) // slice length
		for v5 := range []ChildInfo(target.ChildrenInfo) {
			// --- [begin][write][alias](ChildInfo) ---
			if ((*Info)([]ChildInfo(target.ChildrenInfo)[v5])) == nil {
				buff.WriteUInt8(uint8(0)) // write nil byte
			} else {
				buff.WriteUInt8(uint8(1)) // write non-nil byte
				// --- [begin][write][struct](Info) ---
				buff.WriteInt(0) // [compatibility, unused]
				v6 := ((*Info)([]ChildInfo(target.ChildrenInfo)[v5])).MarshalBinaryWithContext(ctx)
				if v6 != nil {
					return v6
				}
				// --- [end][write][struct](Info) ---
			}
			// --- [end][write][alias](ChildInfo) ---
		}
		// --- [end][write][slice]([]ChildInfo) ---
	}
	// --- [end][write][alias](OtherChildInfo) ---
	// --- [begin][write][alias](shared.FloatList) ---
	if []float64(target.FavoriteNumbers) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte
		// --- [begin][write][slice]([]float64) ---
		buff.WriteInt(len([]float64(target.FavoriteNumbers))) // slice length
		for v7 := range []float64(target.FavoriteNumbers) {
			buff.WriteFloat64([]float64(target.FavoriteNumbers)[v7])
		}
		// --- [end][write][slice]([]float64) ---
	}
	// --- [end][write][alias](shared.FloatList) ---
	// --- [begin][write][alias](shared.StrMap) ---
	if map[string]int(target.NameMap) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte
		// --- [begin][write][map](map[string]int) ---
		buff.WriteInt(len(map[string]int(target.NameMap))) // map length
		for v8, v9 := range map[string]int(target.NameMap) {
			if ctx.IsStringTable() {
				v10 := ctx.Table.AddOrGet(v8)
				buff.WriteInt(v10) // write table index
			} else {
				buff.WriteString(v8) // write string
			}
			buff.WriteInt(v9)
		}
		// --- [end][write][map](map[string]int) ---
	}
	// --- [end][write][alias](shared.StrMap) ---
	// --- [begin][write][alias](shared.UIntPtrList) ---
	if []*uint32(target.U32s) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte
		// --- [begin][write][slice]([]*uint32) ---
		buff.WriteInt(len([]*uint32(target.U32s))) // slice length
		for v11 := range []*uint32(target.U32s) {
			if []*uint32(target.U32s)[v11] == nil {
				buff.WriteUInt8(uint8(0)) // write nil byte
			} else {
				buff.WriteUInt8(uint8(1)) // write non-nil byte
				buff.WriteUInt32(*[]*uint32(target.U32s)[v11])
			}
		}
		// --- [end][write][slice]([]*uint32) ---
	}
	// --- [end][write][alias](shared.UIntPtrList) ---
	// --- [begin][write][alias](shared.DoubleSlice) ---
	if [][]map[string]*int(target.Slices) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte
		// --- [begin][write][slice]([][]map[string]*int) ---
		buff.WriteInt(len([][]map[string]*int(target.Slices))) // slice length
		for v12 := range [][]map[string]*int(target.Slices) {
			if [][]map[string]*int(target.Slices)[v12] == nil {
				buff.WriteUInt8(uint8(0)) // write nil byte
			} else {
				buff.WriteUInt8(uint8(1)) // write non-nil byte
				// --- [begin][write][slice]([]map[string]*int) ---
				buff.WriteInt(len([][]map[string]*int(target.Slices)[v12])) // slice length
				for v13 := range [][]map[string]*int(target.Slices)[v12] {
					if [][]map[string]*int(target.Slices)[v12][v13] == nil {
						buff.WriteUInt8(uint8(0)) // write nil byte
					} else {
						buff.WriteUInt8(uint8(1)) // write non-nil byte
						// --- [begin][write][map](map[string]*int) ---
						buff.WriteInt(len([][]map[string]*int(target.Slices)[v12][v13])) // map length
						for v14, v15 := range [][]map[string]*int(target.Slices)[v12][v13] {
							if ctx.IsStringTable() {
								v16 := ctx.Table.AddOrGet(v14)
								buff.WriteInt(v16) // write table index
							} else {
								buff.WriteString(v14) // write string
							}
							if v15 == nil {
								buff.WriteUInt8(uint8(0)) // write nil byte
							} else {
								buff.WriteUInt8(uint8(1)) // write non-nil byte
								buff.WriteInt(*v15)
							}
						}
						// --- [end][write][map](map[string]*int) ---
					}
				}
				// --- [end][write][slice]([]map[string]*int) ---
			}
		}
		// --- [end][write][slice]([][]map[string]*int) ---
	}
	// --- [end][write][alias](shared.DoubleSlice) ---

	return nil
}

// UnmarshalBinary uses the data passed byte array to set all the internal properties of
// the Parent type
func (target *Parent) UnmarshalBinary(data []byte) error {
	ctx := NewDecodingContextFromBytes(data)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryFromReader uses the io.Reader data to set all the internal properties of
// the Parent type
func (target *Parent) UnmarshalBinaryFromReader(reader io.Reader) error {
	ctx := NewDecodingContextFromReader(reader)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryWithContext uses the context containing a string table and binary buffer to set all the internal properties of
// the Parent type
func (target *Parent) UnmarshalBinaryWithContext(ctx *DecodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	version := buff.ReadUInt8()

	if version > DefaultCodecVersion {
		return fmt.Errorf("Invalid Version Unmarshalling Parent. Expected %d or less, got %d", DefaultCodecVersion, version)
	}

	var v0 *shared.Name
	if buff.ReadUInt8() == uint8(0) {
		v0 = nil
	} else {
		// --- [begin][read][alias](shared.Name) ---
		var v1 string
		if ctx.IsStringTable() {
			v2 := buff.ReadInt() // read string index
			v1 = ctx.Table.At(v2)
		} else {
			v1 = buff.ReadString() // read string
		}
		v3 := shared.Name(v1)
		v0 = &v3
		// --- [end][read][alias](shared.Name) ---
	}
	target.Name = v0
	var v4 *shared.Age
	if buff.ReadUInt8() == uint8(0) {
		v4 = nil
	} else {
		// --- [begin][read][alias](shared.Age) ---
		var v5 *int
		if buff.ReadUInt8() == uint8(0) {
			v5 = nil
		} else {
			v6 := buff.ReadInt()
			v5 = &v6
		}
		v7 := shared.Age(v5)
		v4 = &v7
		// --- [end][read][alias](shared.Age) ---
	}
	target.Age = v4
	var v8 Child
	// --- [begin][read][alias](Child) ---
	var v9 string
	if ctx.IsStringTable() {
		v10 := buff.ReadInt() // read string index
		v9 = ctx.Table.At(v10)
	} else {
		v9 = buff.ReadString() // read string
	}
	v8 = Child(v9)
	// --- [end][read][alias](Child) ---
	target.FirstChild = v8
	var v11 ChildInfo
	// --- [begin][read][alias](ChildInfo) ---
	var v12 *Info
	if buff.ReadUInt8() == uint8(0) {
		v12 = nil
	} else {
		// --- [begin][read][struct](Info) ---
		v13 := new(Info)
		buff.ReadInt() // [compatibility, unused]
		v14 := v13.UnmarshalBinaryWithContext(ctx)
		if v14 != nil {
			return v14
		}
		v12 = v13
		// --- [end][read][struct](Info) ---
	}
	v11 = ChildInfo(v12)
	// --- [end][read][alias](ChildInfo) ---
	target.FirstChildInfo = v11
	var v15 []Child
	if buff.ReadUInt8() == uint8(0) {
		v15 = nil
	} else {
		// --- [begin][read][slice]([]Child) ---
		v16 := buff.ReadInt() // slice len
		v15 = make([]Child, v16)
		for v17 := range v16 {
			var v18 Child
			// --- [begin][read][alias](Child) ---
			var v19 string
			if ctx.IsStringTable() {
				v20 := buff.ReadInt() // read string index
				v19 = ctx.Table.At(v20)
			} else {
				v19 = buff.ReadString() // read string
			}
			v18 = Child(v19)
			// --- [end][read][alias](Child) ---
			v15[v17] = v18
		}
		// --- [end][read][slice]([]Child) ---
	}
	target.Children = v15
	var v21 OtherChildInfo
	// --- [begin][read][alias](OtherChildInfo) ---
	var v22 []ChildInfo
	if buff.ReadUInt8() == uint8(0) {
		v22 = nil
	} else {
		// --- [begin][read][slice]([]ChildInfo) ---
		v23 := buff.ReadInt() // slice len
		v22 = make([]ChildInfo, v23)
		for v24 := range v23 {
			var v25 ChildInfo
			// --- [begin][read][alias](ChildInfo) ---
			var v26 *Info
			if buff.ReadUInt8() == uint8(0) {
				v26 = nil
			} else {
				// --- [begin][read][struct](Info) ---
				v27 := new(Info)
				buff.ReadInt() // [compatibility, unused]
				v28 := v27.UnmarshalBinaryWithContext(ctx)
				if v28 != nil {
					return v28
				}
				v26 = v27
				// --- [end][read][struct](Info) ---
			}
			v25 = ChildInfo(v26)
			// --- [end][read][alias](ChildInfo) ---
			v22[v24] = v25
		}
		// --- [end][read][slice]([]ChildInfo) ---
	}
	v21 = OtherChildInfo(v22)
	// --- [end][read][alias](OtherChildInfo) ---
	target.ChildrenInfo = v21
	var v29 shared.FloatList
	// --- [begin][read][alias](shared.FloatList) ---
	var v30 []float64
	if buff.ReadUInt8() == uint8(0) {
		v30 = nil
	} else {
		// --- [begin][read][slice]([]float64) ---
		v31 := buff.ReadInt() // slice len
		v30 = make([]float64, v31)
		for v32 := range v31 {
			var v33 float64
			v33 = buff.ReadFloat64()
			v30[v32] = v33
		}
		// --- [end][read][slice]([]float64) ---
	}
	v29 = shared.FloatList(v30)
	// --- [end][read][alias](shared.FloatList) ---
	target.FavoriteNumbers = v29
	var v34 shared.StrMap
	// --- [begin][read][alias](shared.StrMap) ---
	var v35 map[string]int
	if buff.ReadUInt8() == uint8(0) {
		v35 = nil
	} else {
		// --- [begin][read][map](map[string]int) ---
		v36 := buff.ReadInt() // map len
		v35 = make(map[string]int, v36)
		for range v36 {
			var v37 string
			if ctx.IsStringTable() {
				v38 := buff.ReadInt() // read string index
				v37 = ctx.Table.At(v38)
			} else {
				v37 = buff.ReadString() // read string
			}
			var v39 int
			v39 = buff.ReadInt()
			v35[v37] = v39
		}
		// --- [end][read][map](map[string]int) ---
	}
	v34 = shared.StrMap(v35)
	// --- [end][read][alias](shared.StrMap) ---
	target.NameMap = v34
	var v40 shared.UIntPtrList
	// --- [begin][read][alias](shared.UIntPtrList) ---
	var v41 []*uint32
	if buff.ReadUInt8() == uint8(0) {
		v41 = nil
	} else {
		// --- [begin][read][slice]([]*uint32) ---
		v42 := buff.ReadInt() // slice len
		v41 = make([]*uint32, v42)
		for v43 := range v42 {
			var v44 *uint32
			if buff.ReadUInt8() == uint8(0) {
				v44 = nil
			} else {
				v45 := buff.ReadUInt32()
				v44 = &v45
			}
			v41[v43] = v44
		}
		// --- [end][read][slice]([]*uint32) ---
	}
	v40 = shared.UIntPtrList(v41)
	// --- [end][read][alias](shared.UIntPtrList) ---
	target.U32s = v40
	var v46 shared.DoubleSlice
	// --- [begin][read][alias](shared.DoubleSlice) ---
	var v47 [][]map[string]*int
	if buff.ReadUInt8() == uint8(0) {
		v47 = nil
	} else {
		// --- [begin][read][slice]([][]map[string]*int) ---
		v48 := buff.ReadInt() // slice len
		v47 = make([][]map[string]*int, v48)
		for v49 := range v48 {
			var v50 []map[string]*int
			if buff.ReadUInt8() == uint8(0) {
				v50 = nil
			} else {
				// --- [begin][read][slice]([]map[string]*int) ---
				v51 := buff.ReadInt() // slice len
				v50 = make([]map[string]*int, v51)
				for v52 := range v51 {
					var v53 map[string]*int
					if buff.ReadUInt8() == uint8(0) {
						v53 = nil
					} else {
						// --- [begin][read][map](map[string]*int) ---
						v54 := buff.ReadInt() // map len
						v53 = make(map[string]*int, v54)
						for range v54 {
							var v55 string
							if ctx.IsStringTable() {
								v56 := buff.ReadInt() // read string index
								v55 = ctx.Table.At(v56)
							} else {
								v55 = buff.ReadString() // read string
							}
							var v57 *int
							if buff.ReadUInt8() == uint8(0) {
								v57 = nil
							} else {
								v58 := buff.ReadInt()
								v57 = &v58
							}
							v53[v55] = v57
						}
						// --- [end][read][map](map[string]*int) ---
					}
					v50[v52] = v53
				}
				// --- [end][read][slice]([]map[string]*int) ---
			}
			v47[v49] = v50
		}
		// --- [end][read][slice]([][]map[string]*int) ---
	}
	v46 = shared.DoubleSlice(v47)
	// --- [end][read][alias](shared.DoubleSlice) ---
	target.Slices = v46

	return nil
}

//--------------------------------------------------------------------------
//  ParentStream
//--------------------------------------------------------------------------

// ParentStream is a single use field stream for the contents of an Parent instance. Instead of creating an instance and populating
// the fields on that instance, we provide a streaming iterator which yields (BingenFieldInfo, *BingenValue) tuples for each
// streamable element. All slices and maps will be flattened one depth and each element streamed individually.
type ParentStream struct {
	reader io.Reader
	ctx    *DecodingContext
	err    error
}

// Closes closes the internal io.Reader used to read and parse the Parent fields.
// This should be called once the stream is no longer needed.
func (stream *ParentStream) Close() {
	if closer, ok := stream.reader.(io.Closer); ok {
		closer.Close()
	}
	stream.ctx.Close()
}

// Error returns an error if one occurred during the process of streaming the Parent
// This can be checked after iterating through the Stream().
func (stream *ParentStream) Error() error {
	return stream.err
}

// NewParentStream creates a new ParentStream, which uses the io.Reader data to stream all internal fields of an Parent instance
func NewParentStream(reader io.Reader) bstream.BingenStream {
	ctx := NewDecodingContextFromReader(reader)

	return &ParentStream{
		ctx:    ctx,
		reader: reader,
	}
}

// Stream returns the iterator which will stream each field of the target type.
func (stream *ParentStream) Stream() iter.Seq2[bstream.BingenFieldInfo, *bstream.BingenValue] {
	return func(yield func(bstream.BingenFieldInfo, *bstream.BingenValue) bool) {
		var fi bstream.BingenFieldInfo

		ctx := stream.ctx
		buff := ctx.Buffer
		version := buff.ReadUInt8()

		if version > DefaultCodecVersion {
			stream.err = fmt.Errorf("Invalid Version Unmarshalling Parent. Expected %d or less, got %d", DefaultCodecVersion, version)
			return
		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[*shared.Name](),
			Name: "Name",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			var v0 *shared.Name
			// --- [begin][read][alias](shared.Name) ---
			var v1 string
			if ctx.IsStringTable() {
				v2 := buff.ReadInt() // read string index
				v1 = ctx.Table.At(v2)
			} else {
				v1 = buff.ReadString() // read string
			}
			v3 := shared.Name(v1)
			v0 = &v3
			// --- [end][read][alias](shared.Name) ---
			if !yield(fi, bstream.SingleV(v0)) {
				return
			}
		}
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[*shared.Age](),
			Name: "Age",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			var v4 *shared.Age
			// --- [begin][read][alias](shared.Age) ---
			var v5 *int
			if buff.ReadUInt8() == uint8(0) {
				v5 = nil
			} else {
				v6 := buff.ReadInt()
				v5 = &v6
			}
			v7 := shared.Age(v5)
			v4 = &v7
			// --- [end][read][alias](shared.Age) ---
			if !yield(fi, bstream.SingleV(v4)) {
				return
			}
		}
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[Child](),
			Name: "FirstChild",
		}
		var v8 Child
		// --- [begin][read][alias](Child) ---
		var v9 string
		if ctx.IsStringTable() {
			v10 := buff.ReadInt() // read string index
			v9 = ctx.Table.At(v10)
		} else {
			v9 = buff.ReadString() // read string
		}
		v8 = Child(v9)
		// --- [end][read][alias](Child) ---
		if !yield(fi, bstream.SingleV(v8)) {
			return
		}
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[ChildInfo](),
			Name: "FirstChildInfo",
		}
		var v11 ChildInfo
		// --- [begin][read][alias](ChildInfo) ---
		var v12 *Info
		if buff.ReadUInt8() == uint8(0) {
			v12 = nil
		} else {
			// --- [begin][read][struct](Info) ---
			v13 := new(Info)
			buff.ReadInt() // [compatibility, unused]
			v14 := v13.UnmarshalBinaryWithContext(ctx)
			if v14 != nil {
				stream.err = v14
				return
			}
			v12 = v13
			// --- [end][read][struct](Info) ---
		}
		v11 = ChildInfo(v12)
		// --- [end][read][alias](ChildInfo) ---
		if !yield(fi, bstream.SingleV(v11)) {
			return
		}
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[[]Child](),
			Name: "Children",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			// --- [begin][read][streaming-slice]([]Child) ---
			v15 := buff.ReadInt() // slice len
			for v16 := range v15 {
				var v17 Child
				// --- [begin][read][alias](Child) ---
				var v18 string
				if ctx.IsStringTable() {
					v19 := buff.ReadInt() // read string index
					v18 = ctx.Table.At(v19)
				} else {
					v18 = buff.ReadString() // read string
				}
				v17 = Child(v18)
				// --- [end][read][alias](Child) ---
				if !yield(fi, bstream.PairV(v16, v17)) {
					return
				}
			}
			// --- [end][read][streaming-slice]([]Child) ---
		}
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[OtherChildInfo](),
			Name: "ChildrenInfo",
		}
		// --- [begin][read][streaming-slice]([]ChildInfo) ---
		v20 := buff.ReadInt() // slice len
		for v21 := range v20 {
			var v22 ChildInfo
			// --- [begin][read][alias](ChildInfo) ---
			var v23 *Info
			if buff.ReadUInt8() == uint8(0) {
				v23 = nil
			} else {
				// --- [begin][read][struct](Info) ---
				v24 := new(Info)
				buff.ReadInt() // [compatibility, unused]
				v25 := v24.UnmarshalBinaryWithContext(ctx)
				if v25 != nil {
					stream.err = v25
					return
				}
				v23 = v24
				// --- [end][read][struct](Info) ---
			}
			v22 = ChildInfo(v23)
			// --- [end][read][alias](ChildInfo) ---
			if !yield(fi, bstream.PairV(v21, v22)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([]ChildInfo) ---
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[shared.FloatList](),
			Name: "FavoriteNumbers",
		}
		// --- [begin][read][streaming-slice]([]float64) ---
		v26 := buff.ReadInt() // slice len
		for v27 := range v26 {
			var v28 float64
			v28 = buff.ReadFloat64()
			if !yield(fi, bstream.PairV(v27, v28)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([]float64) ---
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[shared.StrMap](),
			Name: "NameMap",
		}
		// --- [begin][read][streaming-map](map[string]int) ---
		v29 := buff.ReadInt() // map len
		for range v29 {
			var v30 string
			if ctx.IsStringTable() {
				v31 := buff.ReadInt() // read string index
				v30 = ctx.Table.At(v31)
			} else {
				v30 = buff.ReadString() // read string
			}
			var v32 int
			v32 = buff.ReadInt()
			if !yield(fi, bstream.PairV(v30, v32)) {
				return
			}
		}
		// --- [end][read][streaming-map](map[string]int) ---
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[shared.UIntPtrList](),
			Name: "U32s",
		}
		// --- [begin][read][streaming-slice]([]*uint32) ---
		v33 := buff.ReadInt() // slice len
		for v34 := range v33 {
			var v35 *uint32
			if buff.ReadUInt8() == uint8(0) {
				v35 = nil
			} else {
				v36 := buff.ReadUInt32()
				v35 = &v36
			}
			if !yield(fi, bstream.PairV(v34, v35)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([]*uint32) ---
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[shared.DoubleSlice](),
			Name: "Slices",
		}
		// --- [begin][read][streaming-slice]([][]map[string]*int) ---
		v37 := buff.ReadInt() // slice len
		for v38 := range v37 {
			var v39 []map[string]*int
			if buff.ReadUInt8() == uint8(0) {
				v39 = nil
			} else {
				// --- [begin][read][slice]([]map[string]*int) ---
				v40 := buff.ReadInt() // slice len
				v39 = make([]map[string]*int, v40)
				for v41 := range v40 {
					var v42 map[string]*int
					if buff.ReadUInt8() == uint8(0) {
						v42 = nil
					} else {
						// --- [begin][read][map](map[string]*int) ---
						v43 := buff.ReadInt() // map len
						v42 = make(map[string]*int, v43)
						for range v43 {
							var v44 string
							if ctx.IsStringTable() {
								v45 := buff.ReadInt() // read string index
								v44 = ctx.Table.At(v45)
							} else {
								v44 = buff.ReadString() // read string
							}
							var v46 *int
							if buff.ReadUInt8() == uint8(0) {
								v46 = nil
							} else {
								v47 := buff.ReadInt()
								v46 = &v47
							}
							v42[v44] = v46
						}
						// --- [end][read][map](map[string]*int) ---
					}
					v39[v41] = v42
				}
				// --- [end][read][slice]([]map[string]*int) ---
			}
			if !yield(fi, bstream.PairV(v38, v39)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([][]map[string]*int) ---
	}
}
