////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package aliases

import (
	"fmt"
	"github.com/opencost/bingen/tests/shared"
	"io"
	"iter"
	"os"
	"reflect"
	"strings"
	"sync"
	"unsafe"

	util "github.com/opencost/bingen/pkg/util"
)

const (
	// GeneratorPackageName is the package the generator is targetting
	GeneratorPackageName string = "aliases"

	// BinaryTagStringTable is written and/or read prior to the existence of a string
	// table (where each index is encoded as a string entry in the resource
	BinaryTagStringTable string = "BGST"

	// MaxStringTableEntries is the hard upper bound on the number of entries
	// in a decoded string table, applied unconditionally to bound the
	// attacker-controlled allocation in NewSliceStringTableReaderFrom and
	// NewFileStringTableReaderFrom.
	MaxStringTableEntries = 1 << 20

	// DefaultCodecVersion is used for any resources listed in the Default version set
	DefaultCodecVersion uint8 = 16
)

//--------------------------------------------------------------------------
//  Configuration
//--------------------------------------------------------------------------

var (
	bingenConfigLock sync.RWMutex
	bingenConfig     *BingenConfiguration = DefaultBingenConfiguration()
)

// BingenConfiguration is used to set any custom configuration in the way files are encoded
// or decoded.
type BingenConfiguration struct {
	// FileBackedStringTableEnabled enables the use of file-backed string tables for streaming
	// bingen decoding.
	FileBackedStringTableEnabled bool

	// FileBackedStringTableDir is the directory to write the string table files for reading.
	FileBackedStringTableDir string
}

// DefaultBingenConfiguration creates the default implementation of the bingen configuration
// and returns it.
func DefaultBingenConfiguration() *BingenConfiguration {
	return &BingenConfiguration{
		FileBackedStringTableEnabled: false,
		FileBackedStringTableDir:     os.TempDir(),
	}
}

// ConfigureBingen accepts a new *BingenConfiguration instance which updates the internal decoder
// and encoder behavior.
func ConfigureBingen(config *BingenConfiguration) {
	bingenConfigLock.Lock()
	defer bingenConfigLock.Unlock()

	if config == nil {
		config = DefaultBingenConfiguration()
	}
	bingenConfig = config
}

// IsBingenFileBackedStringTableEnabled accessor for file backed string table configuration
func IsBingenFileBackedStringTableEnabled() bool {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableEnabled
}

// BingenFileBackedStringTableDir returns the directory configured for file backed string tables.
func BingenFileBackedStringTableDir() string {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableDir
}

//--------------------------------------------------------------------------
//  Type Map
//--------------------------------------------------------------------------

// Generated type map for resolving interface implementations to to concrete types
var typeMap map[string]reflect.Type = map[string]reflect.Type{
	"Info":   reflect.TypeFor[Info](),
	"Parent": reflect.TypeFor[Parent](),
}

//--------------------------------------------------------------------------
//  Type Helpers
//--------------------------------------------------------------------------

// isBinaryTag returns true when the first bytes in the provided binary matches the tag
func isBinaryTag(data []byte, tag string) bool {
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// isReaderBinaryTag is used to peek the header for an io.Reader Buffer
func isReaderBinaryTag(buff *util.Buffer, tag string) bool {
	data, err := buff.Peek(len(tag))
	if err != nil && err != io.EOF {
		panic(fmt.Sprintf("called Peek() on a non buffered reader: %s", err))
	}
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// appendBytes combines a and b into a new byte array
func appendBytes(a []byte, b []byte) []byte {
	al := len(a)
	bl := len(b)
	tl := al + bl

	// allocate a new byte array for the combined
	// use native copy for speedy byte copying
	result := make([]byte, tl)
	copy(result, a)
	copy(result[al:], b)

	return result
}

// typeToString determines the basic properties of the type, the qualifier, package path, and
// type name, and returns the qualified type
func typeToString(f interface{}) string {
	qual := ""
	t := reflect.TypeOf(f)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
		qual = "*"
	}

	return fmt.Sprintf("%s%s.%s", qual, t.PkgPath(), t.Name())
}

// resolveType uses the name of a type and returns the package, base type name, and whether
// or not it's a pointer.
func resolveType(t string) (pkg string, name string, isPtr bool) {
	isPtr = t[:1] == "*"
	if isPtr {
		t = t[1:]
	}

	slashIndex := strings.LastIndex(t, "/")
	if slashIndex >= 0 {
		t = t[slashIndex+1:]
	}
	parts := strings.Split(t, ".")
	if parts[0] == GeneratorPackageName {
		parts[0] = ""
	}

	pkg = parts[0]
	name = parts[1]
	return
}

//--------------------------------------------------------------------------
//  Stream Helpers
//--------------------------------------------------------------------------

// StreamFactoryFunc is an alias for a func that creates a BingenStream implementation.
// It returns an error to allow the constructor to surface decoding-context
// failures (e.g. an oversized or malformed string table) up to the caller
// rather than panicking.
type StreamFactoryFunc func(io.Reader) (BingenStream, error)

// Generated streamable factory map for finding the specific new stream methods
// by T type
var streamFactoryMap map[reflect.Type]StreamFactoryFunc = map[reflect.Type]StreamFactoryFunc{
	reflect.TypeFor[Parent](): NewParentStream,
}

// NewStreamFor accepts an io.Reader, and returns a new BingenStream for the generic T
// type provided _if_ it is a registered bingen type that is annotated as 'streamable'. See
// the streamFactoryMap for generated type listings.
func NewStreamFor[T any](reader io.Reader) (BingenStream, error) {
	typeKey := reflect.TypeFor[T]()

	factory, ok := streamFactoryMap[typeKey]
	if !ok {
		return nil, fmt.Errorf("the type: %s is not a registered bingen streamable type", typeKey.Name())
	}

	return factory(reader)
}

// BingenStream is the stream interface for all streamable types
type BingenStream interface {
	// Stream returns the iterator which will stream each field of the target type and
	// return the field info as well as the value.
	Stream() iter.Seq2[BingenFieldInfo, *BingenValue]

	// Close will close any dynamic io.Reader used to stream in the fields
	Close()

	// Error returns an error if one occurred during the process of streaming the type's fields.
	// This can be checked after iterating through the Stream().
	Error() error
}

// BingenValue contains the value of a field as well as any index/key associated with that value.
type BingenValue struct {
	Value any
	Index any
}

// IsNil is just a method accessor way to check to see if the value returned was nil
func (bv *BingenValue) IsNil() bool {
	return bv == nil
}

// creates a single BingenValue instance without a key or index
func singleV(value any) *BingenValue {
	return &BingenValue{
		Value: value,
	}
}

// creates a pair of key/index and value.
func pairV(index any, value any) *BingenValue {
	return &BingenValue{
		Value: value,
		Index: index,
	}
}

// BingenFieldInfo contains the type of the field being streamed as well as the name of the field.
type BingenFieldInfo struct {
	Type reflect.Type
	Name string
}

//--------------------------------------------------------------------------
//  String Table Writer
//--------------------------------------------------------------------------

// StringTableWriter maps strings to specific indices for encoding
type StringTableWriter struct {
	l       sync.Mutex
	indices map[string]int
	next    int
}

// NewStringTableWriter Creates a new StringTableWriter instance with provided contents
func NewStringTableWriter(contents ...string) *StringTableWriter {
	st := &StringTableWriter{
		indices: make(map[string]int, len(contents)),
		next:    len(contents),
	}

	for i, entry := range contents {
		st.indices[entry] = i
	}

	return st
}

// AddOrGet atomically retrieves a string entry's index if it exist. Otherwise, it will
// add the entry and return the index.
func (st *StringTableWriter) AddOrGet(s string) int {
	st.l.Lock()
	defer st.l.Unlock()

	if ind, ok := st.indices[s]; ok {
		return ind
	}

	current := st.next
	st.next++

	st.indices[s] = current
	return current
}

// ToSlice Converts the contents to a string array for encoding.
func (st *StringTableWriter) ToSlice() []string {
	st.l.Lock()
	defer st.l.Unlock()

	if st.next == 0 {
		return []string{}
	}

	sl := make([]string, st.next)
	for s, i := range st.indices {
		sl[i] = s
	}
	return sl
}

// ToBytes Converts the contents to a binary encoded representation
func (st *StringTableWriter) ToBytes() []byte {
	buff := util.NewBuffer()
	buff.WriteBytes([]byte(BinaryTagStringTable)) // bingen table header

	strs := st.ToSlice()

	buff.WriteInt(len(strs)) // table length
	for _, s := range strs {
		buff.WriteString(s)
	}

	return buff.Bytes()
}

//--------------------------------------------------------------------------
//  String Table Reader
//--------------------------------------------------------------------------

// StringTableReader is the interface used to read the string table from the decoding.
type StringTableReader interface {
	// At returns the string entry at a specific index, or panics on out of bounds.
	At(index int) string

	// Len returns the total number of strings loaded in the string table.
	Len() int

	// Close will clear the loaded table, and drop any external resources used.
	Close() error
}

// SliceStringTableReader is a basic pre-loaded []string that provides index-based access.
// The cost of this implementation is holding all strings in memory, which provides faster
// lookup performance at the expense of memory usage.
type SliceStringTableReader struct {
	table []string
}

// NewSliceStringTableReaderFrom creates a new SliceStringTableReader instance loading
// data directly from the buffer. The buffer's position should start at the table length.
//
// The table length is unconditionally capped at MaxStringTableEntries to bound
// the attacker-controlled allocation. In byte-buffer mode it is also bounded
// by the buffer's remaining bytes; in reader-mode buffer.Remaining() returns
// -1 and the underlying read fails naturally if the stream is short.
func NewSliceStringTableReaderFrom(buffer *util.Buffer) (StringTableReader, error) {
	tl := buffer.ReadInt()
	if tl < 0 {
		return nil, fmt.Errorf("%s: invalid string table length: %d", GeneratorPackageName, tl)
	}
	if tl > MaxStringTableEntries {
		return nil, fmt.Errorf("%s: string table length %d exceeds MaxStringTableEntries %d", GeneratorPackageName, tl, MaxStringTableEntries)
	}
	// Each entry has at least a 4-byte uint32 length prefix, so an honest
	// table of tl entries needs at minimum tl*4 remaining bytes. Comparing
	// against rem (bytes) rather than rem/4 (max-entries-from-bytes) would
	// have left a tl*4 mismatch — a payload could legitimately advertise
	// a 4x oversize table within the remaining-byte bound.
	if rem := buffer.Remaining(); rem >= 0 && tl > rem/4 {
		return nil, fmt.Errorf("%s: string table length %d exceeds capacity for %d remaining bytes", GeneratorPackageName, tl, rem)
	}

	var table []string
	if tl > 0 {
		table = make([]string, tl)
		for i := range tl {
			table[i] = buffer.ReadString()
		}
	}

	return &SliceStringTableReader{
		table: table,
	}, nil
}

// At returns the string entry at a specific index, or panics on out of bounds.
func (sstr *SliceStringTableReader) At(index int) string {
	if index < 0 || index >= len(sstr.table) {
		panic(fmt.Errorf("%s: string table index out of bounds: %d", GeneratorPackageName, index))
	}

	return sstr.table[index]
}

// Len returns the total number of strings loaded in the string table.
func (sstr *SliceStringTableReader) Len() int {
	if sstr == nil {
		return 0
	}

	return len(sstr.table)
}

// Close for the slice tables just nils out the slice and returns
func (sstr *SliceStringTableReader) Close() error {
	sstr.table = nil
	return nil
}

// fileStringRef maps a bingen string-table index to a payload stored in a temp file.
type fileStringRef struct {
	off    int64
	length int
}

// FileStringTableReader leverages a local file to write string table data for lookup. On
// memory focused systems, this allows a slower parse with a significant decrease in memory
// usage. This implementation is often pair with streaming readers for high throughput with
// reduced memory usage.
type FileStringTableReader struct {
	f    *os.File
	refs []fileStringRef
}

// NewFileStringTableReaderFrom reads exactly tl length-prefixed string payloads
// from buffer and appends each payload to a new temp file. It does not retain
// full strings in memory.
//
// The table length is unconditionally capped at MaxStringTableEntries to bound
// the attacker-controlled allocation of refs. The temp file is closed and
// removed on any failure path.
func NewFileStringTableReaderFrom(buffer *util.Buffer, dir string) (StringTableReader, error) {
	// helper func to cast a string in-place to a byte slice.
	// NOTE: Return value is READ-ONLY. DO NOT MODIFY!
	byteSliceFor := func(s string) []byte {
		return unsafe.Slice(unsafe.StringData(s), len(s))
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, fmt.Errorf("%s: failed to create string table directory: %w", GeneratorPackageName, err)
	}

	f, err := os.CreateTemp(dir, fmt.Sprintf("%s-bgst-*", GeneratorPackageName))
	if err != nil {
		return nil, fmt.Errorf("%s: failed to create string table file: %w", GeneratorPackageName, err)
	}

	cleanup := func() {
		path := f.Name()
		_ = f.Close()
		if path != "" {
			_ = os.Remove(path)
		}
	}

	// table length
	tl := buffer.ReadInt()
	if tl < 0 {
		cleanup()
		return nil, fmt.Errorf("%s: invalid string table length: %d", GeneratorPackageName, tl)
	}
	if tl > MaxStringTableEntries {
		cleanup()
		return nil, fmt.Errorf("%s: string table length %d exceeds MaxStringTableEntries %d", GeneratorPackageName, tl, MaxStringTableEntries)
	}

	var refs []fileStringRef
	if tl > 0 {
		refs = make([]fileStringRef, tl)

		for i := range tl {
			payload := byteSliceFor(buffer.ReadString())

			var off int64
			if len(payload) > 0 {
				off, err = f.Seek(0, io.SeekEnd)
				if err != nil {
					cleanup()
					return nil, fmt.Errorf("%s: failed to seek string table file: %w", GeneratorPackageName, err)
				}
				if _, werr := f.Write(payload); werr != nil {
					cleanup()
					return nil, fmt.Errorf("%s: failed to write string table entry %d: %w", GeneratorPackageName, i, werr)
				}
			}

			refs[i] = fileStringRef{
				off:    off,
				length: len(payload),
			}
		}
	}

	return &FileStringTableReader{
		f:    f,
		refs: refs,
	}, nil
}

// At returns the string from the internal file using the reference's offset and length.
func (fstr *FileStringTableReader) At(index int) string {
	if fstr == nil || fstr.f == nil {
		panic(fmt.Errorf("%s: failed to read file string table data", GeneratorPackageName))
	}
	if index < 0 || index >= len(fstr.refs) {
		panic(fmt.Errorf("%s: string table index out of bounds: %d", GeneratorPackageName, index))
	}

	ref := fstr.refs[index]
	if ref.length == 0 {
		return ""
	}

	b := make([]byte, ref.length)
	_, err := fstr.f.ReadAt(b, ref.off)
	if err != nil {
		return ""
	}

	// cast the allocated bytes to a string in-place, as we
	// were the ones that allocated the bytes
	return unsafe.String(unsafe.SliceData(b), len(b))
}

// Len returns the total number of strings loaded in the string table.
func (fstr *FileStringTableReader) Len() int {
	if fstr == nil {
		return 0
	}

	return len(fstr.refs)
}

// Close for the file string table reader closes the file and deletes it.
func (fstr *FileStringTableReader) Close() error {
	if fstr == nil || fstr.f == nil {
		return nil
	}

	path := fstr.f.Name()
	err := fstr.f.Close()
	fstr.f = nil
	fstr.refs = nil

	if path != "" {
		_ = os.Remove(path)
	}

	return err
}

//--------------------------------------------------------------------------
//  Codec Context
//--------------------------------------------------------------------------

// EncodingContext is a context object passed to the encoders to ensure reuse of buffer
// and table data
type EncodingContext struct {
	Buffer *util.Buffer
	Table  *StringTableWriter
}

// IsStringTable returns true if the table is available
func (ec *EncodingContext) IsStringTable() bool {
	return ec.Table != nil
}

// DecodingContext is a context object passed to the decoders to ensure parent objects
// reuse as much data as possible
type DecodingContext struct {
	Buffer *util.Buffer
	Table  StringTableReader
}

// NewDecodingContextFromBytes creates a new DecodingContext instance using an byte slice
func NewDecodingContextFromBytes(data []byte) (*DecodingContext, error) {
	var table StringTableReader

	buff := util.NewBufferFromBytes(data)

	// string table header validation
	if isBinaryTag(data, BinaryTagStringTable) {
		buff.ReadBytes(len(BinaryTagStringTable)) // strip tag length

		// always use a slice string table with a byte array since the
		// data is already in memory
		var err error
		table, err = NewSliceStringTableReaderFrom(buff)
		if err != nil {
			return nil, err
		}
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}, nil
}

// NewDecodingContextFromReader creates a new DecodingContext instance using an io.Reader
// implementation
func NewDecodingContextFromReader(reader io.Reader) (*DecodingContext, error) {
	var table StringTableReader

	buff := util.NewBufferFromReader(reader)

	if isReaderBinaryTag(buff, BinaryTagStringTable) {
		buff.ReadBytes(len(BinaryTagStringTable)) // strip tag length

		// create correct string table implementation
		var err error
		if IsBingenFileBackedStringTableEnabled() {
			table, err = NewFileStringTableReaderFrom(buff, BingenFileBackedStringTableDir())
		} else {
			table, err = NewSliceStringTableReaderFrom(buff)
		}
		if err != nil {
			return nil, err
		}
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}, nil
}

// IsStringTable returns true if the table is available
func (dc *DecodingContext) IsStringTable() bool {
	return dc.Table != nil && dc.Table.Len() > 0
}

// Close will ensure that any string table resources and buffer resources are
// cleaned up.
func (dc *DecodingContext) Close() {
	if dc.Table != nil {
		_ = dc.Table.Close()
		dc.Table = nil
	}
}

//--------------------------------------------------------------------------
//  Binary Codec
//--------------------------------------------------------------------------

// BinEncoder is an encoding interface which defines a context based marshal contract.
type BinEncoder interface {
	MarshalBinaryWithContext(*EncodingContext) error
}

// BinDecoder is a decoding interface which defines a context based unmarshal contract.
type BinDecoder interface {
	UnmarshalBinaryWithContext(*DecodingContext) error
}

//--------------------------------------------------------------------------
//  Info
//--------------------------------------------------------------------------

// MarshalBinary serializes the internal properties of this Info instance
// into a byte array
func (target *Info) MarshalBinary() (data []byte, err error) {
	ctx := &EncodingContext{
		Buffer: util.NewBuffer(),
		Table:  nil,
	}

	e := target.MarshalBinaryWithContext(ctx)
	if e != nil {
		return nil, e
	}

	encBytes := ctx.Buffer.Bytes()
	return encBytes, nil
}

// MarshalBinaryWithContext serializes the internal properties of this Info instance
// into a byte array leveraging a predefined context.
func (target *Info) MarshalBinaryWithContext(ctx *EncodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	buff.WriteUInt8(DefaultCodecVersion) // version

	if ctx.IsStringTable() {
		a := ctx.Table.AddOrGet(target.Name)
		buff.WriteInt(a) // write table index
	} else {
		buff.WriteString(target.Name) // write string
	}

	buff.WriteUInt(target.Age) // write uint

	return nil
}

// UnmarshalBinary uses the data passed byte array to set all the internal properties of
// the Info type
func (target *Info) UnmarshalBinary(data []byte) error {
	ctx, err := NewDecodingContextFromBytes(data)
	if err != nil {
		return err
	}
	defer ctx.Close()

	return target.UnmarshalBinaryWithContext(ctx)
}

// UnmarshalBinaryFromReader uses the io.Reader data to set all the internal properties of
// the Info type
func (target *Info) UnmarshalBinaryFromReader(reader io.Reader) error {
	ctx, err := NewDecodingContextFromReader(reader)
	if err != nil {
		return err
	}
	defer ctx.Close()

	return target.UnmarshalBinaryWithContext(ctx)
}

// UnmarshalBinaryWithContext uses the context containing a string table and binary buffer to set all the internal properties of
// the Info type
func (target *Info) UnmarshalBinaryWithContext(ctx *DecodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	version := buff.ReadUInt8()

	if version > DefaultCodecVersion {
		return fmt.Errorf("Invalid Version Unmarshalling Info. Expected %d or less, got %d", DefaultCodecVersion, version)
	}

	var b string
	if ctx.IsStringTable() {
		c := buff.ReadInt() // read string index
		b = ctx.Table.At(c)
	} else {
		b = buff.ReadString() // read string
	}
	a := b
	target.Name = a

	d := buff.ReadUInt() // read uint
	target.Age = d

	return nil
}

//--------------------------------------------------------------------------
//  Parent
//--------------------------------------------------------------------------

// MarshalBinary serializes the internal properties of this Parent instance
// into a byte array
func (target *Parent) MarshalBinary() (data []byte, err error) {
	ctx := &EncodingContext{
		Buffer: util.NewBuffer(),
		Table:  NewStringTableWriter(),
	}

	e := target.MarshalBinaryWithContext(ctx)
	if e != nil {
		return nil, e
	}

	encBytes := ctx.Buffer.Bytes()
	sTableBytes := ctx.Table.ToBytes()
	merged := appendBytes(sTableBytes, encBytes)
	return merged, nil
}

// MarshalBinaryWithContext serializes the internal properties of this Parent instance
// into a byte array leveraging a predefined context.
func (target *Parent) MarshalBinaryWithContext(ctx *EncodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	buff.WriteUInt8(DefaultCodecVersion) // version

	if target.Name == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][alias](shared.Name) ---

		if ctx.IsStringTable() {
			a := ctx.Table.AddOrGet(string(*target.Name))
			buff.WriteInt(a) // write table index
		} else {
			buff.WriteString(string(*target.Name)) // write string
		}

		// --- [end][write][alias](shared.Name) ---
	}
	if target.Age == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][alias](shared.Age) ---
		if ((*int)(*target.Age)) == nil {
			buff.WriteUInt8(uint8(0)) // write nil byte
		} else {
			buff.WriteUInt8(uint8(1)) // write non-nil byte

			buff.WriteInt(*((*int)(*target.Age))) // write int

		}
		// --- [end][write][alias](shared.Age) ---
	}

	// --- [begin][write][alias](Child) ---

	if ctx.IsStringTable() {
		b := ctx.Table.AddOrGet(string(target.FirstChild))
		buff.WriteInt(b) // write table index
	} else {
		buff.WriteString(string(target.FirstChild)) // write string
	}

	// --- [end][write][alias](Child) ---

	// --- [begin][write][alias](ChildInfo) ---
	if ((*Info)(target.FirstChildInfo)) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][struct](Info) ---
		buff.WriteInt(0) // [compatibility, unused]
		errA := ((*Info)(target.FirstChildInfo)).MarshalBinaryWithContext(ctx)
		if errA != nil {
			return errA
		}
		// --- [end][write][struct](Info) ---

	}
	// --- [end][write][alias](ChildInfo) ---
	if target.Children == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([]Child) ---
		buff.WriteInt(len(target.Children)) // slice length
		for i := range target.Children {
			// --- [begin][write][alias](Child) ---

			if ctx.IsStringTable() {
				c := ctx.Table.AddOrGet(string(target.Children[i]))
				buff.WriteInt(c) // write table index
			} else {
				buff.WriteString(string(target.Children[i])) // write string
			}

			// --- [end][write][alias](Child) ---
		}
		// --- [end][write][slice]([]Child) ---

	}

	// --- [begin][write][alias](OtherChildInfo) ---
	if []ChildInfo(target.ChildrenInfo) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([]ChildInfo) ---
		buff.WriteInt(len([]ChildInfo(target.ChildrenInfo))) // slice length
		for j := range []ChildInfo(target.ChildrenInfo) {
			// --- [begin][write][alias](ChildInfo) ---
			if ((*Info)([]ChildInfo(target.ChildrenInfo)[j])) == nil {
				buff.WriteUInt8(uint8(0)) // write nil byte
			} else {
				buff.WriteUInt8(uint8(1)) // write non-nil byte

				// --- [begin][write][struct](Info) ---
				buff.WriteInt(0) // [compatibility, unused]
				errB := ((*Info)([]ChildInfo(target.ChildrenInfo)[j])).MarshalBinaryWithContext(ctx)
				if errB != nil {
					return errB
				}
				// --- [end][write][struct](Info) ---

			}
			// --- [end][write][alias](ChildInfo) ---
		}
		// --- [end][write][slice]([]ChildInfo) ---

	}
	// --- [end][write][alias](OtherChildInfo) ---

	// --- [begin][write][alias](shared.FloatList) ---
	if []float64(target.FavoriteNumbers) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([]float64) ---
		buff.WriteInt(len([]float64(target.FavoriteNumbers))) // slice length
		for ii := range []float64(target.FavoriteNumbers) {
			buff.WriteFloat64([]float64(target.FavoriteNumbers)[ii]) // write float64

		}
		// --- [end][write][slice]([]float64) ---

	}
	// --- [end][write][alias](shared.FloatList) ---

	// --- [begin][write][alias](shared.StrMap) ---
	if map[string]int(target.NameMap) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][map](map[string]int) ---
		buff.WriteInt(len(map[string]int(target.NameMap))) // map length
		for v, z := range map[string]int(target.NameMap) {
			if ctx.IsStringTable() {
				d := ctx.Table.AddOrGet(v)
				buff.WriteInt(d) // write table index
			} else {
				buff.WriteString(v) // write string
			}

			buff.WriteInt(z) // write int

		}
		// --- [end][write][map](map[string]int) ---

	}
	// --- [end][write][alias](shared.StrMap) ---

	// --- [begin][write][alias](shared.UIntPtrList) ---
	if []*uint32(target.U32s) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([]*uint32) ---
		buff.WriteInt(len([]*uint32(target.U32s))) // slice length
		for jj := range []*uint32(target.U32s) {
			if []*uint32(target.U32s)[jj] == nil {
				buff.WriteUInt8(uint8(0)) // write nil byte
			} else {
				buff.WriteUInt8(uint8(1)) // write non-nil byte

				buff.WriteUInt32(*[]*uint32(target.U32s)[jj]) // write uint32

			}
		}
		// --- [end][write][slice]([]*uint32) ---

	}
	// --- [end][write][alias](shared.UIntPtrList) ---

	// --- [begin][write][alias](shared.DoubleSlice) ---
	if [][]map[string]*int(target.Slices) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([][]map[string]*int) ---
		buff.WriteInt(len([][]map[string]*int(target.Slices))) // slice length
		for iii := range [][]map[string]*int(target.Slices) {
			if [][]map[string]*int(target.Slices)[iii] == nil {
				buff.WriteUInt8(uint8(0)) // write nil byte
			} else {
				buff.WriteUInt8(uint8(1)) // write non-nil byte

				// --- [begin][write][slice]([]map[string]*int) ---
				buff.WriteInt(len([][]map[string]*int(target.Slices)[iii])) // slice length
				for jjj := range [][]map[string]*int(target.Slices)[iii] {
					if [][]map[string]*int(target.Slices)[iii][jjj] == nil {
						buff.WriteUInt8(uint8(0)) // write nil byte
					} else {
						buff.WriteUInt8(uint8(1)) // write non-nil byte

						// --- [begin][write][map](map[string]*int) ---
						buff.WriteInt(len([][]map[string]*int(target.Slices)[iii][jjj])) // map length
						for vv, zz := range [][]map[string]*int(target.Slices)[iii][jjj] {
							if ctx.IsStringTable() {
								e := ctx.Table.AddOrGet(vv)
								buff.WriteInt(e) // write table index
							} else {
								buff.WriteString(vv) // write string
							}
							if zz == nil {
								buff.WriteUInt8(uint8(0)) // write nil byte
							} else {
								buff.WriteUInt8(uint8(1)) // write non-nil byte

								buff.WriteInt(*zz) // write int

							}
						}
						// --- [end][write][map](map[string]*int) ---

					}
				}
				// --- [end][write][slice]([]map[string]*int) ---

			}
		}
		// --- [end][write][slice]([][]map[string]*int) ---

	}
	// --- [end][write][alias](shared.DoubleSlice) ---

	return nil
}

// UnmarshalBinary uses the data passed byte array to set all the internal properties of
// the Parent type
func (target *Parent) UnmarshalBinary(data []byte) error {
	ctx, err := NewDecodingContextFromBytes(data)
	if err != nil {
		return err
	}
	defer ctx.Close()

	return target.UnmarshalBinaryWithContext(ctx)
}

// UnmarshalBinaryFromReader uses the io.Reader data to set all the internal properties of
// the Parent type
func (target *Parent) UnmarshalBinaryFromReader(reader io.Reader) error {
	ctx, err := NewDecodingContextFromReader(reader)
	if err != nil {
		return err
	}
	defer ctx.Close()

	return target.UnmarshalBinaryWithContext(ctx)
}

// UnmarshalBinaryWithContext uses the context containing a string table and binary buffer to set all the internal properties of
// the Parent type
func (target *Parent) UnmarshalBinaryWithContext(ctx *DecodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	version := buff.ReadUInt8()

	if version > DefaultCodecVersion {
		return fmt.Errorf("Invalid Version Unmarshalling Parent. Expected %d or less, got %d", DefaultCodecVersion, version)
	}

	if buff.ReadUInt8() == uint8(0) {
		target.Name = nil
	} else {
		// --- [begin][read][alias](shared.Name) ---
		var a string
		var c string
		if ctx.IsStringTable() {
			d := buff.ReadInt() // read string index
			c = ctx.Table.At(d)
		} else {
			c = buff.ReadString() // read string
		}
		b := c
		a = b

		e := shared.Name(a)
		target.Name = &e
		// --- [end][read][alias](shared.Name) ---
	}

	if buff.ReadUInt8() == uint8(0) {
		target.Age = nil
	} else {
		// --- [begin][read][alias](shared.Age) ---
		var f *int
		if buff.ReadUInt8() == uint8(0) {
			f = nil
		} else {

			g := buff.ReadInt() // read int
			f = &g

		}
		h := shared.Age(f)
		target.Age = &h
		// --- [end][read][alias](shared.Age) ---
	}

	// --- [begin][read][alias](Child) ---
	var l string
	var n string
	if ctx.IsStringTable() {
		o := buff.ReadInt() // read string index
		n = ctx.Table.At(o)
	} else {
		n = buff.ReadString() // read string
	}
	m := n
	l = m

	target.FirstChild = Child(l)
	// --- [end][read][alias](Child) ---

	// --- [begin][read][alias](ChildInfo) ---
	var p *Info
	if buff.ReadUInt8() == uint8(0) {
		p = nil
	} else {
		// --- [begin][read][struct](Info) ---
		q := new(Info)
		buff.ReadInt() // [compatibility, unused]
		errA := q.UnmarshalBinaryWithContext(ctx)
		if errA != nil {
			return errA
		}
		p = q
		// --- [end][read][struct](Info) ---

	}

	target.FirstChildInfo = ChildInfo(p)
	// --- [end][read][alias](ChildInfo) ---

	if buff.ReadUInt8() == uint8(0) {
		target.Children = nil
	} else {
		// --- [begin][read][slice]([]Child) ---
		s := buff.ReadInt() // slice len
		if s < 0 {
			return fmt.Errorf("bingen: invalid slice length %d", s)
		}
		// In byte-buffer mode Remaining() upper-bounds the length to reject
		// length-prefix DoS; in reader-mode Remaining() returns -1 ("unknown") and
		// we trust the underlying read to fail if the stream is short.
		if rem := buff.Remaining(); rem >= 0 && s > rem {
			return fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", s, rem)
		}
		r := make([]Child, s)
		for i := range s {
			// --- [begin][read][alias](Child) ---
			var u string
			var x string
			if ctx.IsStringTable() {
				y := buff.ReadInt() // read string index
				x = ctx.Table.At(y)
			} else {
				x = buff.ReadString() // read string
			}
			w := x
			u = w

			t := Child(u)
			// --- [end][read][alias](Child) ---

			r[i] = t
		}
		target.Children = r
		// --- [end][read][slice]([]Child) ---

	}

	// --- [begin][read][alias](OtherChildInfo) ---
	var aa []ChildInfo
	if buff.ReadUInt8() == uint8(0) {
		aa = nil
	} else {
		// --- [begin][read][slice]([]ChildInfo) ---
		cc := buff.ReadInt() // slice len
		if cc < 0 {
			return fmt.Errorf("bingen: invalid slice length %d", cc)
		}
		// In byte-buffer mode Remaining() upper-bounds the length to reject
		// length-prefix DoS; in reader-mode Remaining() returns -1 ("unknown") and
		// we trust the underlying read to fail if the stream is short.
		if rem := buff.Remaining(); rem >= 0 && cc > rem {
			return fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", cc, rem)
		}
		bb := make([]ChildInfo, cc)
		for j := range cc {
			// --- [begin][read][alias](ChildInfo) ---
			var ee *Info
			if buff.ReadUInt8() == uint8(0) {
				ee = nil
			} else {
				// --- [begin][read][struct](Info) ---
				ff := new(Info)
				buff.ReadInt() // [compatibility, unused]
				errB := ff.UnmarshalBinaryWithContext(ctx)
				if errB != nil {
					return errB
				}
				ee = ff
				// --- [end][read][struct](Info) ---

			}

			dd := ChildInfo(ee)
			// --- [end][read][alias](ChildInfo) ---

			bb[j] = dd
		}
		aa = bb
		// --- [end][read][slice]([]ChildInfo) ---

	}

	target.ChildrenInfo = OtherChildInfo(aa)
	// --- [end][read][alias](OtherChildInfo) ---

	// --- [begin][read][alias](shared.FloatList) ---
	var gg []float64
	if buff.ReadUInt8() == uint8(0) {
		gg = nil
	} else {
		// --- [begin][read][slice]([]float64) ---
		ll := buff.ReadInt() // slice len
		if ll < 0 {
			return fmt.Errorf("bingen: invalid slice length %d", ll)
		}
		// In byte-buffer mode Remaining() upper-bounds the length to reject
		// length-prefix DoS; in reader-mode Remaining() returns -1 ("unknown") and
		// we trust the underlying read to fail if the stream is short.
		if rem := buff.Remaining(); rem >= 0 && ll > rem {
			return fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", ll, rem)
		}
		hh := make([]float64, ll)
		for ii := range ll {
			var mm float64
			nn := buff.ReadFloat64() // read float64
			mm = nn

			hh[ii] = mm
		}
		gg = hh
		// --- [end][read][slice]([]float64) ---

	}

	target.FavoriteNumbers = shared.FloatList(gg)
	// --- [end][read][alias](shared.FloatList) ---

	// --- [begin][read][alias](shared.StrMap) ---
	var oo map[string]int
	if buff.ReadUInt8() == uint8(0) {
		oo = nil
	} else {
		// --- [begin][read][map](map[string]int) ---
		qq := buff.ReadInt() // map len
		if qq < 0 {
			return fmt.Errorf("bingen: invalid map length %d", qq)
		}
		// Remaining() returns -1 in reader-mode; only apply the upper bound when
		// the buffer is byte-backed and the value is meaningful.
		if rem := buff.Remaining(); rem >= 0 && qq > rem {
			return fmt.Errorf("bingen: map length %d exceeds remaining bytes %d", qq, rem)
		}
		pp := make(map[string]int, qq)
		for range qq {
			var v string
			var ss string
			if ctx.IsStringTable() {
				tt := buff.ReadInt() // read string index
				ss = ctx.Table.At(tt)
			} else {
				ss = buff.ReadString() // read string
			}
			rr := ss
			v = rr

			var z int
			uu := buff.ReadInt() // read int
			z = uu

			pp[v] = z
		}
		oo = pp
		// --- [end][read][map](map[string]int) ---

	}

	target.NameMap = shared.StrMap(oo)
	// --- [end][read][alias](shared.StrMap) ---

	// --- [begin][read][alias](shared.UIntPtrList) ---
	var ww []*uint32
	if buff.ReadUInt8() == uint8(0) {
		ww = nil
	} else {
		// --- [begin][read][slice]([]*uint32) ---
		yy := buff.ReadInt() // slice len
		if yy < 0 {
			return fmt.Errorf("bingen: invalid slice length %d", yy)
		}
		// In byte-buffer mode Remaining() upper-bounds the length to reject
		// length-prefix DoS; in reader-mode Remaining() returns -1 ("unknown") and
		// we trust the underlying read to fail if the stream is short.
		if rem := buff.Remaining(); rem >= 0 && yy > rem {
			return fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", yy, rem)
		}
		xx := make([]*uint32, yy)
		for jj := range yy {
			var aaa *uint32
			if buff.ReadUInt8() == uint8(0) {
				aaa = nil
			} else {

				bbb := buff.ReadUInt32() // read uint32
				aaa = &bbb

			}

			xx[jj] = aaa
		}
		ww = xx
		// --- [end][read][slice]([]*uint32) ---

	}

	target.U32s = shared.UIntPtrList(ww)
	// --- [end][read][alias](shared.UIntPtrList) ---

	// --- [begin][read][alias](shared.DoubleSlice) ---
	var ccc [][]map[string]*int
	if buff.ReadUInt8() == uint8(0) {
		ccc = nil
	} else {
		// --- [begin][read][slice]([][]map[string]*int) ---
		eee := buff.ReadInt() // slice len
		if eee < 0 {
			return fmt.Errorf("bingen: invalid slice length %d", eee)
		}
		// In byte-buffer mode Remaining() upper-bounds the length to reject
		// length-prefix DoS; in reader-mode Remaining() returns -1 ("unknown") and
		// we trust the underlying read to fail if the stream is short.
		if rem := buff.Remaining(); rem >= 0 && eee > rem {
			return fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", eee, rem)
		}
		ddd := make([][]map[string]*int, eee)
		for iii := range eee {
			var fff []map[string]*int
			if buff.ReadUInt8() == uint8(0) {
				fff = nil
			} else {
				// --- [begin][read][slice]([]map[string]*int) ---
				hhh := buff.ReadInt() // slice len
				if hhh < 0 {
					return fmt.Errorf("bingen: invalid slice length %d", hhh)
				}
				// In byte-buffer mode Remaining() upper-bounds the length to reject
				// length-prefix DoS; in reader-mode Remaining() returns -1 ("unknown") and
				// we trust the underlying read to fail if the stream is short.
				if rem := buff.Remaining(); rem >= 0 && hhh > rem {
					return fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", hhh, rem)
				}
				ggg := make([]map[string]*int, hhh)
				for jjj := range hhh {
					var lll map[string]*int
					if buff.ReadUInt8() == uint8(0) {
						lll = nil
					} else {
						// --- [begin][read][map](map[string]*int) ---
						nnn := buff.ReadInt() // map len
						if nnn < 0 {
							return fmt.Errorf("bingen: invalid map length %d", nnn)
						}
						// Remaining() returns -1 in reader-mode; only apply the upper bound when
						// the buffer is byte-backed and the value is meaningful.
						if rem := buff.Remaining(); rem >= 0 && nnn > rem {
							return fmt.Errorf("bingen: map length %d exceeds remaining bytes %d", nnn, rem)
						}
						mmm := make(map[string]*int, nnn)
						for range nnn {
							var vv string
							var ppp string
							if ctx.IsStringTable() {
								qqq := buff.ReadInt() // read string index
								ppp = ctx.Table.At(qqq)
							} else {
								ppp = buff.ReadString() // read string
							}
							ooo := ppp
							vv = ooo

							var zz *int
							if buff.ReadUInt8() == uint8(0) {
								zz = nil
							} else {

								rrr := buff.ReadInt() // read int
								zz = &rrr

							}
							mmm[vv] = zz
						}
						lll = mmm
						// --- [end][read][map](map[string]*int) ---

					}

					ggg[jjj] = lll
				}
				fff = ggg
				// --- [end][read][slice]([]map[string]*int) ---

			}

			ddd[iii] = fff
		}
		ccc = ddd
		// --- [end][read][slice]([][]map[string]*int) ---

	}

	target.Slices = shared.DoubleSlice(ccc)
	// --- [end][read][alias](shared.DoubleSlice) ---

	return nil
}

//--------------------------------------------------------------------------
//  ParentStream
//--------------------------------------------------------------------------

// ParentStream is a single use field stream for the contents of an Parent instance. Instead of creating an instance and populating
// the fields on that instance, we provide a streaming iterator which yields (BingenFieldInfo, *BingenValue) tuples for each
// streamable element. All slices and maps will be flattened one depth and each element streamed individually.
type ParentStream struct {
	reader io.Reader
	ctx    *DecodingContext
	err    error
}

// Closes closes the internal io.Reader used to read and parse the Parent fields.
// This should be called once the stream is no longer needed.
func (stream *ParentStream) Close() {
	if closer, ok := stream.reader.(io.Closer); ok {
		closer.Close()
	}
	stream.ctx.Close()
}

// Error returns an error if one occurred during the process of streaming the Parent
// This can be checked after iterating through the Stream().
func (stream *ParentStream) Error() error {
	return stream.err
}

// NewParentStream creates a new ParentStream, which uses the io.Reader data to stream all internal fields of an Parent instance.
// Returns an error if the decoding context cannot be initialized (for example,
// an oversized or malformed string table header).
func NewParentStream(reader io.Reader) (BingenStream, error) {
	ctx, err := NewDecodingContextFromReader(reader)
	if err != nil {
		return nil, err
	}

	return &ParentStream{
		ctx:    ctx,
		reader: reader,
	}, nil
}

// Stream returns the iterator which will stream each field of the target type.
func (stream *ParentStream) Stream() iter.Seq2[BingenFieldInfo, *BingenValue] {
	return func(yield func(BingenFieldInfo, *BingenValue) bool) {
		var fi BingenFieldInfo

		ctx := stream.ctx
		buff := ctx.Buffer
		version := buff.ReadUInt8()

		if version > DefaultCodecVersion {
			stream.err = fmt.Errorf("Invalid Version Unmarshalling Parent. Expected %d or less, got %d", DefaultCodecVersion, version)
			return
		}

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[*shared.Name](),
			Name: "Name",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			// --- [begin][read][streaming-alias](shared.Name) ---

			var a string
			var c string
			if ctx.IsStringTable() {
				d := buff.ReadInt() // read string index
				c = ctx.Table.At(d)
			} else {
				c = buff.ReadString() // read string
			}
			b := c
			a = b

			e := shared.Name(a)
			if !yield(fi, singleV(&e)) {
				return
			}
			// --- [end][read][streaming-alias](shared.Name) ---
		}

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[*shared.Age](),
			Name: "Age",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			// --- [begin][read][streaming-alias](shared.Age) ---

			var f *int
			if buff.ReadUInt8() == uint8(0) {
				f = nil
			} else {

				g := buff.ReadInt() // read int
				f = &g

			}
			h := shared.Age(f)
			if !yield(fi, singleV(&h)) {
				return
			}
			// --- [end][read][streaming-alias](shared.Age) ---
		}

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[Child](),
			Name: "FirstChild",
		}
		// --- [begin][read][streaming-alias](Child) ---

		var l string
		var n string
		if ctx.IsStringTable() {
			o := buff.ReadInt() // read string index
			n = ctx.Table.At(o)
		} else {
			n = buff.ReadString() // read string
		}
		m := n
		l = m

		if !yield(fi, singleV(Child(l))) {
			return
		}
		// --- [end][read][streaming-alias](Child) ---

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[ChildInfo](),
			Name: "FirstChildInfo",
		}
		// --- [begin][read][streaming-alias](ChildInfo) ---

		var p *Info
		if buff.ReadUInt8() == uint8(0) {
			p = nil
		} else {
			// --- [begin][read][struct](Info) ---
			q := new(Info)
			buff.ReadInt() // [compatibility, unused]
			errA := q.UnmarshalBinaryWithContext(ctx)
			if errA != nil {
				stream.err = errA
				return

			}
			p = q
			// --- [end][read][struct](Info) ---

		}

		if !yield(fi, singleV(ChildInfo(p))) {
			return
		}
		// --- [end][read][streaming-alias](ChildInfo) ---

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[[]Child](),
			Name: "Children",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			// --- [begin][read][streaming-slice]([]Child) ---
			r := buff.ReadInt() // slice len
			if r < 0 {
				stream.err = fmt.Errorf("bingen: invalid slice length %d", r)
				return

			}
			// Streaming reads almost always come from an io.Reader, where Remaining()
			// returns -1; the upper-bound check only fires for the byte-buffer case.
			if rem := buff.Remaining(); rem >= 0 && r > rem {
				stream.err = fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", r, rem)
				return

			}
			for i := range r {

				// --- [begin][read][alias](Child) ---
				var t string
				var w string
				if ctx.IsStringTable() {
					x := buff.ReadInt() // read string index
					w = ctx.Table.At(x)
				} else {
					w = buff.ReadString() // read string
				}
				u := w
				t = u

				s := Child(t)
				// --- [end][read][alias](Child) ---

				if !yield(fi, pairV(i, s)) {
					return
				}
			}
			// --- [end][read][streaming-slice]([]Child) ---

		}

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[OtherChildInfo](),
			Name: "ChildrenInfo",
		}
		// --- [begin][read][streaming-alias](OtherChildInfo) ---
		// --- [begin][read][streaming-slice]([]ChildInfo) ---
		y := buff.ReadInt() // slice len
		if y < 0 {
			stream.err = fmt.Errorf("bingen: invalid slice length %d", y)
			return

		}
		// Streaming reads almost always come from an io.Reader, where Remaining()
		// returns -1; the upper-bound check only fires for the byte-buffer case.
		if rem := buff.Remaining(); rem >= 0 && y > rem {
			stream.err = fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", y, rem)
			return

		}
		for j := range y {

			// --- [begin][read][alias](ChildInfo) ---
			var bb *Info
			if buff.ReadUInt8() == uint8(0) {
				bb = nil
			} else {
				// --- [begin][read][struct](Info) ---
				cc := new(Info)
				buff.ReadInt() // [compatibility, unused]
				errB := cc.UnmarshalBinaryWithContext(ctx)
				if errB != nil {
					stream.err = errB
					return

				}
				bb = cc
				// --- [end][read][struct](Info) ---

			}

			aa := ChildInfo(bb)
			// --- [end][read][alias](ChildInfo) ---

			if !yield(fi, pairV(j, aa)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([]ChildInfo) ---
		// --- [end][read][streaming-alias](OtherChildInfo) ---

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[shared.FloatList](),
			Name: "FavoriteNumbers",
		}
		// --- [begin][read][streaming-alias](shared.FloatList) ---
		// --- [begin][read][streaming-slice]([]float64) ---
		dd := buff.ReadInt() // slice len
		if dd < 0 {
			stream.err = fmt.Errorf("bingen: invalid slice length %d", dd)
			return

		}
		// Streaming reads almost always come from an io.Reader, where Remaining()
		// returns -1; the upper-bound check only fires for the byte-buffer case.
		if rem := buff.Remaining(); rem >= 0 && dd > rem {
			stream.err = fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", dd, rem)
			return

		}
		for ii := range dd {

			var ee float64
			ff := buff.ReadFloat64() // read float64
			ee = ff

			if !yield(fi, pairV(ii, ee)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([]float64) ---
		// --- [end][read][streaming-alias](shared.FloatList) ---

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[shared.StrMap](),
			Name: "NameMap",
		}
		// --- [begin][read][streaming-alias](shared.StrMap) ---
		// --- [begin][read][streaming-map](map[string]int) ---
		gg := buff.ReadInt() // map len
		if gg < 0 {
			stream.err = fmt.Errorf("bingen: invalid map length %d", gg)
			return

		}
		if rem := buff.Remaining(); rem >= 0 && gg > rem {
			stream.err = fmt.Errorf("bingen: map length %d exceeds remaining bytes %d", gg, rem)
			return

		}
		for range gg {
			var v string
			var ll string
			if ctx.IsStringTable() {
				mm := buff.ReadInt() // read string index
				ll = ctx.Table.At(mm)
			} else {
				ll = buff.ReadString() // read string
			}
			hh := ll
			v = hh

			var z int
			nn := buff.ReadInt() // read int
			z = nn

			if !yield(fi, pairV(v, z)) {
				return
			}
		}
		// --- [end][read][streaming-map](map[string]int) ---

		// --- [end][read][streaming-alias](shared.StrMap) ---

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[shared.UIntPtrList](),
			Name: "U32s",
		}
		// --- [begin][read][streaming-alias](shared.UIntPtrList) ---
		// --- [begin][read][streaming-slice]([]*uint32) ---
		oo := buff.ReadInt() // slice len
		if oo < 0 {
			stream.err = fmt.Errorf("bingen: invalid slice length %d", oo)
			return

		}
		// Streaming reads almost always come from an io.Reader, where Remaining()
		// returns -1; the upper-bound check only fires for the byte-buffer case.
		if rem := buff.Remaining(); rem >= 0 && oo > rem {
			stream.err = fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", oo, rem)
			return

		}
		for jj := range oo {

			var pp *uint32
			if buff.ReadUInt8() == uint8(0) {
				pp = nil
			} else {

				qq := buff.ReadUInt32() // read uint32
				pp = &qq

			}

			if !yield(fi, pairV(jj, pp)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([]*uint32) ---
		// --- [end][read][streaming-alias](shared.UIntPtrList) ---

		fi = BingenFieldInfo{
			Type: reflect.TypeFor[shared.DoubleSlice](),
			Name: "Slices",
		}
		// --- [begin][read][streaming-alias](shared.DoubleSlice) ---
		// --- [begin][read][streaming-slice]([][]map[string]*int) ---
		rr := buff.ReadInt() // slice len
		if rr < 0 {
			stream.err = fmt.Errorf("bingen: invalid slice length %d", rr)
			return

		}
		// Streaming reads almost always come from an io.Reader, where Remaining()
		// returns -1; the upper-bound check only fires for the byte-buffer case.
		if rem := buff.Remaining(); rem >= 0 && rr > rem {
			stream.err = fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", rr, rem)
			return

		}
		for iii := range rr {

			var ss []map[string]*int
			if buff.ReadUInt8() == uint8(0) {
				ss = nil
			} else {
				// --- [begin][read][slice]([]map[string]*int) ---
				uu := buff.ReadInt() // slice len
				if uu < 0 {
					stream.err = fmt.Errorf("bingen: invalid slice length %d", uu)
					return

				}
				// In byte-buffer mode Remaining() upper-bounds the length to reject
				// length-prefix DoS; in reader-mode Remaining() returns -1 ("unknown") and
				// we trust the underlying read to fail if the stream is short.
				if rem := buff.Remaining(); rem >= 0 && uu > rem {
					stream.err = fmt.Errorf("bingen: slice length %d exceeds remaining bytes %d", uu, rem)
					return

				}
				tt := make([]map[string]*int, uu)
				for jjj := range uu {
					var ww map[string]*int
					if buff.ReadUInt8() == uint8(0) {
						ww = nil
					} else {
						// --- [begin][read][map](map[string]*int) ---
						yy := buff.ReadInt() // map len
						if yy < 0 {
							stream.err = fmt.Errorf("bingen: invalid map length %d", yy)
							return

						}
						// Remaining() returns -1 in reader-mode; only apply the upper bound when
						// the buffer is byte-backed and the value is meaningful.
						if rem := buff.Remaining(); rem >= 0 && yy > rem {
							stream.err = fmt.Errorf("bingen: map length %d exceeds remaining bytes %d", yy, rem)
							return

						}
						xx := make(map[string]*int, yy)
						for range yy {
							var vv string
							var bbb string
							if ctx.IsStringTable() {
								ccc := buff.ReadInt() // read string index
								bbb = ctx.Table.At(ccc)
							} else {
								bbb = buff.ReadString() // read string
							}
							aaa := bbb
							vv = aaa

							var zz *int
							if buff.ReadUInt8() == uint8(0) {
								zz = nil
							} else {

								ddd := buff.ReadInt() // read int
								zz = &ddd

							}
							xx[vv] = zz
						}
						ww = xx
						// --- [end][read][map](map[string]*int) ---

					}

					tt[jjj] = ww
				}
				ss = tt
				// --- [end][read][slice]([]map[string]*int) ---

			}

			if !yield(fi, pairV(iii, ss)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([][]map[string]*int) ---
		// --- [end][read][streaming-alias](shared.DoubleSlice) ---

	}
}
