////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package aliases

import (
	"fmt"
	"io"
	"iter"
	"os"
	"reflect"
	"strings"
	"sync"

	"github.com/opencost/bingen/tests/shared"

	bstream "github.com/opencost/bingen/pkg/stream"
	stringtable "github.com/opencost/bingen/pkg/table"
	util "github.com/opencost/bingen/pkg/util"
)

const (
	// GeneratorPackageName is the package the generator is targetting
	GeneratorPackageName string = "aliases"

	// DefaultCodecVersion is used for any resources listed in the Default version set
	DefaultCodecVersion uint8 = 16
)

//--------------------------------------------------------------------------
//  Configuration
//--------------------------------------------------------------------------

var (
	bingenConfigLock sync.RWMutex
	bingenConfig     *BingenConfiguration = DefaultBingenConfiguration()
)

// BingenConfiguration is used to set any custom configuration in the way files are encoded
// or decoded.
type BingenConfiguration struct {
	// FileBackedStringTableEnabled enables the use of file-backed string tables for streaming
	// bingen decoding.
	FileBackedStringTableEnabled bool

	// FileBackedStringTableDir is the directory to write the string table files for reading.
	FileBackedStringTableDir string

	// FileBackedStringTableMemoMaxBytes limits in-memory memoization for file-backed table lookups.
	// 0 disables memoization.
	FileBackedStringTableMemoMaxBytes int64
}

// DefaultBingenConfiguration creates the default implementation of the bingen configuration
// and returns it.
func DefaultBingenConfiguration() *BingenConfiguration {
	return &BingenConfiguration{
		FileBackedStringTableEnabled:      false,
		FileBackedStringTableDir:          os.TempDir(),
		FileBackedStringTableMemoMaxBytes: 0,
	}
}

// ConfigureBingen accepts a new *BingenConfiguration instance which updates the internal decoder
// and encoder behavior.
func ConfigureBingen(config *BingenConfiguration) {
	bingenConfigLock.Lock()
	defer bingenConfigLock.Unlock()

	if config == nil {
		config = DefaultBingenConfiguration()
	}
	bingenConfig = config
}

// IsBingenFileBackedStringTableEnabled accessor for file backed string table configuration
func IsBingenFileBackedStringTableEnabled() bool {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableEnabled
}

// BingenFileBackedStringTableDir returns the directory configured for file backed string tables.
func BingenFileBackedStringTableDir() string {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableDir
}

// BingenFileBackedStringTableMemoMaxBytes returns the maximum bytes used for file-backed memo cache.
func BingenFileBackedStringTableMemoMaxBytes() int64 {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableMemoMaxBytes
}

//--------------------------------------------------------------------------
//  Type Map
//--------------------------------------------------------------------------

// Generated type map for resolving interface implementations to to concrete types
var typeMap map[string]reflect.Type = map[string]reflect.Type{
	"Info":   reflect.TypeFor[Info](),
	"Parent": reflect.TypeFor[Parent](),
}

//--------------------------------------------------------------------------
//  Type Helpers
//--------------------------------------------------------------------------

// isBinaryTag returns true when the first bytes in the provided binary matches the tag
func isBinaryTag(data []byte, tag string) bool {
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// isReaderBinaryTag is used to peek the header for an io.Reader Buffer
func isReaderBinaryTag(buff *util.Buffer, tag string) bool {
	data, err := buff.Peek(len(tag))
	if err != nil && err != io.EOF {
		panic(fmt.Sprintf("called Peek() on a non buffered reader: %s", err))
	}
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// typeToString determines the basic properties of the type, the qualifier, package path, and
// type name, and returns the qualified type
func typeToString(f interface{}) string {
	qual := ""
	t := reflect.TypeOf(f)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
		qual = "*"
	}

	return fmt.Sprintf("%s%s.%s", qual, t.PkgPath(), t.Name())
}

// resolveType uses the name of a type and returns the package, base type name, and whether
// or not it's a pointer.
func resolveType(t string) (pkg string, name string, isPtr bool) {
	isPtr = t[:1] == "*"
	if isPtr {
		t = t[1:]
	}

	slashIndex := strings.LastIndex(t, "/")
	if slashIndex >= 0 {
		t = t[slashIndex+1:]
	}
	parts := strings.Split(t, ".")
	if parts[0] == GeneratorPackageName {
		parts[0] = ""
	}

	pkg = parts[0]
	name = parts[1]
	return
}

//--------------------------------------------------------------------------
//  Stream Helpers
//--------------------------------------------------------------------------

// StreamFactoryFunc is an alias for a func that creates a BingenStream implementation.
type StreamFactoryFunc func(io.Reader) bstream.BingenStream

// Generated streamable factory map for finding the specific new stream methods
// by T type
var streamFactoryMap map[reflect.Type]StreamFactoryFunc = map[reflect.Type]StreamFactoryFunc{
	reflect.TypeFor[Parent](): NewParentStream,
}

// NewStreamFor accepts an io.Reader, and returns a new BingenStream for the generic T
// type provided _if_ it is a registered bingen type that is annotated as 'streamable'. See
// the streamFactoryMap for generated type listings.
func NewStreamFor[T any](reader io.Reader) (bstream.BingenStream, error) {
	typeKey := reflect.TypeFor[T]()

	factory, ok := streamFactoryMap[typeKey]
	if !ok {
		return nil, fmt.Errorf("the type: %s is not a registered bingen streamable type", typeKey.Name())
	}

	return factory(reader), nil
}

//--------------------------------------------------------------------------
//  Codec Context
//--------------------------------------------------------------------------

// EncodingContext is a context object passed to the encoders to ensure reuse of buffer
// and table data
type EncodingContext struct {
	Buffer *util.Buffer
	Table  stringtable.StringTableWriter
}

// NewEncodingContext creates a new EncodingContext instance that will create a new []byte buffer
// for writing, and return the context
func NewEncodingContext(tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: util.NewBuffer(),
		Table:  tableWriter,
	}
}

// NewEncodingContextFromWriter creates a new EncodingContext instance that will create a new Buffer
// from the provided io.Writer and StringTableWriter.
func NewEncodingContextFromWriter(writer io.Writer, tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: util.NewBufferFromWriter(writer),
		Table:  tableWriter,
	}
}

// NewEncodingContextFromBuffer creates a new EncodingContext instance that will leverage an existing
// Buffer and StringTableWriter.
func NewEncodingContextFromBuffer(buffer *util.Buffer, tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: buffer,
		Table:  tableWriter,
	}
}

// ToBytes returns the encoded string table bytes (if applicable) combined with the encoded buffer bytes. If
// a string table is being used, the string table bytes will be written first to ensure correct ordering for
// decoding.
func (ec *EncodingContext) ToBytes() []byte {
	encBytes := ec.Buffer.Bytes()
	if ec.Table != nil {
		buff := util.NewBuffer()
		ec.Table.WriteTo(buff)
		buff.WriteBytes(encBytes)
		return buff.Bytes()
	}

	return encBytes
}

// IsStringTable returns true if the table is available
func (ec *EncodingContext) IsStringTable() bool {
	return ec.Table != nil
}

// DecodingContext is a context object passed to the decoders to ensure parent objects
// reuse as much data as possible
type DecodingContext struct {
	Buffer *util.Buffer
	Table  stringtable.StringTableReader
}

// NewDecodingContextFromBytes creates a new DecodingContext instance using an byte slice
func NewDecodingContextFromBytes(data []byte) *DecodingContext {
	var table stringtable.StringTableReader

	buff := util.NewBufferFromBytes(data)

	// string table header validation
	if isBinaryTag(data, stringtable.BinaryTagStringTable) {
		buff.ReadBytes(len(stringtable.BinaryTagStringTable)) // strip tag length

		// always use a slice string table with a byte array since the
		// data is already in memory
		table = stringtable.NewSliceStringTableReaderFrom(buff)
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}
}

// NewDecodingContextFromReader creates a new DecodingContext instance using an io.Reader
// implementation
func NewDecodingContextFromReader(reader io.Reader) *DecodingContext {
	var table stringtable.StringTableReader

	buff := util.NewBufferFromReader(reader)

	if isReaderBinaryTag(buff, stringtable.BinaryTagStringTable) {
		buff.ReadBytes(len(stringtable.BinaryTagStringTable)) // strip tag length

		// create correct string table implementation
		if IsBingenFileBackedStringTableEnabled() {
			table = stringtable.NewFileStringTableReaderFrom(buff, BingenFileBackedStringTableDir(), GeneratorPackageName, BingenFileBackedStringTableMemoMaxBytes())
		} else {
			table = stringtable.NewSliceStringTableReaderFrom(buff)
		}
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}
}

// IsStringTable returns true if the table is available
func (dc *DecodingContext) IsStringTable() bool {
	return dc.Table != nil && dc.Table.Len() > 0
}

// Close will ensure that any string table resources and buffer resources are
// cleaned up.
func (dc *DecodingContext) Close() {
	if dc.Table != nil {
		_ = dc.Table.Close()
		dc.Table = nil
	}
}

//--------------------------------------------------------------------------
//  Binary Codec
//--------------------------------------------------------------------------

// BinEncoder is an encoding interface which defines a context based marshal contract.
type BinEncoder interface {
	MarshalBinaryWithContext(*EncodingContext) error
}

// BinDecoder is a decoding interface which defines a context based unmarshal contract.
type BinDecoder interface {
	UnmarshalBinaryWithContext(*DecodingContext) error
}

//--------------------------------------------------------------------------
//  Info
//--------------------------------------------------------------------------

// MarshalBinary serializes the internal properties of this Info instance
// into a byte array
func (target *Info) MarshalBinary() (data []byte, err error) {
	ctx := NewEncodingContext(nil)

	e := target.MarshalBinaryWithContext(ctx)
	if e != nil {
		return nil, e
	}

	return ctx.ToBytes(), nil
}

// MarshalBinary serializes the internal properties of this Info instance
// into an io.Writer.
func (target *Info) MarshalBinaryTo(writer io.Writer) error {
	buff := util.NewBufferFromWriter(writer)
	defer buff.Flush()

	ctx := NewEncodingContextFromBuffer(buff, nil)

	return target.MarshalBinaryWithContext(ctx)
}

// MarshalBinaryWithContext serializes the internal properties of this Info instance
// into a byte array leveraging a predefined context.
func (target *Info) MarshalBinaryWithContext(ctx *EncodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	buff.WriteUInt8(DefaultCodecVersion) // version

	if ctx.IsStringTable() {
		a := ctx.Table.AddOrGet(target.Name)
		buff.WriteInt(a) // write table index
	} else {
		buff.WriteString(target.Name) // write string
	}

	buff.WriteUInt(target.Age) // write uint

	return nil
}

// UnmarshalBinary uses the data passed byte array to set all the internal properties of
// the Info type
func (target *Info) UnmarshalBinary(data []byte) error {
	ctx := NewDecodingContextFromBytes(data)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryFromReader uses the io.Reader data to set all the internal properties of
// the Info type
func (target *Info) UnmarshalBinaryFromReader(reader io.Reader) error {
	ctx := NewDecodingContextFromReader(reader)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryWithContext uses the context containing a string table and binary buffer to set all the internal properties of
// the Info type
func (target *Info) UnmarshalBinaryWithContext(ctx *DecodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	version := buff.ReadUInt8()

	if version > DefaultCodecVersion {
		return fmt.Errorf("Invalid Version Unmarshalling Info. Expected %d or less, got %d", DefaultCodecVersion, version)
	}

	var b string
	if ctx.IsStringTable() {
		c := buff.ReadInt() // read string index
		b = ctx.Table.At(c)
	} else {
		b = buff.ReadString() // read string
	}
	a := b
	target.Name = a

	d := buff.ReadUInt() // read uint
	target.Age = d

	return nil
}

//--------------------------------------------------------------------------
//  Parent
//--------------------------------------------------------------------------

// MarshalBinary serializes the internal properties of this Parent instance
// into a byte array
func (target *Parent) MarshalBinary() (data []byte, err error) {
	ctx := NewEncodingContext(stringtable.NewIndexedStringTableWriter())

	e := target.MarshalBinaryWithContext(ctx)
	if e != nil {
		return nil, e
	}

	return ctx.ToBytes(), nil
}

// MarshalBinary serializes the internal properties of this Parent instance
// into an io.Writer.
func (target *Parent) MarshalBinaryTo(writer io.Writer) error {
	buff := util.NewBufferFromWriter(writer)
	defer buff.Flush()

	// run a pre-pass to collect all strings into the string table and discard all writes to the main
	// buffer. Then, we write the string table, sorted by number of repeated uses (descending), to the
	// main buffer, and use the resulting table as part of the context for the main pass.
	prepass := stringtable.NewPrepassStringTableWriter()
	prepassCtx := NewEncodingContextFromWriter(io.Discard, prepass)

	e := target.MarshalBinaryWithContext(prepassCtx)
	if e != nil {
		return e
	}

	tableWriter := prepass.WriteSortedTo(buff)
	ctx := NewEncodingContextFromBuffer(buff, tableWriter)

	return target.MarshalBinaryWithContext(ctx)
}

// MarshalBinaryWithContext serializes the internal properties of this Parent instance
// into a byte array leveraging a predefined context.
func (target *Parent) MarshalBinaryWithContext(ctx *EncodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	buff.WriteUInt8(DefaultCodecVersion) // version

	if target.Name == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][alias](shared.Name) ---

		if ctx.IsStringTable() {
			a := ctx.Table.AddOrGet(string(*target.Name))
			buff.WriteInt(a) // write table index
		} else {
			buff.WriteString(string(*target.Name)) // write string
		}

		// --- [end][write][alias](shared.Name) ---
	}
	if target.Age == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][alias](shared.Age) ---
		if ((*int)(*target.Age)) == nil {
			buff.WriteUInt8(uint8(0)) // write nil byte
		} else {
			buff.WriteUInt8(uint8(1)) // write non-nil byte

			buff.WriteInt(*((*int)(*target.Age))) // write int

		}
		// --- [end][write][alias](shared.Age) ---
	}

	// --- [begin][write][alias](Child) ---

	if ctx.IsStringTable() {
		b := ctx.Table.AddOrGet(string(target.FirstChild))
		buff.WriteInt(b) // write table index
	} else {
		buff.WriteString(string(target.FirstChild)) // write string
	}

	// --- [end][write][alias](Child) ---

	// --- [begin][write][alias](ChildInfo) ---
	if ((*Info)(target.FirstChildInfo)) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][struct](Info) ---
		buff.WriteInt(0) // [compatibility, unused]
		errA := ((*Info)(target.FirstChildInfo)).MarshalBinaryWithContext(ctx)
		if errA != nil {
			return errA
		}
		// --- [end][write][struct](Info) ---

	}
	// --- [end][write][alias](ChildInfo) ---
	if target.Children == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([]Child) ---
		buff.WriteInt(len(target.Children)) // slice length
		for i := range target.Children {
			// --- [begin][write][alias](Child) ---

			if ctx.IsStringTable() {
				c := ctx.Table.AddOrGet(string(target.Children[i]))
				buff.WriteInt(c) // write table index
			} else {
				buff.WriteString(string(target.Children[i])) // write string
			}

			// --- [end][write][alias](Child) ---
		}
		// --- [end][write][slice]([]Child) ---

	}

	// --- [begin][write][alias](OtherChildInfo) ---
	if []ChildInfo(target.ChildrenInfo) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([]ChildInfo) ---
		buff.WriteInt(len([]ChildInfo(target.ChildrenInfo))) // slice length
		for j := range []ChildInfo(target.ChildrenInfo) {
			// --- [begin][write][alias](ChildInfo) ---
			if ((*Info)([]ChildInfo(target.ChildrenInfo)[j])) == nil {
				buff.WriteUInt8(uint8(0)) // write nil byte
			} else {
				buff.WriteUInt8(uint8(1)) // write non-nil byte

				// --- [begin][write][struct](Info) ---
				buff.WriteInt(0) // [compatibility, unused]
				errB := ((*Info)([]ChildInfo(target.ChildrenInfo)[j])).MarshalBinaryWithContext(ctx)
				if errB != nil {
					return errB
				}
				// --- [end][write][struct](Info) ---

			}
			// --- [end][write][alias](ChildInfo) ---
		}
		// --- [end][write][slice]([]ChildInfo) ---

	}
	// --- [end][write][alias](OtherChildInfo) ---

	// --- [begin][write][alias](shared.FloatList) ---
	if []float64(target.FavoriteNumbers) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([]float64) ---
		buff.WriteInt(len([]float64(target.FavoriteNumbers))) // slice length
		for ii := range []float64(target.FavoriteNumbers) {
			buff.WriteFloat64([]float64(target.FavoriteNumbers)[ii]) // write float64

		}
		// --- [end][write][slice]([]float64) ---

	}
	// --- [end][write][alias](shared.FloatList) ---

	// --- [begin][write][alias](shared.StrMap) ---
	if map[string]int(target.NameMap) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][map](map[string]int) ---
		buff.WriteInt(len(map[string]int(target.NameMap))) // map length
		for v, z := range map[string]int(target.NameMap) {
			if ctx.IsStringTable() {
				d := ctx.Table.AddOrGet(v)
				buff.WriteInt(d) // write table index
			} else {
				buff.WriteString(v) // write string
			}

			buff.WriteInt(z) // write int

		}
		// --- [end][write][map](map[string]int) ---

	}
	// --- [end][write][alias](shared.StrMap) ---

	// --- [begin][write][alias](shared.UIntPtrList) ---
	if []*uint32(target.U32s) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([]*uint32) ---
		buff.WriteInt(len([]*uint32(target.U32s))) // slice length
		for jj := range []*uint32(target.U32s) {
			if []*uint32(target.U32s)[jj] == nil {
				buff.WriteUInt8(uint8(0)) // write nil byte
			} else {
				buff.WriteUInt8(uint8(1)) // write non-nil byte

				buff.WriteUInt32(*[]*uint32(target.U32s)[jj]) // write uint32

			}
		}
		// --- [end][write][slice]([]*uint32) ---

	}
	// --- [end][write][alias](shared.UIntPtrList) ---

	// --- [begin][write][alias](shared.DoubleSlice) ---
	if [][]map[string]*int(target.Slices) == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([][]map[string]*int) ---
		buff.WriteInt(len([][]map[string]*int(target.Slices))) // slice length
		for iii := range [][]map[string]*int(target.Slices) {
			if [][]map[string]*int(target.Slices)[iii] == nil {
				buff.WriteUInt8(uint8(0)) // write nil byte
			} else {
				buff.WriteUInt8(uint8(1)) // write non-nil byte

				// --- [begin][write][slice]([]map[string]*int) ---
				buff.WriteInt(len([][]map[string]*int(target.Slices)[iii])) // slice length
				for jjj := range [][]map[string]*int(target.Slices)[iii] {
					if [][]map[string]*int(target.Slices)[iii][jjj] == nil {
						buff.WriteUInt8(uint8(0)) // write nil byte
					} else {
						buff.WriteUInt8(uint8(1)) // write non-nil byte

						// --- [begin][write][map](map[string]*int) ---
						buff.WriteInt(len([][]map[string]*int(target.Slices)[iii][jjj])) // map length
						for vv, zz := range [][]map[string]*int(target.Slices)[iii][jjj] {
							if ctx.IsStringTable() {
								e := ctx.Table.AddOrGet(vv)
								buff.WriteInt(e) // write table index
							} else {
								buff.WriteString(vv) // write string
							}
							if zz == nil {
								buff.WriteUInt8(uint8(0)) // write nil byte
							} else {
								buff.WriteUInt8(uint8(1)) // write non-nil byte

								buff.WriteInt(*zz) // write int

							}
						}
						// --- [end][write][map](map[string]*int) ---

					}
				}
				// --- [end][write][slice]([]map[string]*int) ---

			}
		}
		// --- [end][write][slice]([][]map[string]*int) ---

	}
	// --- [end][write][alias](shared.DoubleSlice) ---

	return nil
}

// UnmarshalBinary uses the data passed byte array to set all the internal properties of
// the Parent type
func (target *Parent) UnmarshalBinary(data []byte) error {
	ctx := NewDecodingContextFromBytes(data)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryFromReader uses the io.Reader data to set all the internal properties of
// the Parent type
func (target *Parent) UnmarshalBinaryFromReader(reader io.Reader) error {
	ctx := NewDecodingContextFromReader(reader)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryWithContext uses the context containing a string table and binary buffer to set all the internal properties of
// the Parent type
func (target *Parent) UnmarshalBinaryWithContext(ctx *DecodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	version := buff.ReadUInt8()

	if version > DefaultCodecVersion {
		return fmt.Errorf("Invalid Version Unmarshalling Parent. Expected %d or less, got %d", DefaultCodecVersion, version)
	}

	if buff.ReadUInt8() == uint8(0) {
		target.Name = nil
	} else {
		// --- [begin][read][alias](shared.Name) ---
		var a string
		var c string
		if ctx.IsStringTable() {
			d := buff.ReadInt() // read string index
			c = ctx.Table.At(d)
		} else {
			c = buff.ReadString() // read string
		}
		b := c
		a = b

		e := shared.Name(a)
		target.Name = &e
		// --- [end][read][alias](shared.Name) ---
	}

	if buff.ReadUInt8() == uint8(0) {
		target.Age = nil
	} else {
		// --- [begin][read][alias](shared.Age) ---
		var f *int
		if buff.ReadUInt8() == uint8(0) {
			f = nil
		} else {

			g := buff.ReadInt() // read int
			f = &g

		}
		h := shared.Age(f)
		target.Age = &h
		// --- [end][read][alias](shared.Age) ---
	}

	// --- [begin][read][alias](Child) ---
	var l string
	var n string
	if ctx.IsStringTable() {
		o := buff.ReadInt() // read string index
		n = ctx.Table.At(o)
	} else {
		n = buff.ReadString() // read string
	}
	m := n
	l = m

	target.FirstChild = Child(l)
	// --- [end][read][alias](Child) ---

	// --- [begin][read][alias](ChildInfo) ---
	var p *Info
	if buff.ReadUInt8() == uint8(0) {
		p = nil
	} else {
		// --- [begin][read][struct](Info) ---
		q := new(Info)
		buff.ReadInt() // [compatibility, unused]
		errA := q.UnmarshalBinaryWithContext(ctx)
		if errA != nil {
			return errA
		}
		p = q
		// --- [end][read][struct](Info) ---

	}

	target.FirstChildInfo = ChildInfo(p)
	// --- [end][read][alias](ChildInfo) ---

	if buff.ReadUInt8() == uint8(0) {
		target.Children = nil
	} else {
		// --- [begin][read][slice]([]Child) ---
		s := buff.ReadInt() // slice len
		r := make([]Child, s)
		for i := range s {
			// --- [begin][read][alias](Child) ---
			var u string
			var x string
			if ctx.IsStringTable() {
				y := buff.ReadInt() // read string index
				x = ctx.Table.At(y)
			} else {
				x = buff.ReadString() // read string
			}
			w := x
			u = w

			t := Child(u)
			// --- [end][read][alias](Child) ---

			r[i] = t
		}
		target.Children = r
		// --- [end][read][slice]([]Child) ---

	}

	// --- [begin][read][alias](OtherChildInfo) ---
	var aa []ChildInfo
	if buff.ReadUInt8() == uint8(0) {
		aa = nil
	} else {
		// --- [begin][read][slice]([]ChildInfo) ---
		cc := buff.ReadInt() // slice len
		bb := make([]ChildInfo, cc)
		for j := range cc {
			// --- [begin][read][alias](ChildInfo) ---
			var ee *Info
			if buff.ReadUInt8() == uint8(0) {
				ee = nil
			} else {
				// --- [begin][read][struct](Info) ---
				ff := new(Info)
				buff.ReadInt() // [compatibility, unused]
				errB := ff.UnmarshalBinaryWithContext(ctx)
				if errB != nil {
					return errB
				}
				ee = ff
				// --- [end][read][struct](Info) ---

			}

			dd := ChildInfo(ee)
			// --- [end][read][alias](ChildInfo) ---

			bb[j] = dd
		}
		aa = bb
		// --- [end][read][slice]([]ChildInfo) ---

	}

	target.ChildrenInfo = OtherChildInfo(aa)
	// --- [end][read][alias](OtherChildInfo) ---

	// --- [begin][read][alias](shared.FloatList) ---
	var gg []float64
	if buff.ReadUInt8() == uint8(0) {
		gg = nil
	} else {
		// --- [begin][read][slice]([]float64) ---
		ll := buff.ReadInt() // slice len
		hh := make([]float64, ll)
		for ii := range ll {
			var mm float64
			nn := buff.ReadFloat64() // read float64
			mm = nn

			hh[ii] = mm
		}
		gg = hh
		// --- [end][read][slice]([]float64) ---

	}

	target.FavoriteNumbers = shared.FloatList(gg)
	// --- [end][read][alias](shared.FloatList) ---

	// --- [begin][read][alias](shared.StrMap) ---
	var oo map[string]int
	if buff.ReadUInt8() == uint8(0) {
		oo = nil
	} else {
		// --- [begin][read][map](map[string]int) ---
		qq := buff.ReadInt() // map len
		pp := make(map[string]int, qq)
		for range qq {
			var v string
			var ss string
			if ctx.IsStringTable() {
				tt := buff.ReadInt() // read string index
				ss = ctx.Table.At(tt)
			} else {
				ss = buff.ReadString() // read string
			}
			rr := ss
			v = rr

			var z int
			uu := buff.ReadInt() // read int
			z = uu

			pp[v] = z
		}
		oo = pp
		// --- [end][read][map](map[string]int) ---

	}

	target.NameMap = shared.StrMap(oo)
	// --- [end][read][alias](shared.StrMap) ---

	// --- [begin][read][alias](shared.UIntPtrList) ---
	var ww []*uint32
	if buff.ReadUInt8() == uint8(0) {
		ww = nil
	} else {
		// --- [begin][read][slice]([]*uint32) ---
		yy := buff.ReadInt() // slice len
		xx := make([]*uint32, yy)
		for jj := range yy {
			var aaa *uint32
			if buff.ReadUInt8() == uint8(0) {
				aaa = nil
			} else {

				bbb := buff.ReadUInt32() // read uint32
				aaa = &bbb

			}

			xx[jj] = aaa
		}
		ww = xx
		// --- [end][read][slice]([]*uint32) ---

	}

	target.U32s = shared.UIntPtrList(ww)
	// --- [end][read][alias](shared.UIntPtrList) ---

	// --- [begin][read][alias](shared.DoubleSlice) ---
	var ccc [][]map[string]*int
	if buff.ReadUInt8() == uint8(0) {
		ccc = nil
	} else {
		// --- [begin][read][slice]([][]map[string]*int) ---
		eee := buff.ReadInt() // slice len
		ddd := make([][]map[string]*int, eee)
		for iii := range eee {
			var fff []map[string]*int
			if buff.ReadUInt8() == uint8(0) {
				fff = nil
			} else {
				// --- [begin][read][slice]([]map[string]*int) ---
				hhh := buff.ReadInt() // slice len
				ggg := make([]map[string]*int, hhh)
				for jjj := range hhh {
					var lll map[string]*int
					if buff.ReadUInt8() == uint8(0) {
						lll = nil
					} else {
						// --- [begin][read][map](map[string]*int) ---
						nnn := buff.ReadInt() // map len
						mmm := make(map[string]*int, nnn)
						for range nnn {
							var vv string
							var ppp string
							if ctx.IsStringTable() {
								qqq := buff.ReadInt() // read string index
								ppp = ctx.Table.At(qqq)
							} else {
								ppp = buff.ReadString() // read string
							}
							ooo := ppp
							vv = ooo

							var zz *int
							if buff.ReadUInt8() == uint8(0) {
								zz = nil
							} else {

								rrr := buff.ReadInt() // read int
								zz = &rrr

							}
							mmm[vv] = zz
						}
						lll = mmm
						// --- [end][read][map](map[string]*int) ---

					}

					ggg[jjj] = lll
				}
				fff = ggg
				// --- [end][read][slice]([]map[string]*int) ---

			}

			ddd[iii] = fff
		}
		ccc = ddd
		// --- [end][read][slice]([][]map[string]*int) ---

	}

	target.Slices = shared.DoubleSlice(ccc)
	// --- [end][read][alias](shared.DoubleSlice) ---

	return nil
}

//--------------------------------------------------------------------------
//  ParentStream
//--------------------------------------------------------------------------

// ParentStream is a single use field stream for the contents of an Parent instance. Instead of creating an instance and populating
// the fields on that instance, we provide a streaming iterator which yields (BingenFieldInfo, *BingenValue) tuples for each
// streamable element. All slices and maps will be flattened one depth and each element streamed individually.
type ParentStream struct {
	reader io.Reader
	ctx    *DecodingContext
	err    error
}

// Closes closes the internal io.Reader used to read and parse the Parent fields.
// This should be called once the stream is no longer needed.
func (stream *ParentStream) Close() {
	if closer, ok := stream.reader.(io.Closer); ok {
		closer.Close()
	}
	stream.ctx.Close()
}

// Error returns an error if one occurred during the process of streaming the Parent
// This can be checked after iterating through the Stream().
func (stream *ParentStream) Error() error {
	return stream.err
}

// NewParentStream creates a new ParentStream, which uses the io.Reader data to stream all internal fields of an Parent instance
func NewParentStream(reader io.Reader) bstream.BingenStream {
	ctx := NewDecodingContextFromReader(reader)

	return &ParentStream{
		ctx:    ctx,
		reader: reader,
	}
}

// Stream returns the iterator which will stream each field of the target type.
func (stream *ParentStream) Stream() iter.Seq2[bstream.BingenFieldInfo, *bstream.BingenValue] {
	return func(yield func(bstream.BingenFieldInfo, *bstream.BingenValue) bool) {
		var fi bstream.BingenFieldInfo

		ctx := stream.ctx
		buff := ctx.Buffer
		version := buff.ReadUInt8()

		if version > DefaultCodecVersion {
			stream.err = fmt.Errorf("Invalid Version Unmarshalling Parent. Expected %d or less, got %d", DefaultCodecVersion, version)
			return
		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[*shared.Name](),
			Name: "Name",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			// --- [begin][read][streaming-alias](shared.Name) ---

			var a string
			var c string
			if ctx.IsStringTable() {
				d := buff.ReadInt() // read string index
				c = ctx.Table.At(d)
			} else {
				c = buff.ReadString() // read string
			}
			b := c
			a = b

			e := shared.Name(a)
			if !yield(fi, bstream.SingleV(&e)) {
				return
			}
			// --- [end][read][streaming-alias](shared.Name) ---
		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[*shared.Age](),
			Name: "Age",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			// --- [begin][read][streaming-alias](shared.Age) ---

			var f *int
			if buff.ReadUInt8() == uint8(0) {
				f = nil
			} else {

				g := buff.ReadInt() // read int
				f = &g

			}
			h := shared.Age(f)
			if !yield(fi, bstream.SingleV(&h)) {
				return
			}
			// --- [end][read][streaming-alias](shared.Age) ---
		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[Child](),
			Name: "FirstChild",
		}
		// --- [begin][read][streaming-alias](Child) ---

		var l string
		var n string
		if ctx.IsStringTable() {
			o := buff.ReadInt() // read string index
			n = ctx.Table.At(o)
		} else {
			n = buff.ReadString() // read string
		}
		m := n
		l = m

		if !yield(fi, bstream.SingleV(Child(l))) {
			return
		}
		// --- [end][read][streaming-alias](Child) ---

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[ChildInfo](),
			Name: "FirstChildInfo",
		}
		// --- [begin][read][streaming-alias](ChildInfo) ---

		var p *Info
		if buff.ReadUInt8() == uint8(0) {
			p = nil
		} else {
			// --- [begin][read][struct](Info) ---
			q := new(Info)
			buff.ReadInt() // [compatibility, unused]
			errA := q.UnmarshalBinaryWithContext(ctx)
			if errA != nil {
				stream.err = errA
				return

			}
			p = q
			// --- [end][read][struct](Info) ---

		}

		if !yield(fi, bstream.SingleV(ChildInfo(p))) {
			return
		}
		// --- [end][read][streaming-alias](ChildInfo) ---

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[[]Child](),
			Name: "Children",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			// --- [begin][read][streaming-slice]([]Child) ---
			r := buff.ReadInt() // slice len
			for i := range r {

				// --- [begin][read][alias](Child) ---
				var t string
				var w string
				if ctx.IsStringTable() {
					x := buff.ReadInt() // read string index
					w = ctx.Table.At(x)
				} else {
					w = buff.ReadString() // read string
				}
				u := w
				t = u

				s := Child(t)
				// --- [end][read][alias](Child) ---

				if !yield(fi, bstream.PairV(i, s)) {
					return
				}
			}
			// --- [end][read][streaming-slice]([]Child) ---

		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[OtherChildInfo](),
			Name: "ChildrenInfo",
		}
		// --- [begin][read][streaming-alias](OtherChildInfo) ---
		// --- [begin][read][streaming-slice]([]ChildInfo) ---
		y := buff.ReadInt() // slice len
		for j := range y {

			// --- [begin][read][alias](ChildInfo) ---
			var bb *Info
			if buff.ReadUInt8() == uint8(0) {
				bb = nil
			} else {
				// --- [begin][read][struct](Info) ---
				cc := new(Info)
				buff.ReadInt() // [compatibility, unused]
				errB := cc.UnmarshalBinaryWithContext(ctx)
				if errB != nil {
					stream.err = errB
					return

				}
				bb = cc
				// --- [end][read][struct](Info) ---

			}

			aa := ChildInfo(bb)
			// --- [end][read][alias](ChildInfo) ---

			if !yield(fi, bstream.PairV(j, aa)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([]ChildInfo) ---
		// --- [end][read][streaming-alias](OtherChildInfo) ---

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[shared.FloatList](),
			Name: "FavoriteNumbers",
		}
		// --- [begin][read][streaming-alias](shared.FloatList) ---
		// --- [begin][read][streaming-slice]([]float64) ---
		dd := buff.ReadInt() // slice len
		for ii := range dd {

			var ee float64
			ff := buff.ReadFloat64() // read float64
			ee = ff

			if !yield(fi, bstream.PairV(ii, ee)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([]float64) ---
		// --- [end][read][streaming-alias](shared.FloatList) ---

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[shared.StrMap](),
			Name: "NameMap",
		}
		// --- [begin][read][streaming-alias](shared.StrMap) ---
		// --- [begin][read][streaming-map](map[string]int) ---
		gg := buff.ReadInt() // map len
		for range gg {
			var v string
			var ll string
			if ctx.IsStringTable() {
				mm := buff.ReadInt() // read string index
				ll = ctx.Table.At(mm)
			} else {
				ll = buff.ReadString() // read string
			}
			hh := ll
			v = hh

			var z int
			nn := buff.ReadInt() // read int
			z = nn

			if !yield(fi, bstream.PairV(v, z)) {
				return
			}
		}
		// --- [end][read][streaming-map](map[string]int) ---

		// --- [end][read][streaming-alias](shared.StrMap) ---

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[shared.UIntPtrList](),
			Name: "U32s",
		}
		// --- [begin][read][streaming-alias](shared.UIntPtrList) ---
		// --- [begin][read][streaming-slice]([]*uint32) ---
		oo := buff.ReadInt() // slice len
		for jj := range oo {

			var pp *uint32
			if buff.ReadUInt8() == uint8(0) {
				pp = nil
			} else {

				qq := buff.ReadUInt32() // read uint32
				pp = &qq

			}

			if !yield(fi, bstream.PairV(jj, pp)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([]*uint32) ---
		// --- [end][read][streaming-alias](shared.UIntPtrList) ---

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[shared.DoubleSlice](),
			Name: "Slices",
		}
		// --- [begin][read][streaming-alias](shared.DoubleSlice) ---
		// --- [begin][read][streaming-slice]([][]map[string]*int) ---
		rr := buff.ReadInt() // slice len
		for iii := range rr {

			var ss []map[string]*int
			if buff.ReadUInt8() == uint8(0) {
				ss = nil
			} else {
				// --- [begin][read][slice]([]map[string]*int) ---
				uu := buff.ReadInt() // slice len
				tt := make([]map[string]*int, uu)
				for jjj := range uu {
					var ww map[string]*int
					if buff.ReadUInt8() == uint8(0) {
						ww = nil
					} else {
						// --- [begin][read][map](map[string]*int) ---
						yy := buff.ReadInt() // map len
						xx := make(map[string]*int, yy)
						for range yy {
							var vv string
							var bbb string
							if ctx.IsStringTable() {
								ccc := buff.ReadInt() // read string index
								bbb = ctx.Table.At(ccc)
							} else {
								bbb = buff.ReadString() // read string
							}
							aaa := bbb
							vv = aaa

							var zz *int
							if buff.ReadUInt8() == uint8(0) {
								zz = nil
							} else {

								ddd := buff.ReadInt() // read int
								zz = &ddd

							}
							xx[vv] = zz
						}
						ww = xx
						// --- [end][read][map](map[string]*int) ---

					}

					tt[jjj] = ww
				}
				ss = tt
				// --- [end][read][slice]([]map[string]*int) ---

			}

			if !yield(fi, bstream.PairV(iii, ss)) {
				return
			}
		}
		// --- [end][read][streaming-slice]([][]map[string]*int) ---
		// --- [end][read][streaming-alias](shared.DoubleSlice) ---

	}
}
