////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated binary decoder for {@link AllocationProperties}.
 */
public final class AllocationPropertiesDecoder implements BinDecoder<AllocationProperties> {

    public static final AllocationPropertiesDecoder INSTANCE = new AllocationPropertiesDecoder();

    private static final int VERSION = 16;

    /** Decodes a {@link AllocationProperties} from a standalone byte array. */
    public static AllocationProperties fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** Decodes a {@link AllocationProperties} read incrementally from a stream. */
    public static AllocationProperties fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public AllocationProperties decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding AllocationProperties: expected " + VERSION + " or less, got " + version);
        }

        AllocationProperties.Builder builder = AllocationProperties.builder();
        String v0;
        if (ctx.isStringTable()) {
            v0 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v0 = buff.readString(); // read string
        }
        builder.cluster(v0);
        String v1;
        if (ctx.isStringTable()) {
            v1 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v1 = buff.readString(); // read string
        }
        builder.node(v1);
        String v2;
        if (ctx.isStringTable()) {
            v2 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v2 = buff.readString(); // read string
        }
        builder.container(v2);
        String v3;
        if (ctx.isStringTable()) {
            v3 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v3 = buff.readString(); // read string
        }
        builder.controller(v3);
        String v4;
        if (ctx.isStringTable()) {
            v4 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v4 = buff.readString(); // read string
        }
        builder.controllerKind(v4);
        String v5;
        if (ctx.isStringTable()) {
            v5 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v5 = buff.readString(); // read string
        }
        builder.namespace(v5);
        String v6;
        if (ctx.isStringTable()) {
            v6 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v6 = buff.readString(); // read string
        }
        builder.pod(v6);
        List<String> v7;
        if (buff.readUInt8() == 0) {
            v7 = null;
        } else {
            int v8 = buff.readInt(); // slice length
            v7 = new ArrayList<>(v8);
            for (int v9 = 0; v9 < v8; v9++) {
                String v10;
                if (ctx.isStringTable()) {
                    v10 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v10 = buff.readString(); // read string
                }
                v7.add(v10);
            }
        }
        builder.services(v7);
        String v11;
        if (ctx.isStringTable()) {
            v11 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v11 = buff.readString(); // read string
        }
        builder.providerID(v11);
        Map<String, String> v12;
        if (buff.readUInt8() == 0) {
            v12 = null;
        } else {
            int v13 = buff.readInt(); // map length
            v12 = new LinkedHashMap<>(v13);
            for (int v14 = 0; v14 < v13; v14++) {
                String v15;
                if (ctx.isStringTable()) {
                    v15 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v15 = buff.readString(); // read string
                }
                String v16;
                if (ctx.isStringTable()) {
                    v16 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v16 = buff.readString(); // read string
                }
                v12.put(v15, v16);
            }
        }
        builder.labels(v12);
        Map<String, String> v17;
        if (buff.readUInt8() == 0) {
            v17 = null;
        } else {
            int v18 = buff.readInt(); // map length
            v17 = new LinkedHashMap<>(v18);
            for (int v19 = 0; v19 < v18; v19++) {
                String v20;
                if (ctx.isStringTable()) {
                    v20 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v20 = buff.readString(); // read string
                }
                String v21;
                if (ctx.isStringTable()) {
                    v21 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v21 = buff.readString(); // read string
                }
                v17.put(v20, v21);
            }
        }
        builder.annotations(v17);
        AllocationProperties result = builder.build();
        return result;
    }
}
