////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.util.List;
import java.util.Map;

/**
 * Generated data type for the {@code AllocationSet} go struct.
 */
public record AllocationSet(Map<String, Allocation> allocations, Map<String, Boolean> externalKeys, Map<String, Boolean> idleKeys, String fromSource, Window window, List<String> warnings, List<String> errors) {

    /** Creates a new builder for {@link AllocationSet}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Mutable builder the decoder uses to accumulate fields and apply defaults. */
    public static final class Builder {
        private Map<String, Allocation> allocations;
        private Map<String, Boolean> externalKeys;
        private Map<String, Boolean> idleKeys;
        private String fromSource;
        private Window window;
        private List<String> warnings;
        private List<String> errors;
        public Builder allocations(Map<String, Allocation> allocations) {
            this.allocations = allocations;
            return this;
        }
        public Builder externalKeys(Map<String, Boolean> externalKeys) {
            this.externalKeys = externalKeys;
            return this;
        }
        public Builder idleKeys(Map<String, Boolean> idleKeys) {
            this.idleKeys = idleKeys;
            return this;
        }
        public Builder fromSource(String fromSource) {
            this.fromSource = fromSource;
            return this;
        }
        public Builder window(Window window) {
            this.window = window;
            return this;
        }
        public Builder warnings(List<String> warnings) {
            this.warnings = warnings;
            return this;
        }
        public Builder errors(List<String> errors) {
            this.errors = errors;
            return this;
        }

        public AllocationSet build() {
            return new AllocationSet(allocations, externalKeys, idleKeys, fromSource, window, warnings, errors);
        }
    }
}
