////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;

/**
 * Generated binary encoder for {@link AllocationSetRange}.
 */
public final class AllocationSetRangeEncoder implements BinEncoder<AllocationSetRange> {

    public static final AllocationSetRangeEncoder INSTANCE = new AllocationSetRangeEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** 
     * Encodes {@code value} to a standalone byte array. 
     */
    public static byte[] toBytes(AllocationSetRange value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(AllocationSetRange value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (value.allocations() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.allocations().size()); // slice length
            for (AllocationSet v0 : value.allocations()) {
                if (v0 == null) {
                    buff.writeUInt8(0); // write nil byte
                } else {
                    buff.writeUInt8(1); // write non-nil byte
                    buff.writeInt(0); // [compatibility, unused]
                    AllocationSetEncoder.INSTANCE.encode(v0, ctx);
                }
            }
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.fromStore())); // string table index
        } else {
            buff.writeString(value.fromStore()); // string
        }
    }
}
