////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.util.List;
import java.util.Map;

/**
 * Generated data type for the {@code AllocationProperties} go struct.
 */
public record AllocationProperties(String cluster, String node, String container, String controller, String controllerKind, String namespace, String pod, List<String> services, String providerID, Map<String, String> labels, Map<String, String> annotations) {

    /** 
     * Creates a new builder for {@link AllocationProperties}. 
     */
    public static Builder builder() {
        return new Builder();
    }

    /** 
     * Mutable builder the decoder uses to accumulate fields and apply defaults. 
     */
    public static final class Builder {
        private String cluster;
        private String node;
        private String container;
        private String controller;
        private String controllerKind;
        private String namespace;
        private String pod;
        private List<String> services;
        private String providerID;
        private Map<String, String> labels;
        private Map<String, String> annotations;
        public Builder cluster(String cluster) {
            this.cluster = cluster;
            return this;
        }
        public Builder node(String node) {
            this.node = node;
            return this;
        }
        public Builder container(String container) {
            this.container = container;
            return this;
        }
        public Builder controller(String controller) {
            this.controller = controller;
            return this;
        }
        public Builder controllerKind(String controllerKind) {
            this.controllerKind = controllerKind;
            return this;
        }
        public Builder namespace(String namespace) {
            this.namespace = namespace;
            return this;
        }
        public Builder pod(String pod) {
            this.pod = pod;
            return this;
        }
        public Builder services(List<String> services) {
            this.services = services;
            return this;
        }
        public Builder providerID(String providerID) {
            this.providerID = providerID;
            return this;
        }
        public Builder labels(Map<String, String> labels) {
            this.labels = labels;
            return this;
        }
        public Builder annotations(Map<String, String> annotations) {
            this.annotations = annotations;
            return this;
        }

        public AllocationProperties build() {
            return new AllocationProperties(cluster, node, container, controller, controllerKind, namespace, pod, services, providerID, labels, annotations);
        }
    }
}
