////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.util.List;

/**
 * Generated data type for the {@code AllocationSetRange} go struct.
 */
public record AllocationSetRange(List<AllocationSet> allocations, String fromStore) {

    /** Creates a new builder for {@link AllocationSetRange}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Mutable builder the decoder uses to accumulate fields and apply defaults. */
    public static final class Builder {
        private List<AllocationSet> allocations;
        private String fromStore;
        public Builder allocations(List<AllocationSet> allocations) {
            this.allocations = allocations;
            return this;
        }
        public Builder fromStore(String fromStore) {
            this.fromStore = fromStore;
            return this;
        }

        public AllocationSetRange build() {
            return new AllocationSetRange(allocations, fromStore);
        }
    }
}
