////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;
import java.util.Map;

/**
 * Generated binary encoder for {@link AllocationSet}.
 */
public final class AllocationSetEncoder implements BinEncoder<AllocationSet> {

    public static final AllocationSetEncoder INSTANCE = new AllocationSetEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = true;

    /** Encodes {@code value} to a standalone byte array. */
    public static byte[] toBytes(AllocationSet value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(AllocationSet value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (value.allocations() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.allocations().size()); // map length
            for (Map.Entry<String, Allocation> v0 : value.allocations().entrySet()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v0.getKey())); // string table index
                } else {
                    buff.writeString(v0.getKey()); // string
                }
                if (v0.getValue() == null) {
                    buff.writeUInt8(0); // write nil byte
                } else {
                    buff.writeUInt8(1); // write non-nil byte
                    buff.writeInt(0); // [compatibility, unused]
                    AllocationEncoder.INSTANCE.encode(v0.getValue(), ctx);
                }
            }
        }
        if (value.externalKeys() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.externalKeys().size()); // map length
            for (Map.Entry<String, Boolean> v1 : value.externalKeys().entrySet()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v1.getKey())); // string table index
                } else {
                    buff.writeString(v1.getKey()); // string
                }
                buff.writeBool(v1.getValue());
            }
        }
        if (value.idleKeys() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.idleKeys().size()); // map length
            for (Map.Entry<String, Boolean> v2 : value.idleKeys().entrySet()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v2.getKey())); // string table index
                } else {
                    buff.writeString(v2.getKey()); // string
                }
                buff.writeBool(v2.getValue());
            }
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.fromSource())); // string table index
        } else {
            buff.writeString(value.fromSource()); // string
        }
        buff.writeInt(0); // [compatibility, unused]
        WindowEncoder.INSTANCE.encode(value.window(), ctx);
        if (value.warnings() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.warnings().size()); // slice length
            for (String v3 : value.warnings()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v3)); // string table index
                } else {
                    buff.writeString(v3); // string
                }
            }
        }
        if (value.errors() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.errors().size()); // slice length
            for (String v4 : value.errors()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v4)); // string table index
                } else {
                    buff.writeString(v4); // string
                }
            }
        }
    }
}
