////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated binary decoder for {@link AllocationSet}.
 */
public final class AllocationSetDecoder implements BinDecoder<AllocationSet> {

    public static final AllocationSetDecoder INSTANCE = new AllocationSetDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link AllocationSet} from a standalone byte array. 
     */
    public static AllocationSet fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link AllocationSet} read incrementally from a stream. 
     */
    public static AllocationSet fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public AllocationSet decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding AllocationSet: expected " + VERSION + " or less, got " + version);
        }

        AllocationSet.Builder builder = AllocationSet.builder();
        Map<String, Allocation> v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            int v1 = buff.readInt(); // map length
            v0 = new LinkedHashMap<>(v1);
            for (int v2 = 0; v2 < v1; v2++) {
                String v3;
                if (ctx.isStringTable()) {
                    v3 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v3 = buff.readString(); // read string
                }
                Allocation v4;
                if (buff.readUInt8() == 0) {
                    v4 = null;
                } else {
                    buff.readInt(); // [compatibility, unused]
                    v4 = AllocationDecoder.INSTANCE.decode(ctx);
                }
                v0.put(v3, v4);
            }
        }
        builder.allocations(v0);
        Map<String, Boolean> v5;
        if (buff.readUInt8() == 0) {
            v5 = null;
        } else {
            int v6 = buff.readInt(); // map length
            v5 = new LinkedHashMap<>(v6);
            for (int v7 = 0; v7 < v6; v7++) {
                String v8;
                if (ctx.isStringTable()) {
                    v8 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v8 = buff.readString(); // read string
                }
                boolean v9;
                v9 = buff.readBool();
                v5.put(v8, v9);
            }
        }
        builder.externalKeys(v5);
        Map<String, Boolean> v10;
        if (buff.readUInt8() == 0) {
            v10 = null;
        } else {
            int v11 = buff.readInt(); // map length
            v10 = new LinkedHashMap<>(v11);
            for (int v12 = 0; v12 < v11; v12++) {
                String v13;
                if (ctx.isStringTable()) {
                    v13 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v13 = buff.readString(); // read string
                }
                boolean v14;
                v14 = buff.readBool();
                v10.put(v13, v14);
            }
        }
        builder.idleKeys(v10);
        String v15;
        if (ctx.isStringTable()) {
            v15 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v15 = buff.readString(); // read string
        }
        builder.fromSource(v15);
        Window v16;
        buff.readInt(); // [compatibility, unused]
        v16 = WindowDecoder.INSTANCE.decode(ctx);
        builder.window(v16);
        List<String> v17;
        if (buff.readUInt8() == 0) {
            v17 = null;
        } else {
            int v18 = buff.readInt(); // slice length
            v17 = new ArrayList<>(v18);
            for (int v19 = 0; v19 < v18; v19++) {
                String v20;
                if (ctx.isStringTable()) {
                    v20 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v20 = buff.readString(); // read string
                }
                v17.add(v20);
            }
        }
        builder.warnings(v17);
        List<String> v21;
        if (buff.readUInt8() == 0) {
            v21 = null;
        } else {
            int v22 = buff.readInt(); // slice length
            v21 = new ArrayList<>(v22);
            for (int v23 = 0; v23 < v22; v23++) {
                String v24;
                if (ctx.isStringTable()) {
                    v24 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v24 = buff.readString(); // read string
                }
                v21.add(v24);
            }
        }
        builder.errors(v21);
        AllocationSet result = builder.build();
        return result;
    }
}
