////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;
import com.bingen.GoTime;
import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Generated binary encoder for {@link Allocation}.
 */
public final class AllocationEncoder implements BinEncoder<Allocation> {

    public static final AllocationEncoder INSTANCE = new AllocationEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** 
     * Encodes {@code value} to a standalone byte array. 
     */
    public static byte[] toBytes(Allocation value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(Allocation value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.name())); // string table index
        } else {
            buff.writeString(value.name()); // string
        }
        if (value.properties() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(0); // [compatibility, unused]
            AllocationPropertiesEncoder.INSTANCE.encode(value.properties(), ctx);
        }
        buff.writeInt(0); // [compatibility, unused]
        WindowEncoder.INSTANCE.encode(value.window(), ctx);
        GoTime.encode(value.start(), buff);
        GoTime.encode(value.end(), buff);
        buff.writeFloat64(value.cPUCoreHours());
        buff.writeFloat64(value.cPUCoreRequestAverage());
        buff.writeFloat64(value.cPUCoreUsageAverage());
        buff.writeFloat64(value.cPUCost());
        buff.writeFloat64(value.cPUCostAdjustment());
        buff.writeFloat64(value.gPUHours());
        buff.writeFloat64(value.gPUCost());
        buff.writeFloat64(value.gPUCostAdjustment());
        buff.writeFloat64(value.networkTransferBytes());
        buff.writeFloat64(value.networkReceiveBytes());
        buff.writeFloat64(value.networkCost());
        buff.writeFloat64(value.networkCostAdjustment());
        buff.writeFloat64(value.loadBalancerCost());
        buff.writeFloat64(value.loadBalancerCostAdjustment());
        if (value.pVs() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.pVs().size()); // map length
            for (Map.Entry<PVKey, PVAllocation> v0 : value.pVs().entrySet()) {
                buff.writeInt(0); // [compatibility, unused]
                PVKeyEncoder.INSTANCE.encode(v0.getKey(), ctx);
                if (v0.getValue() == null) {
                    buff.writeUInt8(0); // write nil byte
                } else {
                    buff.writeUInt8(1); // write non-nil byte
                    buff.writeInt(0); // [compatibility, unused]
                    PVAllocationEncoder.INSTANCE.encode(v0.getValue(), ctx);
                }
            }
        }
        buff.writeFloat64(value.pVCostAdjustment());
        buff.writeFloat64(value.rAMByteHours());
        buff.writeFloat64(value.rAMBytesRequestAverage());
        buff.writeFloat64(value.rAMBytesUsageAverage());
        buff.writeFloat64(value.rAMCost());
        buff.writeFloat64(value.rAMCostAdjustment());
        buff.writeFloat64(value.sharedCost());
        buff.writeFloat64(value.externalCost());
        if (value.rawAllocationOnly() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(0); // [compatibility, unused]
            RawAllocationOnlyDataEncoder.INSTANCE.encode(value.rawAllocationOnly(), ctx);
        }
        buff.writeInt(value.testProperty());
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.testStr())); // string table index
        } else {
            buff.writeString(value.testStr()); // string
        }
    }
}
