////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;
import java.util.Map;

/**
 * Generated binary encoder for {@link AllocationProperties}.
 */
public final class AllocationPropertiesEncoder implements BinEncoder<AllocationProperties> {

    public static final AllocationPropertiesEncoder INSTANCE = new AllocationPropertiesEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** Encodes {@code value} to a standalone byte array. */
    public static byte[] toBytes(AllocationProperties value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(AllocationProperties value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.cluster())); // string table index
        } else {
            buff.writeString(value.cluster()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.node())); // string table index
        } else {
            buff.writeString(value.node()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.container())); // string table index
        } else {
            buff.writeString(value.container()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.controller())); // string table index
        } else {
            buff.writeString(value.controller()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.controllerKind())); // string table index
        } else {
            buff.writeString(value.controllerKind()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.namespace())); // string table index
        } else {
            buff.writeString(value.namespace()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.pod())); // string table index
        } else {
            buff.writeString(value.pod()); // string
        }
        if (value.services() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.services().size()); // slice length
            for (String v0 : value.services()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v0)); // string table index
                } else {
                    buff.writeString(v0); // string
                }
            }
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.providerID())); // string table index
        } else {
            buff.writeString(value.providerID()); // string
        }
        if (value.labels() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.labels().size()); // map length
            for (Map.Entry<String, String> v1 : value.labels().entrySet()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v1.getKey())); // string table index
                } else {
                    buff.writeString(v1.getKey()); // string
                }
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v1.getValue())); // string table index
                } else {
                    buff.writeString(v1.getValue()); // string
                }
            }
        }
        if (value.annotations() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.annotations().size()); // map length
            for (Map.Entry<String, String> v2 : value.annotations().entrySet()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v2.getKey())); // string table index
                } else {
                    buff.writeString(v2.getKey()); // string
                }
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v2.getValue())); // string table index
                } else {
                    buff.writeString(v2.getValue()); // string
                }
            }
        }
    }
}
