////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Generated data type for the {@code Allocation} go struct.
 */
public record Allocation(String name, AllocationProperties properties, Window window, OffsetDateTime start, OffsetDateTime end, double cPUCoreHours, double cPUCoreRequestAverage, double cPUCoreUsageAverage, double cPUCost, double cPUCostAdjustment, double gPUHours, double gPUCost, double gPUCostAdjustment, double networkTransferBytes, double networkReceiveBytes, double networkCost, double networkCostAdjustment, double loadBalancerCost, double loadBalancerCostAdjustment, Map<PVKey, PVAllocation> pVs, double pVCostAdjustment, double rAMByteHours, double rAMBytesRequestAverage, double rAMBytesUsageAverage, double rAMCost, double rAMCostAdjustment, double sharedCost, double externalCost, RawAllocationOnlyData rawAllocationOnly, int testProperty, String testStr) {

    /** Creates a new builder for {@link Allocation}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Mutable builder the decoder uses to accumulate fields and apply defaults. */
    public static final class Builder {
        private String name;
        private AllocationProperties properties;
        private Window window;
        private OffsetDateTime start;
        private OffsetDateTime end;
        private double cPUCoreHours;
        private double cPUCoreRequestAverage;
        private double cPUCoreUsageAverage;
        private double cPUCost;
        private double cPUCostAdjustment;
        private double gPUHours;
        private double gPUCost;
        private double gPUCostAdjustment;
        private double networkTransferBytes;
        private double networkReceiveBytes;
        private double networkCost;
        private double networkCostAdjustment;
        private double loadBalancerCost;
        private double loadBalancerCostAdjustment;
        private Map<PVKey, PVAllocation> pVs;
        private double pVCostAdjustment;
        private double rAMByteHours;
        private double rAMBytesRequestAverage;
        private double rAMBytesUsageAverage;
        private double rAMCost;
        private double rAMCostAdjustment;
        private double sharedCost;
        private double externalCost;
        private RawAllocationOnlyData rawAllocationOnly;
        private int testProperty;
        private String testStr;
        public Builder name(String name) {
            this.name = name;
            return this;
        }
        public Builder properties(AllocationProperties properties) {
            this.properties = properties;
            return this;
        }
        public Builder window(Window window) {
            this.window = window;
            return this;
        }
        public Builder start(OffsetDateTime start) {
            this.start = start;
            return this;
        }
        public Builder end(OffsetDateTime end) {
            this.end = end;
            return this;
        }
        public Builder cPUCoreHours(double cPUCoreHours) {
            this.cPUCoreHours = cPUCoreHours;
            return this;
        }
        public Builder cPUCoreRequestAverage(double cPUCoreRequestAverage) {
            this.cPUCoreRequestAverage = cPUCoreRequestAverage;
            return this;
        }
        public Builder cPUCoreUsageAverage(double cPUCoreUsageAverage) {
            this.cPUCoreUsageAverage = cPUCoreUsageAverage;
            return this;
        }
        public Builder cPUCost(double cPUCost) {
            this.cPUCost = cPUCost;
            return this;
        }
        public Builder cPUCostAdjustment(double cPUCostAdjustment) {
            this.cPUCostAdjustment = cPUCostAdjustment;
            return this;
        }
        public Builder gPUHours(double gPUHours) {
            this.gPUHours = gPUHours;
            return this;
        }
        public Builder gPUCost(double gPUCost) {
            this.gPUCost = gPUCost;
            return this;
        }
        public Builder gPUCostAdjustment(double gPUCostAdjustment) {
            this.gPUCostAdjustment = gPUCostAdjustment;
            return this;
        }
        public Builder networkTransferBytes(double networkTransferBytes) {
            this.networkTransferBytes = networkTransferBytes;
            return this;
        }
        public Builder networkReceiveBytes(double networkReceiveBytes) {
            this.networkReceiveBytes = networkReceiveBytes;
            return this;
        }
        public Builder networkCost(double networkCost) {
            this.networkCost = networkCost;
            return this;
        }
        public Builder networkCostAdjustment(double networkCostAdjustment) {
            this.networkCostAdjustment = networkCostAdjustment;
            return this;
        }
        public Builder loadBalancerCost(double loadBalancerCost) {
            this.loadBalancerCost = loadBalancerCost;
            return this;
        }
        public Builder loadBalancerCostAdjustment(double loadBalancerCostAdjustment) {
            this.loadBalancerCostAdjustment = loadBalancerCostAdjustment;
            return this;
        }
        public Builder pVs(Map<PVKey, PVAllocation> pVs) {
            this.pVs = pVs;
            return this;
        }
        public Builder pVCostAdjustment(double pVCostAdjustment) {
            this.pVCostAdjustment = pVCostAdjustment;
            return this;
        }
        public Builder rAMByteHours(double rAMByteHours) {
            this.rAMByteHours = rAMByteHours;
            return this;
        }
        public Builder rAMBytesRequestAverage(double rAMBytesRequestAverage) {
            this.rAMBytesRequestAverage = rAMBytesRequestAverage;
            return this;
        }
        public Builder rAMBytesUsageAverage(double rAMBytesUsageAverage) {
            this.rAMBytesUsageAverage = rAMBytesUsageAverage;
            return this;
        }
        public Builder rAMCost(double rAMCost) {
            this.rAMCost = rAMCost;
            return this;
        }
        public Builder rAMCostAdjustment(double rAMCostAdjustment) {
            this.rAMCostAdjustment = rAMCostAdjustment;
            return this;
        }
        public Builder sharedCost(double sharedCost) {
            this.sharedCost = sharedCost;
            return this;
        }
        public Builder externalCost(double externalCost) {
            this.externalCost = externalCost;
            return this;
        }
        public Builder rawAllocationOnly(RawAllocationOnlyData rawAllocationOnly) {
            this.rawAllocationOnly = rawAllocationOnly;
            return this;
        }
        public Builder testProperty(int testProperty) {
            this.testProperty = testProperty;
            return this;
        }
        public Builder testStr(String testStr) {
            this.testStr = testStr;
            return this;
        }

        public Allocation build() {
            return new Allocation(name, properties, window, start, end, cPUCoreHours, cPUCoreRequestAverage, cPUCoreUsageAverage, cPUCost, cPUCostAdjustment, gPUHours, gPUCost, gPUCostAdjustment, networkTransferBytes, networkReceiveBytes, networkCost, networkCostAdjustment, loadBalancerCost, loadBalancerCostAdjustment, pVs, pVCostAdjustment, rAMByteHours, rAMBytesRequestAverage, rAMBytesUsageAverage, rAMCost, rAMCostAdjustment, sharedCost, externalCost, rawAllocationOnly, testProperty, testStr);
        }
    }
}
