////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import com.bingen.GoTime;
import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generated binary decoder for {@link Allocation}.
 */
public final class AllocationDecoder implements BinDecoder<Allocation> {

    public static final AllocationDecoder INSTANCE = new AllocationDecoder();

    private static final int VERSION = 16;

    /** Decodes a {@link Allocation} from a standalone byte array. */
    public static Allocation fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** Decodes a {@link Allocation} read incrementally from a stream. */
    public static Allocation fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public Allocation decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding Allocation: expected " + VERSION + " or less, got " + version);
        }

        Allocation.Builder builder = Allocation.builder();
        String v0;
        if (ctx.isStringTable()) {
            v0 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v0 = buff.readString(); // read string
        }
        builder.name(v0);
        AllocationProperties v1;
        if (buff.readUInt8() == 0) {
            v1 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v1 = AllocationPropertiesDecoder.INSTANCE.decode(ctx);
        }
        builder.properties(v1);
        Window v2;
        buff.readInt(); // [compatibility, unused]
        v2 = WindowDecoder.INSTANCE.decode(ctx);
        builder.window(v2);
        OffsetDateTime v3;
        v3 = GoTime.decode(buff);
        builder.start(v3);
        OffsetDateTime v4;
        v4 = GoTime.decode(buff);
        builder.end(v4);
        double v5;
        v5 = buff.readFloat64();
        builder.cPUCoreHours(v5);
        double v6;
        v6 = buff.readFloat64();
        builder.cPUCoreRequestAverage(v6);
        double v7;
        v7 = buff.readFloat64();
        builder.cPUCoreUsageAverage(v7);
        double v8;
        v8 = buff.readFloat64();
        builder.cPUCost(v8);
        double v9;
        v9 = buff.readFloat64();
        builder.cPUCostAdjustment(v9);
        double v10;
        v10 = buff.readFloat64();
        builder.gPUHours(v10);
        double v11;
        v11 = buff.readFloat64();
        builder.gPUCost(v11);
        double v12;
        v12 = buff.readFloat64();
        builder.gPUCostAdjustment(v12);
        double v13;
        v13 = buff.readFloat64();
        builder.networkTransferBytes(v13);
        double v14;
        v14 = buff.readFloat64();
        builder.networkReceiveBytes(v14);
        double v15;
        v15 = buff.readFloat64();
        builder.networkCost(v15);
        double v16;
        v16 = buff.readFloat64();
        builder.networkCostAdjustment(v16);
        double v17;
        v17 = buff.readFloat64();
        builder.loadBalancerCost(v17);
        double v18;
        v18 = buff.readFloat64();
        builder.loadBalancerCostAdjustment(v18);
        Map<PVKey, PVAllocation> v19;
        if (buff.readUInt8() == 0) {
            v19 = null;
        } else {
            int v20 = buff.readInt(); // map length
            v19 = new LinkedHashMap<>(v20);
            for (int v21 = 0; v21 < v20; v21++) {
                PVKey v22;
                buff.readInt(); // [compatibility, unused]
                v22 = PVKeyDecoder.INSTANCE.decode(ctx);
                PVAllocation v23;
                if (buff.readUInt8() == 0) {
                    v23 = null;
                } else {
                    buff.readInt(); // [compatibility, unused]
                    v23 = PVAllocationDecoder.INSTANCE.decode(ctx);
                }
                v19.put(v22, v23);
            }
        }
        builder.pVs(v19);
        double v24;
        v24 = buff.readFloat64();
        builder.pVCostAdjustment(v24);
        double v25;
        v25 = buff.readFloat64();
        builder.rAMByteHours(v25);
        double v26;
        v26 = buff.readFloat64();
        builder.rAMBytesRequestAverage(v26);
        double v27;
        v27 = buff.readFloat64();
        builder.rAMBytesUsageAverage(v27);
        double v28;
        v28 = buff.readFloat64();
        builder.rAMCost(v28);
        double v29;
        v29 = buff.readFloat64();
        builder.rAMCostAdjustment(v29);
        double v30;
        v30 = buff.readFloat64();
        builder.sharedCost(v30);
        double v31;
        v31 = buff.readFloat64();
        builder.externalCost(v31);
        RawAllocationOnlyData v32;
        if (buff.readUInt8() == 0) {
            v32 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v32 = RawAllocationOnlyDataDecoder.INSTANCE.decode(ctx);
        }
        builder.rawAllocationOnly(v32);
        if (16 <= version) {
            int v33;
            v33 = buff.readInt();
            builder.testProperty(v33);
        } else {
            builder.testProperty(0);
        }
        if (16 <= version) {
            String v34;
            if (ctx.isStringTable()) {
                v34 = ctx.table().at(buff.readInt()); // string table index
            } else {
                v34 = buff.readString(); // read string
            }
            builder.testStr(v34);
        } else {
            builder.testStr("test");
        }
        Allocation result = builder.build();
        return result;
    }
}
