////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BingenConsumer;
import com.bingen.BingenFieldInfo;
import com.bingen.BingenValue;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.ByteArrayInputStream;
import java.io.InputStream;

/**
 * Generated push streamer for {@link AllocationSet}. Each field is delivered to
 * the consumer; slices and maps are flattened one depth (one element per call).
 * Return false from the consumer to stop early.
 */
public final class AllocationSetStreamer {

    private static final int VERSION = 16;

    private AllocationSetStreamer() {
    }

    /** Streams the fields of an encoded {@link AllocationSet} held in memory. */
    public static void stream(byte[] data, BingenConsumer consumer) {
        stream(new ByteArrayInputStream(data), consumer);
    }

    /**
     * Streams the fields of an encoded {@link AllocationSet} read incrementally
     * from {@code in} (socket, file, ...). The caller retains ownership of the
     * stream and is responsible for closing it.
     */
    public static void stream(InputStream in, BingenConsumer consumer) {
        DecodingContext ctx = DecodingContext.fromStream(in);
        ReadBuffer buff = ctx.buffer();

        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version streaming AllocationSet: expected " + VERSION + " or less, got " + version);
        }

        BingenFieldInfo fi = null;
        fi = new BingenFieldInfo("allocations");
        if (buff.readUInt8() == 0) {
            if (!consumer.accept(fi, null)) {
                return;
            }
        } else {
            int v0 = buff.readInt();
            for (int v1 = 0; v1 < v0; v1++) {
                String v2;
                if (ctx.isStringTable()) {
                    v2 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v2 = buff.readString(); // read string
                }
                Allocation v3;
                if (buff.readUInt8() == 0) {
                    v3 = null;
                } else {
                    buff.readInt(); // [compatibility, unused]
                    v3 = AllocationDecoder.INSTANCE.decode(ctx);
                }
                if (!consumer.accept(fi, BingenValue.pair(v2, v3))) {
                    return;
                }
            }
        }
        fi = new BingenFieldInfo("externalKeys");
        if (buff.readUInt8() == 0) {
            if (!consumer.accept(fi, null)) {
                return;
            }
        } else {
            int v4 = buff.readInt();
            for (int v5 = 0; v5 < v4; v5++) {
                String v6;
                if (ctx.isStringTable()) {
                    v6 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v6 = buff.readString(); // read string
                }
                boolean v7;
                v7 = buff.readBool();
                if (!consumer.accept(fi, BingenValue.pair(v6, v7))) {
                    return;
                }
            }
        }
        fi = new BingenFieldInfo("idleKeys");
        if (buff.readUInt8() == 0) {
            if (!consumer.accept(fi, null)) {
                return;
            }
        } else {
            int v8 = buff.readInt();
            for (int v9 = 0; v9 < v8; v9++) {
                String v10;
                if (ctx.isStringTable()) {
                    v10 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v10 = buff.readString(); // read string
                }
                boolean v11;
                v11 = buff.readBool();
                if (!consumer.accept(fi, BingenValue.pair(v10, v11))) {
                    return;
                }
            }
        }
        fi = new BingenFieldInfo("FromSource");
        String v12;
        if (ctx.isStringTable()) {
            v12 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v12 = buff.readString(); // read string
        }
        if (!consumer.accept(fi, BingenValue.single(v12))) {
            return;
        }
        fi = new BingenFieldInfo("Window");
        Window v13;
        buff.readInt(); // [compatibility, unused]
        v13 = WindowDecoder.INSTANCE.decode(ctx);
        if (!consumer.accept(fi, BingenValue.single(v13))) {
            return;
        }
        fi = new BingenFieldInfo("Warnings");
        if (buff.readUInt8() == 0) {
            if (!consumer.accept(fi, null)) {
                return;
            }
        } else {
            int v14 = buff.readInt();
            for (int v15 = 0; v15 < v14; v15++) {
                String v16;
                if (ctx.isStringTable()) {
                    v16 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v16 = buff.readString(); // read string
                }
                if (!consumer.accept(fi, BingenValue.pair(v15, v16))) {
                    return;
                }
            }
        }
        fi = new BingenFieldInfo("Errors");
        if (buff.readUInt8() == 0) {
            if (!consumer.accept(fi, null)) {
                return;
            }
        } else {
            int v17 = buff.readInt();
            for (int v18 = 0; v18 < v17; v18++) {
                String v19;
                if (ctx.isStringTable()) {
                    v19 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v19 = buff.readString(); // read string
                }
                if (!consumer.accept(fi, BingenValue.pair(v18, v19))) {
                    return;
                }
            }
        }
    }
}
