////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated binary decoder for {@link AllocationSetRange}.
 */
public final class AllocationSetRangeDecoder implements BinDecoder<AllocationSetRange> {

    public static final AllocationSetRangeDecoder INSTANCE = new AllocationSetRangeDecoder();

    private static final int VERSION = 16;

    /** Decodes a {@link AllocationSetRange} from a standalone byte array. */
    public static AllocationSetRange fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** Decodes a {@link AllocationSetRange} read incrementally from a stream. */
    public static AllocationSetRange fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public AllocationSetRange decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding AllocationSetRange: expected " + VERSION + " or less, got " + version);
        }

        AllocationSetRange.Builder builder = AllocationSetRange.builder();
        List<AllocationSet> v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            int v1 = buff.readInt(); // slice length
            v0 = new ArrayList<>(v1);
            for (int v2 = 0; v2 < v1; v2++) {
                AllocationSet v3;
                if (buff.readUInt8() == 0) {
                    v3 = null;
                } else {
                    buff.readInt(); // [compatibility, unused]
                    v3 = AllocationSetDecoder.INSTANCE.decode(ctx);
                }
                v0.add(v3);
            }
        }
        builder.allocations(v0);
        String v4;
        if (ctx.isStringTable()) {
            v4 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v4 = buff.readString(); // read string
        }
        builder.fromStore(v4);
        AllocationSetRange result = builder.build();
        return result;
    }
}
