////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import com.bingen.GoTime;
import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generated binary decoder for {@link Any}.
 */
public final class AnyDecoder implements BinDecoder<Any> {

    public static final AnyDecoder INSTANCE = new AnyDecoder();

    private static final int VERSION = 16;

    /** Decodes a {@link Any} from a standalone byte array. */
    public static Any fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** Decodes a {@link Any} read incrementally from a stream. */
    public static Any fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public Any decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding Any: expected " + VERSION + " or less, got " + version);
        }

        Any.Builder builder = Any.builder();
        Map<String, String> v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            int v1 = buff.readInt(); // map length
            v0 = new LinkedHashMap<>(v1);
            for (int v2 = 0; v2 < v1; v2++) {
                String v3;
                if (ctx.isStringTable()) {
                    v3 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v3 = buff.readString(); // read string
                }
                String v4;
                if (ctx.isStringTable()) {
                    v4 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v4 = buff.readString(); // read string
                }
                v0.put(v3, v4);
            }
        }
        builder.labels(v0);
        AssetProperties v5;
        if (buff.readUInt8() == 0) {
            v5 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v5 = AssetPropertiesDecoder.INSTANCE.decode(ctx);
        }
        builder.properties(v5);
        OffsetDateTime v6;
        v6 = GoTime.decode(buff);
        builder.start(v6);
        OffsetDateTime v7;
        v7 = GoTime.decode(buff);
        builder.end(v7);
        Window v8;
        buff.readInt(); // [compatibility, unused]
        v8 = WindowDecoder.INSTANCE.decode(ctx);
        builder.window(v8);
        double v9;
        v9 = buff.readFloat64();
        builder.adjustment(v9);
        double v10;
        v10 = buff.readFloat64();
        builder.cost(v10);
        Any result = builder.build();
        return result;
    }
}
