////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;

/**
 * Generated binary encoder for {@link AssetSetRange}.
 */
public final class AssetSetRangeEncoder implements BinEncoder<AssetSetRange> {

    public static final AssetSetRangeEncoder INSTANCE = new AssetSetRangeEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** Encodes {@code value} to a standalone byte array. */
    public static byte[] toBytes(AssetSetRange value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(AssetSetRange value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (value.assets() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.assets().size()); // slice length
            for (AssetSet v0 : value.assets()) {
                if (v0 == null) {
                    buff.writeUInt8(0); // write nil byte
                } else {
                    buff.writeUInt8(1); // write non-nil byte
                    buff.writeInt(0); // [compatibility, unused]
                    AssetSetEncoder.INSTANCE.encode(v0, ctx);
                }
            }
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.fromStore())); // string table index
        } else {
            buff.writeString(value.fromStore()); // string
        }
    }
}
