////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;

/**
 * Generated binary encoder for {@link AssetProperties}.
 */
public final class AssetPropertiesEncoder implements BinEncoder<AssetProperties> {

    public static final AssetPropertiesEncoder INSTANCE = new AssetPropertiesEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** 
     * Encodes {@code value} to a standalone byte array. 
     */
    public static byte[] toBytes(AssetProperties value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(AssetProperties value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.category())); // string table index
        } else {
            buff.writeString(value.category()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.provider())); // string table index
        } else {
            buff.writeString(value.provider()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.account())); // string table index
        } else {
            buff.writeString(value.account()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.project())); // string table index
        } else {
            buff.writeString(value.project()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.service())); // string table index
        } else {
            buff.writeString(value.service()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.cluster())); // string table index
        } else {
            buff.writeString(value.cluster()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.name())); // string table index
        } else {
            buff.writeString(value.name()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.providerID())); // string table index
        } else {
            buff.writeString(value.providerID()); // string
        }
    }
}
