////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;


/**
 * Generated data type for the {@code AssetProperties} go struct.
 */
public record AssetProperties(String category, String provider, String account, String project, String service, String cluster, String name, String providerID) {

    /** Creates a new builder for {@link AssetProperties}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Mutable builder the decoder uses to accumulate fields and apply defaults. */
    public static final class Builder {
        private String category;
        private String provider;
        private String account;
        private String project;
        private String service;
        private String cluster;
        private String name;
        private String providerID;
        public Builder category(String category) {
            this.category = category;
            return this;
        }
        public Builder provider(String provider) {
            this.provider = provider;
            return this;
        }
        public Builder account(String account) {
            this.account = account;
            return this;
        }
        public Builder project(String project) {
            this.project = project;
            return this;
        }
        public Builder service(String service) {
            this.service = service;
            return this;
        }
        public Builder cluster(String cluster) {
            this.cluster = cluster;
            return this;
        }
        public Builder name(String name) {
            this.name = name;
            return this;
        }
        public Builder providerID(String providerID) {
            this.providerID = providerID;
            return this;
        }

        public AssetProperties build() {
            return new AssetProperties(category, provider, account, project, service, cluster, name, providerID);
        }
    }
}
