////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BingenConsumer;
import com.bingen.BingenFieldInfo;
import com.bingen.BingenValue;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.ByteArrayInputStream;
import java.io.InputStream;

/**
 * Generated push streamer for {@link AssetSet}. Each field is delivered to
 * the consumer; slices and maps are flattened one depth (one element per call).
 * Return false from the consumer to stop early.
 */
public final class AssetSetStreamer {

    private static final int VERSION = 16;

    private AssetSetStreamer() {
    }

    /** Streams the fields of an encoded {@link AssetSet} held in memory. */
    public static void stream(byte[] data, BingenConsumer consumer) {
        stream(new ByteArrayInputStream(data), consumer);
    }

    /**
     * Streams the fields of an encoded {@link AssetSet} read incrementally
     * from {@code in} (socket, file, ...). The caller retains ownership of the
     * stream and is responsible for closing it.
     */
    public static void stream(InputStream in, BingenConsumer consumer) {
        DecodingContext ctx = DecodingContext.fromStream(in);
        ReadBuffer buff = ctx.buffer();

        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version streaming AssetSet: expected " + VERSION + " or less, got " + version);
        }

        BingenFieldInfo fi = null;
        fi = new BingenFieldInfo("aggregateBy");
        if (buff.readUInt8() == 0) {
            if (!consumer.accept(fi, null)) {
                return;
            }
        } else {
            int v0 = buff.readInt();
            for (int v1 = 0; v1 < v0; v1++) {
                String v2;
                if (ctx.isStringTable()) {
                    v2 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v2 = buff.readString(); // read string
                }
                if (!consumer.accept(fi, BingenValue.pair(v1, v2))) {
                    return;
                }
            }
        }
        fi = new BingenFieldInfo("assets");
        if (buff.readUInt8() == 0) {
            if (!consumer.accept(fi, null)) {
                return;
            }
        } else {
            int v3 = buff.readInt();
            for (int v4 = 0; v4 < v3; v4++) {
                String v5;
                if (ctx.isStringTable()) {
                    v5 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v5 = buff.readString(); // read string
                }
                Asset v6;
                if (buff.readUInt8() == 0) {
                    v6 = null;
                } else {
                    String v7 = buff.readString();
                    v6 = (Asset) TypeRegistry.decode(v7, ctx);
                }
                if (!consumer.accept(fi, BingenValue.pair(v5, v6))) {
                    return;
                }
            }
        }
        fi = new BingenFieldInfo("FromSource");
        String v8;
        if (ctx.isStringTable()) {
            v8 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v8 = buff.readString(); // read string
        }
        if (!consumer.accept(fi, BingenValue.single(v8))) {
            return;
        }
        fi = new BingenFieldInfo("Window");
        Window v9;
        buff.readInt(); // [compatibility, unused]
        v9 = WindowDecoder.INSTANCE.decode(ctx);
        if (!consumer.accept(fi, BingenValue.single(v9))) {
            return;
        }
        fi = new BingenFieldInfo("Warnings");
        if (buff.readUInt8() == 0) {
            if (!consumer.accept(fi, null)) {
                return;
            }
        } else {
            int v10 = buff.readInt();
            for (int v11 = 0; v11 < v10; v11++) {
                String v12;
                if (ctx.isStringTable()) {
                    v12 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v12 = buff.readString(); // read string
                }
                if (!consumer.accept(fi, BingenValue.pair(v11, v12))) {
                    return;
                }
            }
        }
        fi = new BingenFieldInfo("Errors");
        if (buff.readUInt8() == 0) {
            if (!consumer.accept(fi, null)) {
                return;
            }
        } else {
            int v13 = buff.readInt();
            for (int v14 = 0; v14 < v13; v14++) {
                String v15;
                if (ctx.isStringTable()) {
                    v15 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v15 = buff.readString(); // read string
                }
                if (!consumer.accept(fi, BingenValue.pair(v14, v15))) {
                    return;
                }
            }
        }
    }
}
