////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;

/**
 * Generated binary decoder for {@link AssetProperties}.
 */
public final class AssetPropertiesDecoder implements BinDecoder<AssetProperties> {

    public static final AssetPropertiesDecoder INSTANCE = new AssetPropertiesDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link AssetProperties} from a standalone byte array. 
     */
    public static AssetProperties fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link AssetProperties} read incrementally from a stream. 
     */
    public static AssetProperties fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public AssetProperties decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding AssetProperties: expected " + VERSION + " or less, got " + version);
        }

        AssetProperties.Builder builder = AssetProperties.builder();
        String v0;
        if (ctx.isStringTable()) {
            v0 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v0 = buff.readString(); // read string
        }
        builder.category(v0);
        String v1;
        if (ctx.isStringTable()) {
            v1 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v1 = buff.readString(); // read string
        }
        builder.provider(v1);
        String v2;
        if (ctx.isStringTable()) {
            v2 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v2 = buff.readString(); // read string
        }
        builder.account(v2);
        String v3;
        if (ctx.isStringTable()) {
            v3 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v3 = buff.readString(); // read string
        }
        builder.project(v3);
        String v4;
        if (ctx.isStringTable()) {
            v4 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v4 = buff.readString(); // read string
        }
        builder.service(v4);
        String v5;
        if (ctx.isStringTable()) {
            v5 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v5 = buff.readString(); // read string
        }
        builder.cluster(v5);
        String v6;
        if (ctx.isStringTable()) {
            v6 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v6 = buff.readString(); // read string
        }
        builder.name(v6);
        String v7;
        if (ctx.isStringTable()) {
            v7 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v7 = buff.readString(); // read string
        }
        builder.providerID(v7);
        AssetProperties result = builder.build();
        return result;
    }
}
