////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

/**
 * Marker interface for the {@code Asset} go interface. Concrete
 * implementations are dispatched by the generated {@code TypeRegistry}.
 */
public interface Asset {
}
