////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;
import java.util.Map;

/**
 * Generated binary encoder for {@link AssetSet}.
 */
public final class AssetSetEncoder implements BinEncoder<AssetSet> {

    public static final AssetSetEncoder INSTANCE = new AssetSetEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = true;

    /** Encodes {@code value} to a standalone byte array. */
    public static byte[] toBytes(AssetSet value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(AssetSet value, EncodingContext ctx) {
        value = AssetSetHooks.preProcess(value);
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (value.aggregateBy() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.aggregateBy().size()); // slice length
            for (String v0 : value.aggregateBy()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v0)); // string table index
                } else {
                    buff.writeString(v0); // string
                }
            }
        }
        if (value.assets() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.assets().size()); // map length
            for (Map.Entry<String, Asset> v1 : value.assets().entrySet()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v1.getKey())); // string table index
                } else {
                    buff.writeString(v1.getKey()); // string
                }
                if (v1.getValue() == null) {
                    buff.writeUInt8(0); // write nil byte
                } else {
                    buff.writeUInt8(1); // write non-nil byte
                    TypeRegistry.encode(v1.getValue(), ctx);
                }
            }
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.fromSource())); // string table index
        } else {
            buff.writeString(value.fromSource()); // string
        }
        buff.writeInt(0); // [compatibility, unused]
        WindowEncoder.INSTANCE.encode(value.window(), ctx);
        if (value.warnings() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.warnings().size()); // slice length
            for (String v2 : value.warnings()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v2)); // string table index
                } else {
                    buff.writeString(v2); // string
                }
            }
        }
        if (value.errors() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.errors().size()); // slice length
            for (String v3 : value.errors()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v3)); // string table index
                } else {
                    buff.writeString(v3); // string
                }
            }
        }
    }
}
