////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.util.List;

/**
 * Generated data type for the {@code AssetSetRange} go struct.
 */
public record AssetSetRange(List<AssetSet> assets, String fromStore) {

    /** 
     * Creates a new builder for {@link AssetSetRange}. 
     */
    public static Builder builder() {
        return new Builder();
    }

    /** 
     * Mutable builder the decoder uses to accumulate fields and apply defaults. 
     */
    public static final class Builder {
        private List<AssetSet> assets;
        private String fromStore;
        public Builder assets(List<AssetSet> assets) {
            this.assets = assets;
            return this;
        }
        public Builder fromStore(String fromStore) {
            this.fromStore = fromStore;
            return this;
        }

        public AssetSetRange build() {
            return new AssetSetRange(assets, fromStore);
        }
    }
}
