////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated binary decoder for {@link AssetSet}.
 */
public final class AssetSetDecoder implements BinDecoder<AssetSet> {

    public static final AssetSetDecoder INSTANCE = new AssetSetDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link AssetSet} from a standalone byte array. 
     */
    public static AssetSet fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link AssetSet} read incrementally from a stream. 
     */
    public static AssetSet fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public AssetSet decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding AssetSet: expected " + VERSION + " or less, got " + version);
        }

        AssetSet.Builder builder = AssetSet.builder();
        List<String> v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            int v1 = buff.readInt(); // slice length
            v0 = new ArrayList<>(v1);
            for (int v2 = 0; v2 < v1; v2++) {
                String v3;
                if (ctx.isStringTable()) {
                    v3 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v3 = buff.readString(); // read string
                }
                v0.add(v3);
            }
        }
        builder.aggregateBy(v0);
        Map<String, Asset> v4;
        if (buff.readUInt8() == 0) {
            v4 = null;
        } else {
            int v5 = buff.readInt(); // map length
            v4 = new LinkedHashMap<>(v5);
            for (int v6 = 0; v6 < v5; v6++) {
                String v7;
                if (ctx.isStringTable()) {
                    v7 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v7 = buff.readString(); // read string
                }
                Asset v8;
                if (buff.readUInt8() == 0) {
                    v8 = null;
                } else {
                    String v9 = buff.readString();
                    v8 = (Asset) TypeRegistry.decode(v9, ctx);
                }
                v4.put(v7, v8);
            }
        }
        builder.assets(v4);
        String v10;
        if (ctx.isStringTable()) {
            v10 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v10 = buff.readString(); // read string
        }
        builder.fromSource(v10);
        Window v11;
        buff.readInt(); // [compatibility, unused]
        v11 = WindowDecoder.INSTANCE.decode(ctx);
        builder.window(v11);
        List<String> v12;
        if (buff.readUInt8() == 0) {
            v12 = null;
        } else {
            int v13 = buff.readInt(); // slice length
            v12 = new ArrayList<>(v13);
            for (int v14 = 0; v14 < v13; v14++) {
                String v15;
                if (ctx.isStringTable()) {
                    v15 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v15 = buff.readString(); // read string
                }
                v12.add(v15);
            }
        }
        builder.warnings(v12);
        List<String> v16;
        if (buff.readUInt8() == 0) {
            v16 = null;
        } else {
            int v17 = buff.readInt(); // slice length
            v16 = new ArrayList<>(v17);
            for (int v18 = 0; v18 < v17; v18++) {
                String v19;
                if (ctx.isStringTable()) {
                    v19 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v19 = buff.readString(); // read string
                }
                v16.add(v19);
            }
        }
        builder.errors(v16);
        AssetSet result = builder.build();
        result = AssetSetHooks.postProcess(result);
        return result;
    }
}
