////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated binary decoder for {@link AssetSetRange}.
 */
public final class AssetSetRangeDecoder implements BinDecoder<AssetSetRange> {

    public static final AssetSetRangeDecoder INSTANCE = new AssetSetRangeDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link AssetSetRange} from a standalone byte array. 
     */
    public static AssetSetRange fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link AssetSetRange} read incrementally from a stream. 
     */
    public static AssetSetRange fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public AssetSetRange decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding AssetSetRange: expected " + VERSION + " or less, got " + version);
        }

        AssetSetRange.Builder builder = AssetSetRange.builder();
        List<AssetSet> v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            int v1 = buff.readInt(); // slice length
            v0 = new ArrayList<>(v1);
            for (int v2 = 0; v2 < v1; v2++) {
                AssetSet v3;
                if (buff.readUInt8() == 0) {
                    v3 = null;
                } else {
                    buff.readInt(); // [compatibility, unused]
                    v3 = AssetSetDecoder.INSTANCE.decode(ctx);
                }
                v0.add(v3);
            }
        }
        builder.assets(v0);
        String v4;
        if (ctx.isStringTable()) {
            v4 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v4 = buff.readString(); // read string
        }
        builder.fromStore(v4);
        AssetSetRange result = builder.build();
        return result;
    }
}
