////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.util.List;
import java.util.Map;

/**
 * Generated data type for the {@code AssetSet} go struct.
 */
public record AssetSet(List<String> aggregateBy, Map<String, Asset> assets, String fromSource, Window window, List<String> warnings, List<String> errors) {

    /** Creates a new builder for {@link AssetSet}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Mutable builder the decoder uses to accumulate fields and apply defaults. */
    public static final class Builder {
        private List<String> aggregateBy;
        private Map<String, Asset> assets;
        private String fromSource;
        private Window window;
        private List<String> warnings;
        private List<String> errors;
        public Builder aggregateBy(List<String> aggregateBy) {
            this.aggregateBy = aggregateBy;
            return this;
        }
        public Builder assets(Map<String, Asset> assets) {
            this.assets = assets;
            return this;
        }
        public Builder fromSource(String fromSource) {
            this.fromSource = fromSource;
            return this;
        }
        public Builder window(Window window) {
            this.window = window;
            return this;
        }
        public Builder warnings(List<String> warnings) {
            this.warnings = warnings;
            return this;
        }
        public Builder errors(List<String> errors) {
            this.errors = errors;
            return this;
        }

        public AssetSet build() {
            return new AssetSet(aggregateBy, assets, fromSource, window, warnings, errors);
        }
    }
}
