////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;

/**
 * Generated binary decoder for {@link Breakdown}.
 */
public final class BreakdownDecoder implements BinDecoder<Breakdown> {

    public static final BreakdownDecoder INSTANCE = new BreakdownDecoder();

    private static final int VERSION = 16;

    /** Decodes a {@link Breakdown} from a standalone byte array. */
    public static Breakdown fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** Decodes a {@link Breakdown} read incrementally from a stream. */
    public static Breakdown fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public Breakdown decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding Breakdown: expected " + VERSION + " or less, got " + version);
        }

        Breakdown.Builder builder = Breakdown.builder();
        double v0;
        v0 = buff.readFloat64();
        builder.idle(v0);
        double v1;
        v1 = buff.readFloat64();
        builder.other(v1);
        double v2;
        v2 = buff.readFloat64();
        builder.system(v2);
        double v3;
        v3 = buff.readFloat64();
        builder.user(v3);
        Breakdown result = builder.build();
        return result;
    }
}
