////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;

/**
 * Generated binary encoder for {@link Breakdown}.
 */
public final class BreakdownEncoder implements BinEncoder<Breakdown> {

    public static final BreakdownEncoder INSTANCE = new BreakdownEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** 
     * Encodes {@code value} to a standalone byte array. 
     */
    public static byte[] toBytes(Breakdown value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(Breakdown value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        buff.writeFloat64(value.idle());
        buff.writeFloat64(value.other());
        buff.writeFloat64(value.system());
        buff.writeFloat64(value.user());
    }
}
