////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;


/**
 * Generated data type for the {@code Breakdown} go struct.
 */
public record Breakdown(double idle, double other, double system, double user) {

    /** 
     * Creates a new builder for {@link Breakdown}. 
     */
    public static Builder builder() {
        return new Builder();
    }

    /** 
     * Mutable builder the decoder uses to accumulate fields and apply defaults. 
     */
    public static final class Builder {
        private double idle;
        private double other;
        private double system;
        private double user;
        public Builder idle(double idle) {
            this.idle = idle;
            return this;
        }
        public Builder other(double other) {
            this.other = other;
            return this;
        }
        public Builder system(double system) {
            this.system = system;
            return this;
        }
        public Builder user(double user) {
            this.user = user;
            return this;
        }

        public Breakdown build() {
            return new Breakdown(idle, other, system, user);
        }
    }
}
