////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Generated data type for the {@code Cloud} go struct.
 */
public record Cloud(Map<String, String> labels, AssetProperties properties, OffsetDateTime start, OffsetDateTime end, Window window, double adjustment, double cost, double credit) implements Asset {

    /** 
     * Creates a new builder for {@link Cloud}. 
     */
    public static Builder builder() {
        return new Builder();
    }

    /** 
     * Mutable builder the decoder uses to accumulate fields and apply defaults. 
     */
    public static final class Builder {
        private Map<String, String> labels;
        private AssetProperties properties;
        private OffsetDateTime start;
        private OffsetDateTime end;
        private Window window;
        private double adjustment;
        private double cost;
        private double credit;
        public Builder labels(Map<String, String> labels) {
            this.labels = labels;
            return this;
        }
        public Builder properties(AssetProperties properties) {
            this.properties = properties;
            return this;
        }
        public Builder start(OffsetDateTime start) {
            this.start = start;
            return this;
        }
        public Builder end(OffsetDateTime end) {
            this.end = end;
            return this;
        }
        public Builder window(Window window) {
            this.window = window;
            return this;
        }
        public Builder adjustment(double adjustment) {
            this.adjustment = adjustment;
            return this;
        }
        public Builder cost(double cost) {
            this.cost = cost;
            return this;
        }
        public Builder credit(double credit) {
            this.credit = credit;
            return this;
        }

        public Cloud build() {
            return new Cloud(labels, properties, start, end, window, adjustment, cost, credit);
        }
    }
}
