////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.util.Map;

/**
 * Generated data type for the {@code ClusterManagement} go struct.
 */
public record ClusterManagement(Map<String, String> labels, AssetProperties properties, Window window, double cost) implements Asset {

    /** 
     * Creates a new builder for {@link ClusterManagement}. 
     */
    public static Builder builder() {
        return new Builder();
    }

    /** 
     * Mutable builder the decoder uses to accumulate fields and apply defaults. 
     */
    public static final class Builder {
        private Map<String, String> labels;
        private AssetProperties properties;
        private Window window;
        private double cost;
        public Builder labels(Map<String, String> labels) {
            this.labels = labels;
            return this;
        }
        public Builder properties(AssetProperties properties) {
            this.properties = properties;
            return this;
        }
        public Builder window(Window window) {
            this.window = window;
            return this;
        }
        public Builder cost(double cost) {
            this.cost = cost;
            return this;
        }

        public ClusterManagement build() {
            return new ClusterManagement(labels, properties, window, cost);
        }
    }
}
