////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;
import com.bingen.GoTime;
import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Generated binary encoder for {@link Disk}.
 */
public final class DiskEncoder implements BinEncoder<Disk> {

    public static final DiskEncoder INSTANCE = new DiskEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** 
     * Encodes {@code value} to a standalone byte array. 
     */
    public static byte[] toBytes(Disk value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(Disk value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (value.labels() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.labels().size()); // map length
            for (Map.Entry<String, String> v0 : value.labels().entrySet()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v0.getKey())); // string table index
                } else {
                    buff.writeString(v0.getKey()); // string
                }
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v0.getValue())); // string table index
                } else {
                    buff.writeString(v0.getValue()); // string
                }
            }
        }
        if (value.properties() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(0); // [compatibility, unused]
            AssetPropertiesEncoder.INSTANCE.encode(value.properties(), ctx);
        }
        GoTime.encode(value.start(), buff);
        GoTime.encode(value.end(), buff);
        buff.writeInt(0); // [compatibility, unused]
        WindowEncoder.INSTANCE.encode(value.window(), ctx);
        buff.writeFloat64(value.adjustment());
        buff.writeFloat64(value.cost());
        buff.writeFloat64(value.byteHours());
        buff.writeFloat64(value.local());
        if (value.breakdown() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(0); // [compatibility, unused]
            BreakdownEncoder.INSTANCE.encode(value.breakdown(), ctx);
        }
    }
}
