////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import com.bingen.GoTime;
import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generated binary decoder for {@link Disk}.
 */
public final class DiskDecoder implements BinDecoder<Disk> {

    public static final DiskDecoder INSTANCE = new DiskDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link Disk} from a standalone byte array. 
     */
    public static Disk fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link Disk} read incrementally from a stream. 
     */
    public static Disk fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public Disk decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding Disk: expected " + VERSION + " or less, got " + version);
        }

        Disk.Builder builder = Disk.builder();
        Map<String, String> v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            int v1 = buff.readInt(); // map length
            v0 = new LinkedHashMap<>(v1);
            for (int v2 = 0; v2 < v1; v2++) {
                String v3;
                if (ctx.isStringTable()) {
                    v3 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v3 = buff.readString(); // read string
                }
                String v4;
                if (ctx.isStringTable()) {
                    v4 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v4 = buff.readString(); // read string
                }
                v0.put(v3, v4);
            }
        }
        builder.labels(v0);
        AssetProperties v5;
        if (buff.readUInt8() == 0) {
            v5 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v5 = AssetPropertiesDecoder.INSTANCE.decode(ctx);
        }
        builder.properties(v5);
        OffsetDateTime v6;
        v6 = GoTime.decode(buff);
        builder.start(v6);
        OffsetDateTime v7;
        v7 = GoTime.decode(buff);
        builder.end(v7);
        Window v8;
        buff.readInt(); // [compatibility, unused]
        v8 = WindowDecoder.INSTANCE.decode(ctx);
        builder.window(v8);
        double v9;
        v9 = buff.readFloat64();
        builder.adjustment(v9);
        double v10;
        v10 = buff.readFloat64();
        builder.cost(v10);
        double v11;
        v11 = buff.readFloat64();
        builder.byteHours(v11);
        double v12;
        v12 = buff.readFloat64();
        builder.local(v12);
        Breakdown v13;
        if (buff.readUInt8() == 0) {
            v13 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v13 = BreakdownDecoder.INSTANCE.decode(ctx);
        }
        builder.breakdown(v13);
        Disk result = builder.build();
        return result;
    }
}
