////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Generated data type for the {@code Disk} go struct.
 */
public record Disk(Map<String, String> labels, AssetProperties properties, OffsetDateTime start, OffsetDateTime end, Window window, double adjustment, double cost, double byteHours, double local, Breakdown breakdown) implements Asset {

    /** Creates a new builder for {@link Disk}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Mutable builder the decoder uses to accumulate fields and apply defaults. */
    public static final class Builder {
        private Map<String, String> labels;
        private AssetProperties properties;
        private OffsetDateTime start;
        private OffsetDateTime end;
        private Window window;
        private double adjustment;
        private double cost;
        private double byteHours;
        private double local;
        private Breakdown breakdown;
        public Builder labels(Map<String, String> labels) {
            this.labels = labels;
            return this;
        }
        public Builder properties(AssetProperties properties) {
            this.properties = properties;
            return this;
        }
        public Builder start(OffsetDateTime start) {
            this.start = start;
            return this;
        }
        public Builder end(OffsetDateTime end) {
            this.end = end;
            return this;
        }
        public Builder window(Window window) {
            this.window = window;
            return this;
        }
        public Builder adjustment(double adjustment) {
            this.adjustment = adjustment;
            return this;
        }
        public Builder cost(double cost) {
            this.cost = cost;
            return this;
        }
        public Builder byteHours(double byteHours) {
            this.byteHours = byteHours;
            return this;
        }
        public Builder local(double local) {
            this.local = local;
            return this;
        }
        public Builder breakdown(Breakdown breakdown) {
            this.breakdown = breakdown;
            return this;
        }

        public Disk build() {
            return new Disk(labels, properties, start, end, window, adjustment, cost, byteHours, local, breakdown);
        }
    }
}
