////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import com.bingen.GoTime;
import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generated binary decoder for {@link LoadBalancer}.
 */
public final class LoadBalancerDecoder implements BinDecoder<LoadBalancer> {

    public static final LoadBalancerDecoder INSTANCE = new LoadBalancerDecoder();

    private static final int VERSION = 16;

    /** Decodes a {@link LoadBalancer} from a standalone byte array. */
    public static LoadBalancer fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** Decodes a {@link LoadBalancer} read incrementally from a stream. */
    public static LoadBalancer fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public LoadBalancer decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding LoadBalancer: expected " + VERSION + " or less, got " + version);
        }

        LoadBalancer.Builder builder = LoadBalancer.builder();
        AssetProperties v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v0 = AssetPropertiesDecoder.INSTANCE.decode(ctx);
        }
        builder.properties(v0);
        Map<String, String> v1;
        if (buff.readUInt8() == 0) {
            v1 = null;
        } else {
            int v2 = buff.readInt(); // map length
            v1 = new LinkedHashMap<>(v2);
            for (int v3 = 0; v3 < v2; v3++) {
                String v4;
                if (ctx.isStringTable()) {
                    v4 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v4 = buff.readString(); // read string
                }
                String v5;
                if (ctx.isStringTable()) {
                    v5 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v5 = buff.readString(); // read string
                }
                v1.put(v4, v5);
            }
        }
        builder.labels(v1);
        OffsetDateTime v6;
        v6 = GoTime.decode(buff);
        builder.start(v6);
        OffsetDateTime v7;
        v7 = GoTime.decode(buff);
        builder.end(v7);
        Window v8;
        buff.readInt(); // [compatibility, unused]
        v8 = WindowDecoder.INSTANCE.decode(ctx);
        builder.window(v8);
        double v9;
        v9 = buff.readFloat64();
        builder.adjustment(v9);
        double v10;
        v10 = buff.readFloat64();
        builder.cost(v10);
        LoadBalancer result = builder.build();
        return result;
    }
}
