////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;
import com.bingen.GoTime;
import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Generated binary encoder for {@link Node}.
 */
public final class NodeEncoder implements BinEncoder<Node> {

    public static final NodeEncoder INSTANCE = new NodeEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** Encodes {@code value} to a standalone byte array. */
    public static byte[] toBytes(Node value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(Node value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (value.properties() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(0); // [compatibility, unused]
            AssetPropertiesEncoder.INSTANCE.encode(value.properties(), ctx);
        }
        if (value.labels() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(value.labels().size()); // map length
            for (Map.Entry<String, String> v0 : value.labels().entrySet()) {
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v0.getKey())); // string table index
                } else {
                    buff.writeString(v0.getKey()); // string
                }
                if (ctx.isStringTable()) {
                    buff.writeInt(ctx.table().addOrGet(v0.getValue())); // string table index
                } else {
                    buff.writeString(v0.getValue()); // string
                }
            }
        }
        GoTime.encode(value.start(), buff);
        GoTime.encode(value.end(), buff);
        buff.writeInt(0); // [compatibility, unused]
        WindowEncoder.INSTANCE.encode(value.window(), ctx);
        buff.writeFloat64(value.adjustment());
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.nodeType())); // string table index
        } else {
            buff.writeString(value.nodeType()); // string
        }
        buff.writeFloat64(value.cPUCoreHours());
        buff.writeFloat64(value.rAMByteHours());
        buff.writeFloat64(value.gPUHours());
        if (value.cPUBreakdown() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(0); // [compatibility, unused]
            BreakdownEncoder.INSTANCE.encode(value.cPUBreakdown(), ctx);
        }
        if (value.rAMBreakdown() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            buff.writeInt(0); // [compatibility, unused]
            BreakdownEncoder.INSTANCE.encode(value.rAMBreakdown(), ctx);
        }
        buff.writeFloat64(value.cPUCost());
        buff.writeFloat64(value.gPUCost());
        buff.writeFloat64(value.gPUCount());
        buff.writeFloat64(value.rAMCost());
        buff.writeFloat64(value.discount());
        buff.writeFloat64(value.preemptible());
    }
}
