////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Generated data type for the {@code Node} go struct.
 */
public record Node(AssetProperties properties, Map<String, String> labels, OffsetDateTime start, OffsetDateTime end, Window window, double adjustment, String nodeType, double cPUCoreHours, double rAMByteHours, double gPUHours, Breakdown cPUBreakdown, Breakdown rAMBreakdown, double cPUCost, double gPUCost, double gPUCount, double rAMCost, double discount, double preemptible) implements Asset {

    /** 
     * Creates a new builder for {@link Node}. 
     */
    public static Builder builder() {
        return new Builder();
    }

    /** 
     * Mutable builder the decoder uses to accumulate fields and apply defaults. 
     */
    public static final class Builder {
        private AssetProperties properties;
        private Map<String, String> labels;
        private OffsetDateTime start;
        private OffsetDateTime end;
        private Window window;
        private double adjustment;
        private String nodeType;
        private double cPUCoreHours;
        private double rAMByteHours;
        private double gPUHours;
        private Breakdown cPUBreakdown;
        private Breakdown rAMBreakdown;
        private double cPUCost;
        private double gPUCost;
        private double gPUCount;
        private double rAMCost;
        private double discount;
        private double preemptible;
        public Builder properties(AssetProperties properties) {
            this.properties = properties;
            return this;
        }
        public Builder labels(Map<String, String> labels) {
            this.labels = labels;
            return this;
        }
        public Builder start(OffsetDateTime start) {
            this.start = start;
            return this;
        }
        public Builder end(OffsetDateTime end) {
            this.end = end;
            return this;
        }
        public Builder window(Window window) {
            this.window = window;
            return this;
        }
        public Builder adjustment(double adjustment) {
            this.adjustment = adjustment;
            return this;
        }
        public Builder nodeType(String nodeType) {
            this.nodeType = nodeType;
            return this;
        }
        public Builder cPUCoreHours(double cPUCoreHours) {
            this.cPUCoreHours = cPUCoreHours;
            return this;
        }
        public Builder rAMByteHours(double rAMByteHours) {
            this.rAMByteHours = rAMByteHours;
            return this;
        }
        public Builder gPUHours(double gPUHours) {
            this.gPUHours = gPUHours;
            return this;
        }
        public Builder cPUBreakdown(Breakdown cPUBreakdown) {
            this.cPUBreakdown = cPUBreakdown;
            return this;
        }
        public Builder rAMBreakdown(Breakdown rAMBreakdown) {
            this.rAMBreakdown = rAMBreakdown;
            return this;
        }
        public Builder cPUCost(double cPUCost) {
            this.cPUCost = cPUCost;
            return this;
        }
        public Builder gPUCost(double gPUCost) {
            this.gPUCost = gPUCost;
            return this;
        }
        public Builder gPUCount(double gPUCount) {
            this.gPUCount = gPUCount;
            return this;
        }
        public Builder rAMCost(double rAMCost) {
            this.rAMCost = rAMCost;
            return this;
        }
        public Builder discount(double discount) {
            this.discount = discount;
            return this;
        }
        public Builder preemptible(double preemptible) {
            this.preemptible = preemptible;
            return this;
        }

        public Node build() {
            return new Node(properties, labels, start, end, window, adjustment, nodeType, cPUCoreHours, rAMByteHours, gPUHours, cPUBreakdown, rAMBreakdown, cPUCost, gPUCost, gPUCount, rAMCost, discount, preemptible);
        }
    }
}
