////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import com.bingen.GoTime;
import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generated binary decoder for {@link Node}.
 */
public final class NodeDecoder implements BinDecoder<Node> {

    public static final NodeDecoder INSTANCE = new NodeDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link Node} from a standalone byte array. 
     */
    public static Node fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link Node} read incrementally from a stream. 
     */
    public static Node fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public Node decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding Node: expected " + VERSION + " or less, got " + version);
        }

        Node.Builder builder = Node.builder();
        AssetProperties v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v0 = AssetPropertiesDecoder.INSTANCE.decode(ctx);
        }
        builder.properties(v0);
        Map<String, String> v1;
        if (buff.readUInt8() == 0) {
            v1 = null;
        } else {
            int v2 = buff.readInt(); // map length
            v1 = new LinkedHashMap<>(v2);
            for (int v3 = 0; v3 < v2; v3++) {
                String v4;
                if (ctx.isStringTable()) {
                    v4 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v4 = buff.readString(); // read string
                }
                String v5;
                if (ctx.isStringTable()) {
                    v5 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v5 = buff.readString(); // read string
                }
                v1.put(v4, v5);
            }
        }
        builder.labels(v1);
        OffsetDateTime v6;
        v6 = GoTime.decode(buff);
        builder.start(v6);
        OffsetDateTime v7;
        v7 = GoTime.decode(buff);
        builder.end(v7);
        Window v8;
        buff.readInt(); // [compatibility, unused]
        v8 = WindowDecoder.INSTANCE.decode(ctx);
        builder.window(v8);
        double v9;
        v9 = buff.readFloat64();
        builder.adjustment(v9);
        String v10;
        if (ctx.isStringTable()) {
            v10 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v10 = buff.readString(); // read string
        }
        builder.nodeType(v10);
        double v11;
        v11 = buff.readFloat64();
        builder.cPUCoreHours(v11);
        double v12;
        v12 = buff.readFloat64();
        builder.rAMByteHours(v12);
        double v13;
        v13 = buff.readFloat64();
        builder.gPUHours(v13);
        Breakdown v14;
        if (buff.readUInt8() == 0) {
            v14 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v14 = BreakdownDecoder.INSTANCE.decode(ctx);
        }
        builder.cPUBreakdown(v14);
        Breakdown v15;
        if (buff.readUInt8() == 0) {
            v15 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v15 = BreakdownDecoder.INSTANCE.decode(ctx);
        }
        builder.rAMBreakdown(v15);
        double v16;
        v16 = buff.readFloat64();
        builder.cPUCost(v16);
        double v17;
        v17 = buff.readFloat64();
        builder.gPUCost(v17);
        double v18;
        v18 = buff.readFloat64();
        builder.gPUCount(v18);
        double v19;
        v19 = buff.readFloat64();
        builder.rAMCost(v19);
        double v20;
        v20 = buff.readFloat64();
        builder.discount(v20);
        double v21;
        v21 = buff.readFloat64();
        builder.preemptible(v21);
        Node result = builder.build();
        return result;
    }
}
