////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;

/**
 * Generated binary decoder for {@link PVAllocation}.
 */
public final class PVAllocationDecoder implements BinDecoder<PVAllocation> {

    public static final PVAllocationDecoder INSTANCE = new PVAllocationDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link PVAllocation} from a standalone byte array. 
     */
    public static PVAllocation fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link PVAllocation} read incrementally from a stream. 
     */
    public static PVAllocation fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public PVAllocation decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding PVAllocation: expected " + VERSION + " or less, got " + version);
        }

        PVAllocation.Builder builder = PVAllocation.builder();
        double v0;
        v0 = buff.readFloat64();
        builder.byteHours(v0);
        double v1;
        v1 = buff.readFloat64();
        builder.cost(v1);
        PVAllocation result = builder.build();
        return result;
    }
}
