////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;


/**
 * Generated data type for the {@code PVAllocation} go struct.
 */
public record PVAllocation(double byteHours, double cost) {

    /** 
     * Creates a new builder for {@link PVAllocation}. 
     */
    public static Builder builder() {
        return new Builder();
    }

    /** 
     * Mutable builder the decoder uses to accumulate fields and apply defaults. 
     */
    public static final class Builder {
        private double byteHours;
        private double cost;
        public Builder byteHours(double byteHours) {
            this.byteHours = byteHours;
            return this;
        }
        public Builder cost(double cost) {
            this.cost = cost;
            return this;
        }

        public PVAllocation build() {
            return new PVAllocation(byteHours, cost);
        }
    }
}
