////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;


/**
 * Generated data type for the {@code PVKey} go struct.
 */
public record PVKey(String cluster, String name) {

    /** 
     * Creates a new builder for {@link PVKey}. 
     */
    public static Builder builder() {
        return new Builder();
    }

    /** 
     * Mutable builder the decoder uses to accumulate fields and apply defaults. 
     */
    public static final class Builder {
        private String cluster;
        private String name;
        public Builder cluster(String cluster) {
            this.cluster = cluster;
            return this;
        }
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public PVKey build() {
            return new PVKey(cluster, name);
        }
    }
}
