////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;

/**
 * Generated binary encoder for {@link PVKey}.
 */
public final class PVKeyEncoder implements BinEncoder<PVKey> {

    public static final PVKeyEncoder INSTANCE = new PVKeyEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** 
     * Encodes {@code value} to a standalone byte array. 
     */
    public static byte[] toBytes(PVKey value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(PVKey value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.cluster())); // string table index
        } else {
            buff.writeString(value.cluster()); // string
        }
        if (ctx.isStringTable()) {
            buff.writeInt(ctx.table().addOrGet(value.name())); // string table index
        } else {
            buff.writeString(value.name()); // string
        }
    }
}
