////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;

/**
 * Generated binary decoder for {@link PVKey}.
 */
public final class PVKeyDecoder implements BinDecoder<PVKey> {

    public static final PVKeyDecoder INSTANCE = new PVKeyDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link PVKey} from a standalone byte array. 
     */
    public static PVKey fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link PVKey} read incrementally from a stream. 
     */
    public static PVKey fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public PVKey decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding PVKey: expected " + VERSION + " or less, got " + version);
        }

        PVKey.Builder builder = PVKey.builder();
        String v0;
        if (ctx.isStringTable()) {
            v0 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v0 = buff.readString(); // read string
        }
        builder.cluster(v0);
        String v1;
        if (ctx.isStringTable()) {
            v1 = ctx.table().at(buff.readInt()); // string table index
        } else {
            v1 = buff.readString(); // read string
        }
        builder.name(v1);
        PVKey result = builder.build();
        return result;
    }
}
