////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;


/**
 * Generated data type for the {@code RawAllocationOnlyData} go struct.
 */
public record RawAllocationOnlyData(double cPUCoreUsageMax, double rAMBytesUsageMax) {

    /** Creates a new builder for {@link RawAllocationOnlyData}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Mutable builder the decoder uses to accumulate fields and apply defaults. */
    public static final class Builder {
        private double cPUCoreUsageMax;
        private double rAMBytesUsageMax;
        public Builder cPUCoreUsageMax(double cPUCoreUsageMax) {
            this.cPUCoreUsageMax = cPUCoreUsageMax;
            return this;
        }
        public Builder rAMBytesUsageMax(double rAMBytesUsageMax) {
            this.rAMBytesUsageMax = rAMBytesUsageMax;
            return this;
        }

        public RawAllocationOnlyData build() {
            return new RawAllocationOnlyData(cPUCoreUsageMax, rAMBytesUsageMax);
        }
    }
}
