////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;

/**
 * Generated binary decoder for {@link RawAllocationOnlyData}.
 */
public final class RawAllocationOnlyDataDecoder implements BinDecoder<RawAllocationOnlyData> {

    public static final RawAllocationOnlyDataDecoder INSTANCE = new RawAllocationOnlyDataDecoder();

    private static final int VERSION = 16;

    /** Decodes a {@link RawAllocationOnlyData} from a standalone byte array. */
    public static RawAllocationOnlyData fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** Decodes a {@link RawAllocationOnlyData} read incrementally from a stream. */
    public static RawAllocationOnlyData fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public RawAllocationOnlyData decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding RawAllocationOnlyData: expected " + VERSION + " or less, got " + version);
        }

        RawAllocationOnlyData.Builder builder = RawAllocationOnlyData.builder();
        double v0;
        v0 = buff.readFloat64();
        builder.cPUCoreUsageMax(v0);
        double v1;
        v1 = buff.readFloat64();
        builder.rAMBytesUsageMax(v1);
        RawAllocationOnlyData result = builder.build();
        return result;
    }
}
