////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Generated binary decoder for {@link SharedAsset}.
 */
public final class SharedAssetDecoder implements BinDecoder<SharedAsset> {

    public static final SharedAssetDecoder INSTANCE = new SharedAssetDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link SharedAsset} from a standalone byte array. 
     */
    public static SharedAsset fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link SharedAsset} read incrementally from a stream. 
     */
    public static SharedAsset fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public SharedAsset decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding SharedAsset: expected " + VERSION + " or less, got " + version);
        }

        SharedAsset.Builder builder = SharedAsset.builder();
        AssetProperties v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            buff.readInt(); // [compatibility, unused]
            v0 = AssetPropertiesDecoder.INSTANCE.decode(ctx);
        }
        builder.properties(v0);
        Map<String, String> v1;
        if (buff.readUInt8() == 0) {
            v1 = null;
        } else {
            int v2 = buff.readInt(); // map length
            v1 = new LinkedHashMap<>(v2);
            for (int v3 = 0; v3 < v2; v3++) {
                String v4;
                if (ctx.isStringTable()) {
                    v4 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v4 = buff.readString(); // read string
                }
                String v5;
                if (ctx.isStringTable()) {
                    v5 = ctx.table().at(buff.readInt()); // string table index
                } else {
                    v5 = buff.readString(); // read string
                }
                v1.put(v4, v5);
            }
        }
        builder.labels(v1);
        Window v6;
        buff.readInt(); // [compatibility, unused]
        v6 = WindowDecoder.INSTANCE.decode(ctx);
        builder.window(v6);
        double v7;
        v7 = buff.readFloat64();
        builder.cost(v7);
        SharedAsset result = builder.build();
        return result;
    }
}
