////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.util.Map;

/**
 * Generated data type for the {@code SharedAsset} go struct.
 */
public record SharedAsset(AssetProperties properties, Map<String, String> labels, Window window, double cost) implements Asset {

    /** Creates a new builder for {@link SharedAsset}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Mutable builder the decoder uses to accumulate fields and apply defaults. */
    public static final class Builder {
        private AssetProperties properties;
        private Map<String, String> labels;
        private Window window;
        private double cost;
        public Builder properties(AssetProperties properties) {
            this.properties = properties;
            return this;
        }
        public Builder labels(Map<String, String> labels) {
            this.labels = labels;
            return this;
        }
        public Builder window(Window window) {
            this.window = window;
            return this;
        }
        public Builder cost(double cost) {
            this.cost = cost;
            return this;
        }

        public SharedAsset build() {
            return new SharedAsset(properties, labels, window, cost);
        }
    }
}
