////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.BinEncoder;
import com.bingen.DecodingContext;
import com.bingen.EncodingContext;
import java.util.HashMap;
import java.util.Map;

/**
 * Maps go wire type strings to the generated codecs for interface dispatch,
 * replacing go's reflection-based type map.
 */
public final class TypeRegistry {

    private static final Map<String, BinDecoder<?>> DECODERS = new HashMap<>();
    private static final Map<Class<?>, String> WIRE_NAMES = new HashMap<>();
    private static final Map<Class<?>, BinEncoder<?>> ENCODERS = new HashMap<>();

    static {
        register("*github.com/opencost/bingen/tests/opencost.Allocation", Allocation.class, AllocationEncoder.INSTANCE, AllocationDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.AllocationProperties", AllocationProperties.class, AllocationPropertiesEncoder.INSTANCE, AllocationPropertiesDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.AllocationSet", AllocationSet.class, AllocationSetEncoder.INSTANCE, AllocationSetDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.AllocationSetRange", AllocationSetRange.class, AllocationSetRangeEncoder.INSTANCE, AllocationSetRangeDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.Any", Any.class, AnyEncoder.INSTANCE, AnyDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.AssetProperties", AssetProperties.class, AssetPropertiesEncoder.INSTANCE, AssetPropertiesDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.AssetSet", AssetSet.class, AssetSetEncoder.INSTANCE, AssetSetDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.AssetSetRange", AssetSetRange.class, AssetSetRangeEncoder.INSTANCE, AssetSetRangeDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.Breakdown", Breakdown.class, BreakdownEncoder.INSTANCE, BreakdownDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.Cloud", Cloud.class, CloudEncoder.INSTANCE, CloudDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.ClusterManagement", ClusterManagement.class, ClusterManagementEncoder.INSTANCE, ClusterManagementDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.Disk", Disk.class, DiskEncoder.INSTANCE, DiskDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.LoadBalancer", LoadBalancer.class, LoadBalancerEncoder.INSTANCE, LoadBalancerDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.Network", Network.class, NetworkEncoder.INSTANCE, NetworkDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.Node", Node.class, NodeEncoder.INSTANCE, NodeDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.PVAllocation", PVAllocation.class, PVAllocationEncoder.INSTANCE, PVAllocationDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.PVKey", PVKey.class, PVKeyEncoder.INSTANCE, PVKeyDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.RawAllocationOnlyData", RawAllocationOnlyData.class, RawAllocationOnlyDataEncoder.INSTANCE, RawAllocationOnlyDataDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.SharedAsset", SharedAsset.class, SharedAssetEncoder.INSTANCE, SharedAssetDecoder.INSTANCE);
        register("*github.com/opencost/bingen/tests/opencost.Window", Window.class, WindowEncoder.INSTANCE, WindowDecoder.INSTANCE);
    }

    private TypeRegistry() {
    }

    private static <T> void register(String wire, Class<T> cls, BinEncoder<T> enc, BinDecoder<T> dec) {
        DECODERS.put(wire, dec);
        DECODERS.put(stripStar(wire), dec);
        WIRE_NAMES.put(cls, wire);
        ENCODERS.put(cls, enc);
    }

    /** Writes the wire type string + compatibility marker, then the value body. */
    @SuppressWarnings("unchecked")
    public static void encode(Object value, EncodingContext ctx) {
        String wire = WIRE_NAMES.get(value.getClass());
        if (wire == null) {
            throw new IllegalArgumentException("bingen: unregistered interface type " + value.getClass().getName());
        }
        BinEncoder<Object> enc = (BinEncoder<Object>) ENCODERS.get(value.getClass());
        ctx.buffer().writeString(wire);
        ctx.buffer().writeInt(0); // [compatibility, unused]
        enc.encode(value, ctx);
    }

    /** Reads the compatibility marker, then decodes the concrete value. */
    public static Object decode(String wire, DecodingContext ctx) {
        BinDecoder<?> dec = DECODERS.get(wire);
        if (dec == null) {
            dec = DECODERS.get(stripStar(wire));
        }
        if (dec == null) {
            throw new IllegalArgumentException("bingen: unknown wire type " + wire);
        }
        ctx.buffer().readInt(); // [compatibility, unused]
        return dec.decode(ctx);
    }

    private static String stripStar(String s) {
        return s.startsWith("*") ? s.substring(1) : s;
    }
}
