////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinEncoder;
import com.bingen.EncodingContext;
import com.bingen.WriteBuffer;
import com.bingen.GoTime;
import java.time.OffsetDateTime;

/**
 * Generated binary encoder for {@link Window}.
 */
public final class WindowEncoder implements BinEncoder<Window> {

    public static final WindowEncoder INSTANCE = new WindowEncoder();

    private static final int VERSION = 16;
    private static final boolean STRING_TABLE = false;

    /** 
     * Encodes {@code value} to a standalone byte array. 
     */
    public static byte[] toBytes(Window value) {
        EncodingContext ctx = STRING_TABLE ? EncodingContext.withStringTable() : EncodingContext.create();
        INSTANCE.encode(value, ctx);
        return ctx.toBytes();
    }

    @Override
    public void encode(Window value, EncodingContext ctx) {
        WriteBuffer buff = ctx.buffer();
        buff.writeUInt8(VERSION); // version
        if (value.start() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            GoTime.encode(value.start(), buff);
        }
        if (value.end() == null) {
            buff.writeUInt8(0); // write nil byte
        } else {
            buff.writeUInt8(1); // write non-nil byte
            GoTime.encode(value.end(), buff);
        }
    }
}
