////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import java.time.OffsetDateTime;

/**
 * Generated data type for the {@code Window} go struct.
 */
public record Window(OffsetDateTime start, OffsetDateTime end) {

    /** Creates a new builder for {@link Window}. */
    public static Builder builder() {
        return new Builder();
    }

    /** Mutable builder the decoder uses to accumulate fields and apply defaults. */
    public static final class Builder {
        private OffsetDateTime start;
        private OffsetDateTime end;
        public Builder start(OffsetDateTime start) {
            this.start = start;
            return this;
        }
        public Builder end(OffsetDateTime end) {
            this.end = end;
            return this;
        }

        public Window build() {
            return new Window(start, end);
        }
    }
}
