////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package com.opencost.opencost;

import com.bingen.BinDecoder;
import com.bingen.DecodingContext;
import com.bingen.ReadBuffer;
import java.io.InputStream;
import com.bingen.GoTime;
import java.time.OffsetDateTime;

/**
 * Generated binary decoder for {@link Window}.
 */
public final class WindowDecoder implements BinDecoder<Window> {

    public static final WindowDecoder INSTANCE = new WindowDecoder();

    private static final int VERSION = 16;

    /** 
     * Decodes a {@link Window} from a standalone byte array. 
     */
    public static Window fromBytes(byte[] data) {
        return INSTANCE.decode(DecodingContext.fromBytes(data));
    }

    /** 
     * Decodes a {@link Window} read incrementally from a stream. 
     */
    public static Window fromStream(InputStream in) {
        return INSTANCE.decode(DecodingContext.fromStream(in));
    }

    @Override
    public Window decode(DecodingContext ctx) {
        ReadBuffer buff = ctx.buffer();
        int version = buff.readUInt8();
        if (version > VERSION) {
            throw new IllegalStateException(
                "Invalid version decoding Window: expected " + VERSION + " or less, got " + version);
        }

        Window.Builder builder = Window.builder();
        OffsetDateTime v0;
        if (buff.readUInt8() == 0) {
            v0 = null;
        } else {
            v0 = GoTime.decode(buff);
        }
        builder.start(v0);
        OffsetDateTime v1;
        if (buff.readUInt8() == 0) {
            v1 = null;
        } else {
            v1 = GoTime.decode(buff);
        }
        builder.end(v1);
        Window result = builder.build();
        return result;
    }
}
