////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package containerv2

import (
	"fmt"
	"io"
	"iter"
	"os"
	"reflect"
	"strings"
	"sync"

	bstream "github.com/opencost/bingen/pkg/stream"
	stringtable "github.com/opencost/bingen/pkg/table"
	util "github.com/opencost/bingen/pkg/util"
)

const (
	// GeneratorPackageName is the package the generator is targetting
	GeneratorPackageName string = "containerv2"

	// ContainerExampleCodecVersion is used for any resources listed in the ContainerExample version set
	ContainerExampleCodecVersion uint8 = 2
)

//--------------------------------------------------------------------------
//  Configuration
//--------------------------------------------------------------------------

var (
	bingenConfigLock sync.RWMutex
	bingenConfig     *BingenConfiguration = DefaultBingenConfiguration()
)

// BingenConfiguration is used to set any custom configuration in the way files are encoded
// or decoded.
type BingenConfiguration struct {
	// FileBackedStringTableEnabled enables the use of file-backed string tables for streaming
	// bingen decoding.
	FileBackedStringTableEnabled bool

	// FileBackedStringTableDir is the directory to write the string table files for reading.
	FileBackedStringTableDir string

	// FileBackedStringTableMemoMaxBytes limits in-memory memoization for file-backed table lookups.
	// 0 disables memoization.
	FileBackedStringTableMemoMaxBytes int64
}

// DefaultBingenConfiguration creates the default implementation of the bingen configuration
// and returns it.
func DefaultBingenConfiguration() *BingenConfiguration {
	return &BingenConfiguration{
		FileBackedStringTableEnabled:      false,
		FileBackedStringTableDir:          os.TempDir(),
		FileBackedStringTableMemoMaxBytes: 0,
	}
}

// ConfigureBingen accepts a new *BingenConfiguration instance which updates the internal decoder
// and encoder behavior.
func ConfigureBingen(config *BingenConfiguration) {
	bingenConfigLock.Lock()
	defer bingenConfigLock.Unlock()

	if config == nil {
		config = DefaultBingenConfiguration()
	}
	bingenConfig = config
}

// IsBingenFileBackedStringTableEnabled accessor for file backed string table configuration
func IsBingenFileBackedStringTableEnabled() bool {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableEnabled
}

// BingenFileBackedStringTableDir returns the directory configured for file backed string tables.
func BingenFileBackedStringTableDir() string {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableDir
}

// BingenFileBackedStringTableMemoMaxBytes returns the maximum bytes used for file-backed memo cache.
func BingenFileBackedStringTableMemoMaxBytes() int64 {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableMemoMaxBytes
}

//--------------------------------------------------------------------------
//  Type Map
//--------------------------------------------------------------------------

// Generated type map for resolving interface implementations to to concrete types
var typeMap map[string]reflect.Type = map[string]reflect.Type{
	"Container": reflect.TypeFor[Container](),
}

//--------------------------------------------------------------------------
//  Type Helpers
//--------------------------------------------------------------------------

// isBinaryTag returns true when the first bytes in the provided binary matches the tag
func isBinaryTag(data []byte, tag string) bool {
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// isReaderBinaryTag is used to peek the header for an io.Reader Buffer
func isReaderBinaryTag(buff *util.Buffer, tag string) bool {
	data, err := buff.Peek(len(tag))
	if err != nil && err != io.EOF {
		panic(fmt.Sprintf("called Peek() on a non buffered reader: %s", err))
	}
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// typeToString determines the basic properties of the type, the qualifier, package path, and
// type name, and returns the qualified type
func typeToString(f interface{}) string {
	qual := ""
	t := reflect.TypeOf(f)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
		qual = "*"
	}

	return fmt.Sprintf("%s%s.%s", qual, t.PkgPath(), t.Name())
}

// resolveType uses the name of a type and returns the package, base type name, and whether
// or not it's a pointer.
func resolveType(t string) (pkg string, name string, isPtr bool) {
	isPtr = t[:1] == "*"
	if isPtr {
		t = t[1:]
	}

	slashIndex := strings.LastIndex(t, "/")
	if slashIndex >= 0 {
		t = t[slashIndex+1:]
	}
	parts := strings.Split(t, ".")
	if parts[0] == GeneratorPackageName {
		parts[0] = ""
	}

	pkg = parts[0]
	name = parts[1]
	return
}

//--------------------------------------------------------------------------
//  Stream Helpers
//--------------------------------------------------------------------------

// StreamFactoryFunc is an alias for a func that creates a BingenStream implementation.
type StreamFactoryFunc func(io.Reader) bstream.BingenStream

// Generated streamable factory map for finding the specific new stream methods
// by T type
var streamFactoryMap map[reflect.Type]StreamFactoryFunc = map[reflect.Type]StreamFactoryFunc{
	reflect.TypeFor[Container](): NewContainerStream,
}

// NewStreamFor accepts an io.Reader, and returns a new BingenStream for the generic T
// type provided _if_ it is a registered bingen type that is annotated as 'streamable'. See
// the streamFactoryMap for generated type listings.
func NewStreamFor[T any](reader io.Reader) (bstream.BingenStream, error) {
	typeKey := reflect.TypeFor[T]()

	factory, ok := streamFactoryMap[typeKey]
	if !ok {
		return nil, fmt.Errorf("the type: %s is not a registered bingen streamable type", typeKey.Name())
	}

	return factory(reader), nil
}

//--------------------------------------------------------------------------
//  Codec Context
//--------------------------------------------------------------------------

// EncodingContext is a context object passed to the encoders to ensure reuse of buffer
// and table data
type EncodingContext struct {
	Buffer *util.Buffer
	Table  stringtable.StringTableWriter
}

// NewEncodingContext creates a new EncodingContext instance that will create a new []byte buffer
// for writing, and return the context
func NewEncodingContext(tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: util.NewBuffer(),
		Table:  tableWriter,
	}
}

// NewEncodingContextFromWriter creates a new EncodingContext instance that will create a new Buffer
// from the provided io.Writer and StringTableWriter.
func NewEncodingContextFromWriter(writer io.Writer, tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: util.NewBufferFromWriter(writer),
		Table:  tableWriter,
	}
}

// NewEncodingContextFromBuffer creates a new EncodingContext instance that will leverage an existing
// Buffer and StringTableWriter.
func NewEncodingContextFromBuffer(buffer *util.Buffer, tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: buffer,
		Table:  tableWriter,
	}
}

// ToBytes returns the encoded string table bytes (if applicable) combined with the encoded buffer bytes. If
// a string table is being used, the string table bytes will be written first to ensure correct ordering for
// decoding.
func (ec *EncodingContext) ToBytes() []byte {
	encBytes := ec.Buffer.Bytes()
	if ec.Table != nil {
		buff := util.NewBuffer()
		ec.Table.WriteTo(buff)
		buff.WriteBytes(encBytes)
		return buff.Bytes()
	}

	return encBytes
}

// IsStringTable returns true if the table is available
func (ec *EncodingContext) IsStringTable() bool {
	return ec.Table != nil
}

// DecodingContext is a context object passed to the decoders to ensure parent objects
// reuse as much data as possible
type DecodingContext struct {
	Buffer *util.Buffer
	Table  stringtable.StringTableReader
}

// NewDecodingContextFromBytes creates a new DecodingContext instance using an byte slice
func NewDecodingContextFromBytes(data []byte) *DecodingContext {
	var table stringtable.StringTableReader

	buff := util.NewBufferFromBytes(data)

	// string table header validation
	if isBinaryTag(data, stringtable.BinaryTagStringTable) {
		buff.ReadBytes(len(stringtable.BinaryTagStringTable)) // strip tag length

		// always use a slice string table with a byte array since the
		// data is already in memory
		table = stringtable.NewSliceStringTableReaderFrom(buff)
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}
}

// NewDecodingContextFromReader creates a new DecodingContext instance using an io.Reader
// implementation
func NewDecodingContextFromReader(reader io.Reader) *DecodingContext {
	var table stringtable.StringTableReader

	buff := util.NewBufferFromReader(reader)

	if isReaderBinaryTag(buff, stringtable.BinaryTagStringTable) {
		buff.ReadBytes(len(stringtable.BinaryTagStringTable)) // strip tag length

		// create correct string table implementation
		if IsBingenFileBackedStringTableEnabled() {
			table = stringtable.NewFileStringTableReaderFrom(buff, BingenFileBackedStringTableDir(), GeneratorPackageName, BingenFileBackedStringTableMemoMaxBytes())
		} else {
			table = stringtable.NewSliceStringTableReaderFrom(buff)
		}
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}
}

// IsStringTable returns true if the table is available
func (dc *DecodingContext) IsStringTable() bool {
	return dc.Table != nil && dc.Table.Len() > 0
}

// Close will ensure that any string table resources and buffer resources are
// cleaned up.
func (dc *DecodingContext) Close() {
	if dc.Table != nil {
		_ = dc.Table.Close()
		dc.Table = nil
	}
}

//--------------------------------------------------------------------------
//  Binary Codec
//--------------------------------------------------------------------------

// BinEncoder is an encoding interface which defines a context based marshal contract.
type BinEncoder interface {
	MarshalBinaryWithContext(*EncodingContext) error
}

// BinDecoder is a decoding interface which defines a context based unmarshal contract.
type BinDecoder interface {
	UnmarshalBinaryWithContext(*DecodingContext) error
}

//--------------------------------------------------------------------------
//  Container
//--------------------------------------------------------------------------

// MarshalBinary serializes the internal properties of this Container instance
// into a byte array
func (target *Container) MarshalBinary() (data []byte, err error) {
	ctx := NewEncodingContext(nil)

	e := target.MarshalBinaryWithContext(ctx)
	if e != nil {
		return nil, e
	}

	return ctx.ToBytes(), nil
}

// MarshalBinary serializes the internal properties of this Container instance
// into an io.Writer.
func (target *Container) MarshalBinaryTo(writer io.Writer) error {
	buff := util.NewBufferFromWriter(writer)
	defer buff.Flush()

	ctx := NewEncodingContextFromBuffer(buff, nil)

	return target.MarshalBinaryWithContext(ctx)
}

// MarshalBinaryWithContext serializes the internal properties of this Container instance
// into a byte array leveraging a predefined context.
func (target *Container) MarshalBinaryWithContext(ctx *EncodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	buff.WriteUInt8(ContainerExampleCodecVersion) // version

	if ctx.IsStringTable() {
		a := ctx.Table.AddOrGet(target.Name)
		buff.WriteInt(a) // write table index
	} else {
		buff.WriteString(target.Name) // write string
	}

	if target.Children == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		// --- [begin][write][slice]([]string) ---
		buff.WriteInt(len(target.Children)) // slice length
		for i := range target.Children {
			if ctx.IsStringTable() {
				b := ctx.Table.AddOrGet(target.Children[i])
				buff.WriteInt(b) // write table index
			} else {
				buff.WriteString(target.Children[i]) // write string
			}

		}
		// --- [end][write][slice]([]string) ---

	}

	buff.WriteFloat64(target.oldValue) // write float64

	if target.Value == nil {
		buff.WriteUInt8(uint8(0)) // write nil byte
	} else {
		buff.WriteUInt8(uint8(1)) // write non-nil byte

		buff.WriteFloat64(*target.Value) // write float64

	}

	return nil
}

// UnmarshalBinary uses the data passed byte array to set all the internal properties of
// the Container type
func (target *Container) UnmarshalBinary(data []byte) error {
	ctx := NewDecodingContextFromBytes(data)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryFromReader uses the io.Reader data to set all the internal properties of
// the Container type
func (target *Container) UnmarshalBinaryFromReader(reader io.Reader) error {
	ctx := NewDecodingContextFromReader(reader)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryWithContext uses the context containing a string table and binary buffer to set all the internal properties of
// the Container type
func (target *Container) UnmarshalBinaryWithContext(ctx *DecodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	version := buff.ReadUInt8()

	if version > ContainerExampleCodecVersion {
		return fmt.Errorf("Invalid Version Unmarshalling Container. Expected %d or less, got %d", ContainerExampleCodecVersion, version)
	}

	var b string
	if ctx.IsStringTable() {
		c := buff.ReadInt() // read string index
		b = ctx.Table.At(c)
	} else {
		b = buff.ReadString() // read string
	}
	a := b
	target.Name = a

	if buff.ReadUInt8() == uint8(0) {
		target.Children = nil
	} else {
		// --- [begin][read][slice]([]string) ---
		e := buff.ReadInt() // slice len
		d := make([]string, e)
		for i := range e {
			var f string
			var h string
			if ctx.IsStringTable() {
				l := buff.ReadInt() // read string index
				h = ctx.Table.At(l)
			} else {
				h = buff.ReadString() // read string
			}
			g := h
			f = g

			d[i] = f
		}
		target.Children = d
		// --- [end][read][slice]([]string) ---

	}

	m := buff.ReadFloat64() // read float64
	target.oldValue = m

	// field version check
	if uint8(2) <= version {
		if buff.ReadUInt8() == uint8(0) {
			target.Value = nil
		} else {

			n := buff.ReadFloat64() // read float64
			target.Value = &n

		}

	} else {
		target.Value = nil
	}

	// execute migration func if version delta detected
	if version != ContainerExampleCodecVersion {
		migrateContainer(target, version, ContainerExampleCodecVersion)
	}

	return nil
}

//--------------------------------------------------------------------------
//  ContainerStream
//--------------------------------------------------------------------------

// ContainerStream is a single use field stream for the contents of an Container instance. Instead of creating an instance and populating
// the fields on that instance, we provide a streaming iterator which yields (BingenFieldInfo, *BingenValue) tuples for each
// streamable element. All slices and maps will be flattened one depth and each element streamed individually.
type ContainerStream struct {
	reader io.Reader
	ctx    *DecodingContext
	err    error
}

// Closes closes the internal io.Reader used to read and parse the Container fields.
// This should be called once the stream is no longer needed.
func (stream *ContainerStream) Close() {
	if closer, ok := stream.reader.(io.Closer); ok {
		closer.Close()
	}
	stream.ctx.Close()
}

// Error returns an error if one occurred during the process of streaming the Container
// This can be checked after iterating through the Stream().
func (stream *ContainerStream) Error() error {
	return stream.err
}

// NewContainerStream creates a new ContainerStream, which uses the io.Reader data to stream all internal fields of an Container instance
func NewContainerStream(reader io.Reader) bstream.BingenStream {
	ctx := NewDecodingContextFromReader(reader)

	return &ContainerStream{
		ctx:    ctx,
		reader: reader,
	}
}

// Stream returns the iterator which will stream each field of the target type.
func (stream *ContainerStream) Stream() iter.Seq2[bstream.BingenFieldInfo, *bstream.BingenValue] {
	return func(yield func(bstream.BingenFieldInfo, *bstream.BingenValue) bool) {
		var fi bstream.BingenFieldInfo

		ctx := stream.ctx
		buff := ctx.Buffer
		version := buff.ReadUInt8()

		if version > ContainerExampleCodecVersion {
			stream.err = fmt.Errorf("Invalid Version Unmarshalling Container. Expected %d or less, got %d", ContainerExampleCodecVersion, version)
			return
		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[string](),
			Name: "Name",
		}

		var a string
		var c string
		if ctx.IsStringTable() {
			d := buff.ReadInt() // read string index
			c = ctx.Table.At(d)
		} else {
			c = buff.ReadString() // read string
		}
		b := c
		a = b
		if !yield(fi, bstream.SingleV(a)) {
			return
		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[[]string](),
			Name: "Children",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			// --- [begin][read][streaming-slice]([]string) ---
			e := buff.ReadInt() // slice len
			for i := range e {

				var f string
				var h string
				if ctx.IsStringTable() {
					l := buff.ReadInt() // read string index
					h = ctx.Table.At(l)
				} else {
					h = buff.ReadString() // read string
				}
				g := h
				f = g

				if !yield(fi, bstream.PairV(i, f)) {
					return
				}
			}
			// --- [end][read][streaming-slice]([]string) ---

		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[float64](),
			Name: "oldValue",
		}

		var m float64
		n := buff.ReadFloat64() // read float64
		m = n
		if !yield(fi, bstream.SingleV(m)) {
			return
		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[*float64](),
			Name: "Value",
		}
		// field version check
		if uint8(2) <= version {

			if buff.ReadUInt8() == uint8(0) {
				if !yield(fi, nil) {
					return
				}
			} else {

				var o *float64
				p := buff.ReadFloat64() // read float64
				o = &p
				if !yield(fi, bstream.SingleV(o)) {
					return
				}

			}

		} else {

			if !yield(fi, nil) {
				return
			}
		}
	}
}
