////////////////////////////////////////////////////////////////////////////////
//
//                             DO NOT MODIFY
//
//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
//
//
//            This source file was automatically generated by bingen.
//
////////////////////////////////////////////////////////////////////////////////

package streamfeed

import (
	"fmt"
	"io"
	"iter"
	"os"
	"reflect"
	"strings"
	"sync"

	bstream "github.com/opencost/bingen/pkg/stream"
	stringtable "github.com/opencost/bingen/pkg/table"
	util "github.com/opencost/bingen/pkg/util"
)

const (
	// GeneratorPackageName is the package the generator is targetting
	GeneratorPackageName string = "streamfeed"

	// DefaultCodecVersion is used for any resources listed in the Default version set
	DefaultCodecVersion uint8 = 1
)

//--------------------------------------------------------------------------
//  Configuration
//--------------------------------------------------------------------------

var (
	bingenConfigLock sync.RWMutex
	bingenConfig     *BingenConfiguration = DefaultBingenConfiguration()
)

// BingenConfiguration is used to set any custom configuration in the way files are encoded
// or decoded.
type BingenConfiguration struct {
	// FileBackedStringTableEnabled enables the use of file-backed string tables for streaming
	// bingen decoding.
	FileBackedStringTableEnabled bool

	// FileBackedStringTableDir is the directory to write the string table files for reading.
	FileBackedStringTableDir string

	// FileBackedStringTableMemoMaxBytes limits in-memory memoization for file-backed table lookups.
	// 0 disables memoization.
	FileBackedStringTableMemoMaxBytes int64
}

// DefaultBingenConfiguration creates the default implementation of the bingen configuration
// and returns it.
func DefaultBingenConfiguration() *BingenConfiguration {
	return &BingenConfiguration{
		FileBackedStringTableEnabled:      false,
		FileBackedStringTableDir:          os.TempDir(),
		FileBackedStringTableMemoMaxBytes: 0,
	}
}

// ConfigureBingen accepts a new *BingenConfiguration instance which updates the internal decoder
// and encoder behavior.
func ConfigureBingen(config *BingenConfiguration) {
	bingenConfigLock.Lock()
	defer bingenConfigLock.Unlock()

	if config == nil {
		config = DefaultBingenConfiguration()
	}
	bingenConfig = config
}

// IsBingenFileBackedStringTableEnabled accessor for file backed string table configuration
func IsBingenFileBackedStringTableEnabled() bool {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableEnabled
}

// BingenFileBackedStringTableDir returns the directory configured for file backed string tables.
func BingenFileBackedStringTableDir() string {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableDir
}

// BingenFileBackedStringTableMemoMaxBytes returns the maximum bytes used for file-backed memo cache.
func BingenFileBackedStringTableMemoMaxBytes() int64 {
	bingenConfigLock.RLock()
	defer bingenConfigLock.RUnlock()

	return bingenConfig.FileBackedStringTableMemoMaxBytes
}

//--------------------------------------------------------------------------
//  Type Map
//--------------------------------------------------------------------------

// Generated type map for resolving interface implementations to to concrete types
var typeMap map[string]reflect.Type = map[string]reflect.Type{
	"Feed": reflect.TypeFor[Feed](),
}

//--------------------------------------------------------------------------
//  Type Helpers
//--------------------------------------------------------------------------

// isBinaryTag returns true when the first bytes in the provided binary matches the tag
func isBinaryTag(data []byte, tag string) bool {
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// isReaderBinaryTag is used to peek the header for an io.Reader Buffer
func isReaderBinaryTag(buff *util.Buffer, tag string) bool {
	data, err := buff.Peek(len(tag))
	if err != nil && err != io.EOF {
		panic(fmt.Sprintf("called Peek() on a non buffered reader: %s", err))
	}
	if len(data) < len(tag) {
		return false
	}

	return string(data[:len(tag)]) == tag
}

// typeToString determines the basic properties of the type, the qualifier, package path, and
// type name, and returns the qualified type
func typeToString(f interface{}) string {
	qual := ""
	t := reflect.TypeOf(f)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
		qual = "*"
	}

	return fmt.Sprintf("%s%s.%s", qual, t.PkgPath(), t.Name())
}

// resolveType uses the name of a type and returns the package, base type name, and whether
// or not it's a pointer.
func resolveType(t string) (pkg string, name string, isPtr bool) {
	isPtr = t[:1] == "*"
	if isPtr {
		t = t[1:]
	}

	slashIndex := strings.LastIndex(t, "/")
	if slashIndex >= 0 {
		t = t[slashIndex+1:]
	}
	parts := strings.Split(t, ".")
	if parts[0] == GeneratorPackageName {
		parts[0] = ""
	}

	pkg = parts[0]
	name = parts[1]
	return
}

//--------------------------------------------------------------------------
//  Stream Helpers
//--------------------------------------------------------------------------

// StreamFactoryFunc is an alias for a func that creates a BingenStream implementation.
type StreamFactoryFunc func(io.Reader) bstream.BingenStream

// Generated streamable factory map for finding the specific new stream methods
// by T type
var streamFactoryMap map[reflect.Type]StreamFactoryFunc = map[reflect.Type]StreamFactoryFunc{
	reflect.TypeFor[Feed](): NewFeedStream,
}

// NewStreamFor accepts an io.Reader, and returns a new BingenStream for the generic T
// type provided _if_ it is a registered bingen type that is annotated as 'streamable'. See
// the streamFactoryMap for generated type listings.
func NewStreamFor[T any](reader io.Reader) (bstream.BingenStream, error) {
	typeKey := reflect.TypeFor[T]()

	factory, ok := streamFactoryMap[typeKey]
	if !ok {
		return nil, fmt.Errorf("the type: %s is not a registered bingen streamable type", typeKey.Name())
	}

	return factory(reader), nil
}

//--------------------------------------------------------------------------
//  Codec Context
//--------------------------------------------------------------------------

// EncodingContext is a context object passed to the encoders to ensure reuse of buffer
// and table data
type EncodingContext struct {
	Buffer *util.Buffer
	Table  stringtable.StringTableWriter
}

// NewEncodingContext creates a new EncodingContext instance that will create a new []byte buffer
// for writing, and return the context
func NewEncodingContext(tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: util.NewBuffer(),
		Table:  tableWriter,
	}
}

// NewEncodingContextFromWriter creates a new EncodingContext instance that will create a new Buffer
// from the provided io.Writer and StringTableWriter.
func NewEncodingContextFromWriter(writer io.Writer, tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: util.NewBufferFromWriter(writer),
		Table:  tableWriter,
	}
}

// NewEncodingContextFromBuffer creates a new EncodingContext instance that will leverage an existing
// Buffer and StringTableWriter.
func NewEncodingContextFromBuffer(buffer *util.Buffer, tableWriter stringtable.StringTableWriter) *EncodingContext {
	return &EncodingContext{
		Buffer: buffer,
		Table:  tableWriter,
	}
}

// ToBytes returns the encoded string table bytes (if applicable) combined with the encoded buffer bytes. If
// a string table is being used, the string table bytes will be written first to ensure correct ordering for
// decoding.
func (ec *EncodingContext) ToBytes() []byte {
	encBytes := ec.Buffer.Bytes()
	if ec.Table != nil {
		buff := util.NewBuffer()
		ec.Table.WriteTo(buff)
		buff.WriteBytes(encBytes)
		return buff.Bytes()
	}

	return encBytes
}

// IsStringTable returns true if the table is available
func (ec *EncodingContext) IsStringTable() bool {
	return ec.Table != nil
}

// DecodingContext is a context object passed to the decoders to ensure parent objects
// reuse as much data as possible
type DecodingContext struct {
	Buffer *util.Buffer
	Table  stringtable.StringTableReader
}

// NewDecodingContextFromBytes creates a new DecodingContext instance using an byte slice
func NewDecodingContextFromBytes(data []byte) *DecodingContext {
	var table stringtable.StringTableReader

	buff := util.NewBufferFromBytes(data)

	// string table header validation
	if isBinaryTag(data, stringtable.BinaryTagStringTable) {
		buff.ReadBytes(len(stringtable.BinaryTagStringTable)) // strip tag length

		// always use a slice string table with a byte array since the
		// data is already in memory
		table = stringtable.NewSliceStringTableReaderFrom(buff)
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}
}

// NewDecodingContextFromReader creates a new DecodingContext instance using an io.Reader
// implementation
func NewDecodingContextFromReader(reader io.Reader) *DecodingContext {
	var table stringtable.StringTableReader

	buff := util.NewBufferFromReader(reader)

	if isReaderBinaryTag(buff, stringtable.BinaryTagStringTable) {
		buff.ReadBytes(len(stringtable.BinaryTagStringTable)) // strip tag length

		// create correct string table implementation
		if IsBingenFileBackedStringTableEnabled() {
			table = stringtable.NewFileStringTableReaderFrom(buff, BingenFileBackedStringTableDir(), GeneratorPackageName, BingenFileBackedStringTableMemoMaxBytes())
		} else {
			table = stringtable.NewSliceStringTableReaderFrom(buff)
		}
	}

	return &DecodingContext{
		Buffer: buff,
		Table:  table,
	}
}

// IsStringTable returns true if the table is available
func (dc *DecodingContext) IsStringTable() bool {
	return dc.Table != nil && dc.Table.Len() > 0
}

// Close will ensure that any string table resources and buffer resources are
// cleaned up.
func (dc *DecodingContext) Close() {
	if dc.Table != nil {
		_ = dc.Table.Close()
		dc.Table = nil
	}
}

//--------------------------------------------------------------------------
//  Binary Codec
//--------------------------------------------------------------------------

// BinEncoder is an encoding interface which defines a context based marshal contract.
type BinEncoder interface {
	MarshalBinaryWithContext(*EncodingContext) error
}

// BinDecoder is a decoding interface which defines a context based unmarshal contract.
type BinDecoder interface {
	UnmarshalBinaryWithContext(*DecodingContext) error
}

//--------------------------------------------------------------------------
//  Feed
//--------------------------------------------------------------------------

// MarshalBinary serializes the internal properties of this Feed instance
// into a byte array
func (target *Feed) MarshalBinary() (data []byte, err error) {
	ctx := NewEncodingContext(nil)

	e := target.MarshalBinaryWithContext(ctx)
	if e != nil {
		return nil, e
	}

	return ctx.ToBytes(), nil
}

// MarshalBinary serializes the internal properties of this Feed instance
// into an io.Writer.
func (target *Feed) MarshalBinaryTo(writer io.Writer) error {
	buff := util.NewBufferFromWriter(writer)
	defer buff.Flush()

	ctx := NewEncodingContextFromBuffer(buff, nil)

	return target.MarshalBinaryWithContext(ctx)
}

// MarshalBinaryWithContext serializes the internal properties of this Feed instance
// into a byte array leveraging a predefined context.
func (target *Feed) MarshalBinaryWithContext(ctx *EncodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	buff.WriteUInt8(DefaultCodecVersion) // version

	if ctx.IsStringTable() {
		v0 := ctx.Table.AddOrGet(target.Name)
		buff.WriteInt(v0)
	} else {
		buff.WriteString(target.Name)
	}
	if target.Tags == nil {
		buff.WriteUInt8(uint8(0))
	} else {
		buff.WriteUInt8(uint8(1))
		buff.WriteInt(len(target.Tags))
		for v1 := range target.Tags {
			if ctx.IsStringTable() {
				v2 := ctx.Table.AddOrGet(target.Tags[v1])
				buff.WriteInt(v2)
			} else {
				buff.WriteString(target.Tags[v1])
			}
		}
	}
	buff.WriteInt(target.Count)
	if target.Meta == nil {
		buff.WriteUInt8(uint8(0))
	} else {
		buff.WriteUInt8(uint8(1))
		buff.WriteInt(len(target.Meta))
		for v3, v4 := range target.Meta {
			if ctx.IsStringTable() {
				v5 := ctx.Table.AddOrGet(v3)
				buff.WriteInt(v5)
			} else {
				buff.WriteString(v3)
			}
			if ctx.IsStringTable() {
				v6 := ctx.Table.AddOrGet(v4)
				buff.WriteInt(v6)
			} else {
				buff.WriteString(v4)
			}
		}
	}

	return nil
}

// UnmarshalBinary uses the data passed byte array to set all the internal properties of
// the Feed type
func (target *Feed) UnmarshalBinary(data []byte) error {
	ctx := NewDecodingContextFromBytes(data)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryFromReader uses the io.Reader data to set all the internal properties of
// the Feed type
func (target *Feed) UnmarshalBinaryFromReader(reader io.Reader) error {
	ctx := NewDecodingContextFromReader(reader)
	defer ctx.Close()

	err := target.UnmarshalBinaryWithContext(ctx)
	if err != nil {
		return err
	}

	return nil
}

// UnmarshalBinaryWithContext uses the context containing a string table and binary buffer to set all the internal properties of
// the Feed type
func (target *Feed) UnmarshalBinaryWithContext(ctx *DecodingContext) (err error) {
	// panics are recovered and propagated as errors
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(error); ok {
				err = e
			} else if s, ok := r.(string); ok {
				err = fmt.Errorf("unexpected panic: %s", s)
			} else {
				err = fmt.Errorf("unexpected panic: %+v", r)
			}
		}
	}()

	buff := ctx.Buffer
	version := buff.ReadUInt8()

	if version > DefaultCodecVersion {
		return fmt.Errorf("Invalid Version Unmarshalling Feed. Expected %d or less, got %d", DefaultCodecVersion, version)
	}

	var v0 string
	if ctx.IsStringTable() {
		v1 := buff.ReadInt()
		v0 = ctx.Table.At(v1)
	} else {
		v0 = buff.ReadString()
	}
	target.Name = v0
	var v2 []string
	if buff.ReadUInt8() == uint8(0) {
		v2 = nil
	} else {
		v3 := buff.ReadInt()
		v2 = make([]string, v3)
		for v4 := range v3 {
			var v5 string
			if ctx.IsStringTable() {
				v6 := buff.ReadInt()
				v5 = ctx.Table.At(v6)
			} else {
				v5 = buff.ReadString()
			}
			v2[v4] = v5
		}
	}
	target.Tags = v2
	var v7 int
	v7 = buff.ReadInt()
	target.Count = v7
	var v8 map[string]string
	if buff.ReadUInt8() == uint8(0) {
		v8 = nil
	} else {
		v9 := buff.ReadInt()
		v8 = make(map[string]string, v9)
		for range v9 {
			var v10 string
			if ctx.IsStringTable() {
				v11 := buff.ReadInt()
				v10 = ctx.Table.At(v11)
			} else {
				v10 = buff.ReadString()
			}
			var v12 string
			if ctx.IsStringTable() {
				v13 := buff.ReadInt()
				v12 = ctx.Table.At(v13)
			} else {
				v12 = buff.ReadString()
			}
			v8[v10] = v12
		}
	}
	target.Meta = v8

	return nil
}

//--------------------------------------------------------------------------
//  FeedStream
//--------------------------------------------------------------------------

// FeedStream is a single use field stream for the contents of an Feed instance. Instead of creating an instance and populating
// the fields on that instance, we provide a streaming iterator which yields (BingenFieldInfo, *BingenValue) tuples for each
// streamable element. All slices and maps will be flattened one depth and each element streamed individually.
type FeedStream struct {
	reader io.Reader
	ctx    *DecodingContext
	err    error
}

// Closes closes the internal io.Reader used to read and parse the Feed fields.
// This should be called once the stream is no longer needed.
func (stream *FeedStream) Close() {
	if closer, ok := stream.reader.(io.Closer); ok {
		closer.Close()
	}
	stream.ctx.Close()
}

// Error returns an error if one occurred during the process of streaming the Feed
// This can be checked after iterating through the Stream().
func (stream *FeedStream) Error() error {
	return stream.err
}

// NewFeedStream creates a new FeedStream, which uses the io.Reader data to stream all internal fields of an Feed instance
func NewFeedStream(reader io.Reader) bstream.BingenStream {
	ctx := NewDecodingContextFromReader(reader)

	return &FeedStream{
		ctx:    ctx,
		reader: reader,
	}
}

// Stream returns the iterator which will stream each field of the target type.
func (stream *FeedStream) Stream() iter.Seq2[bstream.BingenFieldInfo, *bstream.BingenValue] {
	return func(yield func(bstream.BingenFieldInfo, *bstream.BingenValue) bool) {
		var fi bstream.BingenFieldInfo

		ctx := stream.ctx
		buff := ctx.Buffer
		version := buff.ReadUInt8()

		if version > DefaultCodecVersion {
			stream.err = fmt.Errorf("Invalid Version Unmarshalling Feed. Expected %d or less, got %d", DefaultCodecVersion, version)
			return
		}

		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[string](),
			Name: "Name",
		}
		var v0 string
		if ctx.IsStringTable() {
			v1 := buff.ReadInt()
			v0 = ctx.Table.At(v1)
		} else {
			v0 = buff.ReadString()
		}
		if !yield(fi, bstream.SingleV(v0)) {
			return
		}
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[[]string](),
			Name: "Tags",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			v2 := buff.ReadInt()
			for v3 := range v2 {
				var v4 string
				if ctx.IsStringTable() {
					v5 := buff.ReadInt()
					v4 = ctx.Table.At(v5)
				} else {
					v4 = buff.ReadString()
				}
				if !yield(fi, bstream.PairV(v3, v4)) {
					return
				}
			}
		}
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[int](),
			Name: "Count",
		}
		var v6 int
		v6 = buff.ReadInt()
		if !yield(fi, bstream.SingleV(v6)) {
			return
		}
		fi = bstream.BingenFieldInfo{
			Type: reflect.TypeFor[map[string]string](),
			Name: "Meta",
		}
		if buff.ReadUInt8() == uint8(0) {
			if !yield(fi, nil) {
				return
			}
		} else {
			v7 := buff.ReadInt()
			for range v7 {
				var v8 string
				if ctx.IsStringTable() {
					v9 := buff.ReadInt()
					v8 = ctx.Table.At(v9)
				} else {
					v8 = buff.ReadString()
				}
				var v10 string
				if ctx.IsStringTable() {
					v11 := buff.ReadInt()
					v10 = ctx.Table.At(v11)
				} else {
					v10 = buff.ReadString()
				}
				if !yield(fi, bstream.PairV(v8, v10)) {
					return
				}
			}
		}
	}
}
