package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"github.com/opencost/bingen/pkg/generator/vars"
	"github.com/opencost/bingen/pkg/meta"
	"github.com/opencost/bingen/pkg/types"
)

func titleName(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// default type format mapping with specific casts
var defaultValues map[uint8]string = map[uint8]string{
	types.TypeInt:     "int(%s)",
	types.TypeInt8:    "int8(%s)",
	types.TypeInt16:   "int16(%s)",
	types.TypeInt32:   "int32(%s)",
	types.TypeInt64:   "int64(%s)",
	types.TypeUInt:    "uint(%s)",
	types.TypeUInt8:   "uint8(%s)",
	types.TypeUInt16:  "uint16(%s)",
	types.TypeUInt32:  "uint32(%s)",
	types.TypeUInt64:  "uint64(%s)",
	types.TypeFloat32: "float32(%s)",
	types.TypeFloat64: "float64(%s)",
}

func Generate(dir string, pkg string, bufferImport string, tc types.TypeCollection) {
	var out bytes.Buffer

	targetTypes := tc.Types()

	// Sort Types to ensure Deterministic Ordering
	sort.Slice(targetTypes, func(i, j int) bool {
		return targetTypes[i].Name() < targetTypes[j].Name()
	})

	streamableTypes := GetStreamableTypes(targetTypes)

	ctxFactory := NewGeneratorContextFactory(&out, 4, ErrorHandler)

	WriteHeader(&out, pkg)
	WriteImports(&out, pkg, bufferImport, tc.Imports())
	WriteConstants(&out, pkg, tc.VersionSets())
	WriteDivider(&out, "Configuration")
	WriteConfiguration(&out)
	WriteDivider(&out, "Type Map")
	WriteTypeMap(&out, targetTypes)
	WriteDivider(&out, "Type Helpers")
	WriteTypeHelpers(&out)
	WriteDivider(&out, "Stream Helpers")
	WriteStreamableTypeMap(&out, streamableTypes)
	WriteStreamSupportTypes(&out)
	WriteDivider(&out, "String Table Writer")
	WriteStringTableWriter(&out)
	WriteDivider(&out, "String Table Reader")
	WriteStringTableReader(&out)
	WriteDivider(&out, "Codec Context")
	WriteCodecContext(&out)
	WriteDivider(&out, "Binary Codec")
	WriteBinaryCodecInterfaces(&out)

	for _, t := range targetTypes {
		if st, ok := t.(*types.StructType); ok {
			WriteDivider(&out, t.Name())
			WriteMarshaller(ctxFactory.NewContext(st.Opts), t)
			WriteUnmarshaller(ctxFactory.NewContext(st.Opts), t)
			if st.Opts.IsStreamable {
				WriteDivider(&out, fmt.Sprintf("%sStream", t.Name()))
				WriteStreamReader(ctxFactory.NewContext(st.Opts).WithErrorHandler(StreamErrorHandler), t)
			}
		}
	}

	result, err := format.Source(out.Bytes())
	if err != nil {
		fmt.Println("Failed to format:", err)
		return
	}

	err = os.WriteFile(fmt.Sprintf("%s/%s_codecs.go", dir, pkg), result, 0600)
	if err != nil {
		return
	}
}

func WriteHeader(out *bytes.Buffer, pkg string) {
	fmt.Fprintf(out, "////////////////////////////////////////////////////////////////////////////////\n")
	fmt.Fprintf(out, "//\n")
	fmt.Fprintf(out, "//                             DO NOT MODIFY\n//\n")
	fmt.Fprintf(out, "//                          ┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻\n//\n")
	fmt.Fprintf(out, "//\n")
	fmt.Fprintf(out, "//            This source file was automatically generated by bingen.\n")
	fmt.Fprintf(out, "//\n")
	fmt.Fprintf(out, "////////////////////////////////////////////////////////////////////////////////\n\n")
	fmt.Fprintf(out, "package %s\n\n", pkg)
}

func WriteDivider(out *bytes.Buffer, label string) {
	fmt.Fprintf(out, "//--------------------------------------------------------------------------\n")
	fmt.Fprintf(out, "//  %s\n", label)
	fmt.Fprintf(out, "//--------------------------------------------------------------------------\n\n")
}

func WriteImports(out *bytes.Buffer, pkg string, bufferImport string, imports []string) {
	fmt.Fprintf(out, "import (\n")
	//fmt.Fprintf(out, "    \"encoding\"\n")
	fmt.Fprintf(out, "    \"sync\"\n")
	fmt.Fprintf(out, "    \"fmt\"\n")
	fmt.Fprintf(out, "    \"io\"\n")
	fmt.Fprintf(out, "    \"os\"\n")
	fmt.Fprintf(out, "    \"unsafe\"\n")
	fmt.Fprintf(out, "    \"iter\"\n")
	fmt.Fprintf(out, "    \"reflect\"\n")
	fmt.Fprintf(out, "    \"strings\"\n")
	for _, im := range imports {
		fmt.Fprintf(out, "    \"%s\"\n", im)
	}
	fmt.Fprintf(out, "    util \"%s\"\n", bufferImport)
	fmt.Fprintf(out, ")\n\n")
}

func WriteConfiguration(out *bytes.Buffer) {
	fmt.Fprintf(out, "%s\n\n", BingenConfigurationCode)
}

func WriteTypeMap(out *bytes.Buffer, types []types.GenType) {
	fmt.Fprintf(out, "// Generated type map for resolving interface implementations to\n")
	fmt.Fprintf(out, "// to concrete types\n")
	fmt.Fprintf(out, "var typeMap map[string]reflect.Type = map[string]reflect.Type{\n")
	for _, t := range types {
		fmt.Fprintf(out, "    \"%s\": reflect.TypeFor[%s](),\n", t.Name(), t.Name())
	}
	fmt.Fprintf(out, "}\n\n")
}

func WriteConstants(out *bytes.Buffer, pkg string, versionSets []meta.VersionSet) {
	fmt.Fprintf(out, BingenConstants, pkg)
	fmt.Fprintf(out, "const(\n")
	for _, versionSet := range versionSets {
		versionSetName := titleName(versionSet.Name())
		constName := fmt.Sprintf("%sCodecVersion", versionSetName)
		fmt.Fprintf(out, "    // %s is used for any resources listed in the %s version set\n", constName, versionSetName)
		fmt.Fprintf(out, "    %s uint8 = %d\n\n", constName, versionSet.Version())
	}
	fmt.Fprintf(out, ")\n\n")
}

func WriteStreamableTypeMap(out *bytes.Buffer, types []*types.StructType) {
	fmt.Fprintf(out, "// StreamFactoryFunc is an alias for a func that creates a BingenStream implementation.\n")
	fmt.Fprintf(out, "type StreamFactoryFunc func(io.Reader) BingenStream\n\n")
	fmt.Fprintf(out, "// Generated streamable factory map for finding the specific new stream methods\n")
	fmt.Fprintf(out, "// by T type\n")
	fmt.Fprintf(out, "var streamFactoryMap map[reflect.Type]StreamFactoryFunc = map[reflect.Type]StreamFactoryFunc{\n")
	for _, t := range types {
		fmt.Fprintf(out, "    reflect.TypeFor[%s](): New%sStream,\n", t.Name(), t.Name())
	}
	fmt.Fprintf(out, "}\n")
	fmt.Fprintf(out, "%s", BingenNewStreamForCode)
}

func WriteStreamSupportTypes(out *bytes.Buffer) {
	fmt.Fprintf(out, "%s\n\n", BingenFieldStreamSupportCode)
}

func WriteStringTableWriter(out *bytes.Buffer) {
	fmt.Fprintf(out, "%s\n\n", StringTableWriterCode)
}

func WriteStringTableReader(out *bytes.Buffer) {
	fmt.Fprintf(out, "%s\n\n", StringTableReaderCode)
}

func WriteBinaryCodecInterfaces(out *bytes.Buffer) {
	fmt.Fprintf(out, "%s\n\n", BinaryCodecInterfaceCode)
}

func WriteCodecContext(out *bytes.Buffer) {
	fmt.Fprintf(out, "%s\n\n", BinaryCodecContextsCode)
}

func WriteTypeHelpers(out *bytes.Buffer) {
	fmt.Fprintf(out, "%s\n\n", TypeHelperCode)
}

func WritePanicHandler(scope Scope) {
	scope.Writeln("// panics are recovered and propagated as errors")
	scope.Writeln("defer func() {")
	scope.Writeln("    if r := recover(); r != nil {")
	scope.Writeln("        if e, ok := r.(error); ok {")
	scope.Writeln("            err = e")
	scope.Writeln("        } else if s, ok := r.(string); ok {")
	scope.Writeln("            err = fmt.Errorf(\"Unexpected panic: %%s\", s)")
	scope.Writeln("        } else {")
	scope.Writeln("            err = fmt.Errorf(\"Unexpected panic: %%+v\", r)")
	scope.Writeln("        }")
	scope.Writeln("    }")
	scope.Writeln("}()\n")
}

func WriteMarshaller(ctx GeneratorContext, t types.GenType) {
	// Writes the BinaryEncoder implementation for the type
	ctx.Writeln("// MarshalBinary serializes the internal properties of this %s instance", t.Name())
	ctx.Writeln("// into a byte array")
	scope := ctx.PushScope("func (target *%s) MarshalBinary() (data []byte, err error) {", t.Name())

	inner := scope.Push("ctx := &EncodingContext{")
	inner.Writeln("Buffer: util.NewBuffer(),")
	if ctx.IsStringTable() {
		inner.Writeln("Table: NewStringTableWriter(),")
	} else {
		inner.Writeln("Table: nil,")
	}
	inner.Pop("}\n")

	// Writes the custom binary encoding (with added context for optimization)
	scope.Writeln("e := target.MarshalBinaryWithContext(ctx)")
	errchk := scope.Push("if e != nil {")
	errchk.Writeln("return nil, e")
	errchk.Pop("}\n")

	// write the string table to the type if enabled
	scope.Writeln("encBytes := ctx.Buffer.Bytes()")

	if !ctx.IsStringTable() {
		scope.Writeln("return encBytes, nil")
	} else {
		scope.Writeln("sTableBytes := ctx.Table.ToBytes()")
		scope.Writeln("merged := appendBytes(sTableBytes, encBytes)")
		scope.Writeln("return merged, nil")
	}
	scope.Pop("}\n")

	ctx.Writeln("// MarshalBinaryWithContext serializes the internal properties of this %s instance", t.Name())
	ctx.Writeln("// into a byte array leveraging a predefined context.")
	scope = ctx.PushScope("func (target *%s) MarshalBinaryWithContext(ctx *EncodingContext) (err error) {", t.Name())

	WritePanicHandler(scope)

	scope.Writeln("buff := ctx.Buffer")

	scope.Writeln("buff.WriteUInt8(%s) // version\n", ctx.VersionSetConst())

	WriteFullStructType(ctx, t.(*types.StructType))

	scope.Writeln("return nil")
	scope.Pop("}\n")
}

func WriteFullStructType(ctx GeneratorContext, t *types.StructType) {
	if ctx.IsPreProcess() {
		ctx.Writeln("// execute pre-processing func")
		ctx.Writeln("preProcess%s(target)", t.Name())
	}

	for _, f := range t.Fields {
		WriteType(ctx, f.Type, vars.NewFieldTarget("target", f.Name))
	}
}

func WriteType(ctx GeneratorContext, t types.GenType, target vars.Target) {
	// Nilable conditional check
	if t.IsNilable() {
		scope := ctx.PushScope("if %s == nil {", target)
		scope.Writeln("buff.WriteUInt8(uint8(0)) // write nil byte")
		scope.PopPush("} else {")
		scope.Writeln("buff.WriteUInt8(uint8(1)) // write non-nil byte\n")

		WriteTypeRaw(ctx, t, target)

		scope.Pop("}")
		return
	}

	// Otherwise, just output the raw type writer
	WriteTypeRaw(ctx, t, target)
}

func WriteTypeRaw(ctx GeneratorContext, t types.GenType, target vars.Target) {
	switch rt := t.(type) {
	case *types.BasicType:
		WriteBasicType(ctx, rt, target)
	case *types.SliceType:
		WriteArrayType(ctx, rt, target)
	case *types.MapType:
		WriteMapType(ctx, rt, target)
	case *types.StructType:
		WriteStructType(ctx, rt, target)
	case *types.ReferenceType:
		resolvedType := rt.Resolve()
		if resolvedType != nil {
			WriteTypeRaw(ctx, resolvedType, target)
		} else {
			WriteReferenceType(ctx, rt, target)
		}
	case *types.AliasType:
		WriteAliasType(ctx, rt, target)
	case *types.InterfaceType:
		WriteInterfaceType(ctx, rt, target)
	}
}

func WriteBasicType(ctx GeneratorContext, bt *types.BasicType, target vars.Target) {
	star := ""
	if bt.IsPtr() {
		star = "*"
	}

	switch bt.Code() {
	case types.TypeBool:
		ctx.Write("buff.WriteBool(%s%s) // write bool\n", star, target)
	case types.TypeInt:
		ctx.Write("buff.WriteInt(%s%s) // write int\n", star, target)
	case types.TypeInt8:
		ctx.Write("buff.WriteInt8(%s%s) // write int8\n", star, target)
	case types.TypeInt16:
		ctx.Write("buff.WriteInt16(%s%s) // write int16\n", star, target)
	case types.TypeInt32:
		ctx.Write("buff.WriteInt32(%s%s) // write int32\n", star, target)
	case types.TypeInt64:
		ctx.Write("buff.WriteInt64(%s%s) // write int64\n", star, target)
	case types.TypeUInt:
		ctx.Write("buff.WriteUInt(%s%s) // write uint\n", star, target)
	case types.TypeUInt8:
		ctx.Write("buff.WriteUInt8(%s%s) // write uint8\n", star, target)
	case types.TypeUInt16:
		ctx.Write("buff.WriteUInt16(%s%s) // write uint16\n", star, target)
	case types.TypeUInt32:
		ctx.Write("buff.WriteUInt32(%s%s) // write uint32\n", star, target)
	case types.TypeUInt64:
		ctx.Write("buff.WriteUInt64(%s%s) // write uint64\n", star, target)
	case types.TypeFloat32:
		ctx.Write("buff.WriteFloat32(%s%s) // write float32\n", star, target)
	case types.TypeFloat64:
		ctx.Write("buff.WriteFloat64(%s%s) // write float64\n", star, target)
	case types.TypeString:
		tableIndexVar := ctx.NextVar()
		ctx.Writeln("if ctx.IsStringTable() {")
		ctx.Writeln("    %s := ctx.Table.AddOrGet(%s%s)", tableIndexVar, star, target)
		ctx.Writeln("    buff.WriteInt(%s) // write table index", tableIndexVar)
		ctx.Writeln("} else {")
		ctx.Writeln("    buff.WriteString(%s%s) // write string", star, target)
		ctx.Writeln("}")
	}
}

func WriteArrayType(ctx GeneratorContext, at *types.SliceType, target vars.Target) {
	d := ctx.PushDebugWrite("slice", at.Name())
	defer d.End()

	loopVar := ctx.NextLoopVar()

	ctx.Writeln("buff.WriteInt(len(%s)) // array length", target)
	loop := ctx.PushScope("for %s := 0; %s < len(%s); %s++ {", loopVar, loopVar, target, loopVar)
	WriteType(ctx, at.InnerType, vars.NewIndexedTarget(target, loopVar))
	loop.Pop("}")
}

func WriteMapType(ctx GeneratorContext, mt *types.MapType, target vars.Target) {
	d := ctx.PushDebugWrite("map", mt.Name())
	defer d.End()

	keyVar := ctx.NextMapVar()
	valVar := ctx.NextMapVar()

	ctx.Writeln("buff.WriteInt(len(%s)) // map length", target)
	loop := ctx.PushScope("for %s, %s := range %s {", keyVar, valVar, target)
	WriteType(ctx, mt.KeyType, vars.AsTarget(keyVar))
	WriteType(ctx, mt.ValueType, vars.AsTarget(valVar))
	loop.Pop("}")
}

func WriteStructType(ctx GeneratorContext, t *types.StructType, target vars.Target) {
	d := ctx.PushDebugWrite("struct", t.Name())
	defer d.End()

	errVar := ctx.NextErrVar()

	ctx.Writeln("buff.WriteInt(0) // [compatibility, unused]")

	ctx.Writeln("%s := %s.MarshalBinaryWithContext(ctx)", errVar, target)
	errCheck := ctx.PushScope("if %s != nil {", errVar)
	errCheck.Writeln("return %s", errVar)
	errCheck.Pop("}")
}

func WriteReferenceType(ctx GeneratorContext, t *types.ReferenceType, target vars.Target) {
	d := ctx.PushDebugWrite("reference", t.Name())
	defer d.End()

	nvar := ctx.NextVar()
	errVar := ctx.NextErrVar()

	ctx.Writeln("%s, %s := %s.MarshalBinary()", nvar, errVar, target)
	errCheck := ctx.PushScope("if %s != nil {", errVar)
	errCheck.Writeln("return %s", errVar)
	errCheck.Pop("}")
	ctx.Writeln("buff.WriteInt(len(%s))", nvar)
	ctx.Writeln("buff.WriteBytes(%s)", nvar)
}

func WriteInterfaceType(ctx GeneratorContext, t *types.InterfaceType, target vars.Target) {
	d := ctx.PushDebugWrite("interface", t.Name())
	defer d.End()

	interfaceVar := ctx.NextVar()
	binaryMarshalerVar := ctx.NextVar()
	interfaceOKVar := ctx.NextOKVar()
	errVar := ctx.NextErrVar()

	ctx.Writeln("%s := reflect.ValueOf(%s).Interface()", interfaceVar, target)
	ctx.Writeln("%s, %s := %s.(BinEncoder)", binaryMarshalerVar, interfaceOKVar, interfaceVar)
	intCheck := ctx.PushScope("if !%s {", interfaceOKVar)
	intCheck.Writeln("return fmt.Errorf(\"Type: %%s does not implement %%s.BinEncoder\", typeToString(%s), GeneratorPackageName)", target)
	intCheck.Pop("}")

	ctx.Writeln("buff.WriteString(typeToString(%s))", target)
	ctx.Writeln("buff.WriteInt(0) // [compatibility, unused]")

	ctx.Writeln("%s := %s.MarshalBinaryWithContext(ctx)", errVar, binaryMarshalerVar)
	errCheck := ctx.PushScope("if %s != nil {", errVar)
	errCheck.Writeln("return %s", errVar)
	errCheck.Pop("}")
}

func WriteAliasType(ctx GeneratorContext, t *types.AliasType, target vars.Target) {
	d := ctx.PushDebugWrite("alias", t.Name())
	defer d.End()

	// pointer types need to be disambiguated for the go parser: ie: ((*TypePtr)(var))
	// because the following would be illegal syntax: *TypePtr(var) -> treated as *(TypePtr(var))
	// which is incorrect
	if t.Alias.IsPtr() {
		WriteType(ctx, t.Alias, vars.NewTypeCastedTarget(t.Alias.TypeName(), target))
	} else {
		WriteType(ctx, t.Alias, vars.NewCastedTarget(t.Alias.TypeName(), target))
	}
}

func WriteUnmarshalBinary(ctx GeneratorContext, t types.GenType) {
	ctx.Writeln("// UnmarshalBinary uses the data passed byte array to set all the internal properties of")
	ctx.Writeln("// the %s type", t.Name())
	scope := ctx.PushScope("func (target *%s) UnmarshalBinary(data []byte) error {", t.Name())
	scope.Writeln("ctx := NewDecodingContextFromBytes(data)")
	scope.Writeln("defer ctx.Close()")

	// Writes the custom binary encoding (with added context for optimization)
	scope.Writeln("err := target.UnmarshalBinaryWithContext(ctx)")
	errchk := scope.Push("if err != nil {")
	errchk.Writeln("return err")
	errchk.Pop("}\n")

	scope.Writeln("return nil")
	scope.Pop("}\n")
}

func WriteUnmarshalBinaryFromReader(ctx GeneratorContext, t types.GenType) {
	ctx.Writeln("// UnmarshalBinaryFromReader uses the io.Reader data to set all the internal properties of")
	ctx.Writeln("// the %s type", t.Name())
	scope := ctx.PushScope("func (target *%s) UnmarshalBinaryFromReader(reader io.Reader) error {", t.Name())
	scope.Writeln("ctx := NewDecodingContextFromReader(reader)")
	scope.Writeln("defer ctx.Close()")

	// Writes the custom binary encoding (with added context for optimization)
	scope.Writeln("err := target.UnmarshalBinaryWithContext(ctx)")
	errchk := scope.Push("if err != nil {")
	errchk.Writeln("return err")
	errchk.Pop("}\n")

	scope.Writeln("return nil")
	scope.Pop("}\n")
}

func WriteUnmarshalBinaryWithContext(ctx GeneratorContext, t types.GenType) {
	ctx.Writeln("// UnmarshalBinaryWithContext uses the context containing a string table and binary buffer to set all the internal properties of")
	ctx.Writeln("// the %s type", t.Name())
	scope := ctx.PushScope("func (target *%s) UnmarshalBinaryWithContext(ctx *DecodingContext) (err error) {", t.Name())

	WritePanicHandler(scope)

	st := t.(*types.StructType)

	scope.Writeln("buff := ctx.Buffer")
	scope.Writeln("version := buff.ReadUInt8()\n")

	cond := scope.Push("if version > %s {", ctx.VersionSetConst())
	cond.Writeln("return fmt.Errorf(\"Invalid Version Unmarshaling %s. Expected %%d or less, got %%d\", %s, version)", t.Name(), ctx.VersionSetConst())
	cond.Pop("}\n")

	ReadFullStructType(ctx, st)

	scope.Writeln("return nil")
	scope.Pop("}\n")
}

func WriteUnmarshaller(ctx GeneratorContext, t types.GenType) {
	WriteUnmarshalBinary(ctx, t)
	WriteUnmarshalBinaryFromReader(ctx, t)
	WriteUnmarshalBinaryWithContext(ctx, t)
}

func ReadFullStructType(ctx GeneratorContext, t *types.StructType) {
	for _, f := range t.Fields {
		var fieldVersion uint8 = 0
		if f.Opts != nil {
			fieldVersion = f.Opts.Version
		}

		if fieldVersion != 0 {
			ctx.Writeln("// field version check")
			cond := ctx.PushScope("if uint8(%d) <= version {", fieldVersion)
			ReadType(ctx, f.Type, vars.NewFieldTarget("target", f.Name), false)
			cond.PopPush("} else {")
			SetTypeDefault(ctx, f.Type, f.Opts, vars.NewFieldTarget("target", f.Name))
			cond.Pop("}\n")
		} else {
			ReadType(ctx, f.Type, vars.NewFieldTarget("target", f.Name), false)
		}
	}

	if ctx.IsMigration() {
		ctx.Writeln("// execute migration func if version delta detected")
		cond := ctx.PushScope("if version != %s {", ctx.VersionSetConst())
		cond.Writeln("migrate%s(target, version, %s)", t.Name(), ctx.VersionSetConst())
		cond.Pop("}\n")
	}

	if ctx.IsPostProcess() {
		ctx.Writeln("// execute post-processing func")
		ctx.Writeln("postProcess%s(target)", t.Name())
	}
}

func ReadType(ctx GeneratorContext, t types.GenType, target vars.Target, set bool) {
	if t.IsNilable() {
		if set {
			ctx.Writeln("var %s %s", target, t.TypeName())
			set = false
		}

		cond := ctx.PushScope("if buff.ReadUInt8() == uint8(0) {")
		cond.Writeln("%s = nil", target)
		cond.PopPush("} else {")

		ReadTypeRaw(ctx, t, target, set)

		cond.Pop("}")
		return
	}

	ReadTypeRaw(ctx, t, target, set)
}

func SetTypeDefault(ctx GeneratorContext, t types.GenType, opts *types.FieldOpts, target vars.Target) {
	if t.IsNilable() {
		ctx.Writeln("%s = nil\n", target)
		return
	}

	var defaultValue string
	if opts == nil {
		defaultValue = ""
	} else {
		defaultValue = opts.Default
	}

	switch rt := t.(type) {
	case *types.BasicType:
		ctx.Writeln("%s = %s // default", target, ToDefaultValue(rt.Code(), defaultValue))
	default:
		if defaultValue == "" {
			return
		}
		ctx.Writeln("%s = %s // default", target, defaultValue)
	}
}

func ToDefaultValue(typeCode uint8, value string) string {
	if typeCode == types.TypeString {
		return fmt.Sprintf("\"%s\"", value)
	}

	if typeCode == types.TypeBool {
		if value == "" {
			return "false"
		}
		return value
	}

	if value == "" {
		return fmt.Sprintf(defaultValues[typeCode], "0")
	}
	return fmt.Sprintf(defaultValues[typeCode], value)
}

func ErrorHandler(errCheck Scope, newErr string) {
	errCheck.Writeln("return %s", newErr)
}

func ReadTypeRaw(ctx GeneratorContext, t types.GenType, target vars.Target, set bool) {
	switch rt := t.(type) {
	case *types.BasicType:
		ReadBasicType(ctx, rt, target, set)
	case *types.SliceType:
		ReadArrayType(ctx, rt, target, set)
	case *types.MapType:
		ReadMapType(ctx, rt, target, set)
	case *types.StructType:
		ReadStructType(ctx, rt, target, set)
	case *types.ReferenceType:
		resolvedType := rt.Resolve()
		if resolvedType != nil {
			ReadTypeRaw(ctx, resolvedType, target, set)
		} else {
			ReadReferenceType(ctx, rt, target, set)
		}
	case *types.AliasType:
		ReadAliasType(ctx, rt, target, set)
	case *types.InterfaceType:
		ReadInterfaceType(ctx, rt, target, set)
	}
}

func ReadBasicType(ctx GeneratorContext, bt *types.BasicType, target vars.Target, set bool) {
	varName := ctx.NextVar()

	resultVar := varName
	if bt.IsPtr() {
		resultVar = "&" + resultVar
	}

	if set {
		ctx.Writeln("var %s %s", target, bt.TypeName())
	}

	switch bt.Code() {
	case types.TypeBool:
		ctx.Writeln("%s := buff.ReadBool() // read bool", varName)
	case types.TypeInt:
		ctx.Writeln("%s := buff.ReadInt() // read int", varName)
	case types.TypeInt8:
		ctx.Writeln("%s := buff.ReadInt8() // read int8", varName)
	case types.TypeInt16:
		ctx.Writeln("%s := buff.ReadInt16() // read int16", varName)
	case types.TypeInt32:
		ctx.Writeln("%s := buff.ReadInt32() // read int32", varName)
	case types.TypeInt64:
		ctx.Writeln("%s := buff.ReadInt64() // read int64", varName)
	case types.TypeUInt:
		ctx.Writeln("%s := buff.ReadUInt() // read uint", varName)
	case types.TypeUInt8:
		ctx.Writeln("%s := buff.ReadUInt8() // read uint8", varName)
	case types.TypeUInt16:
		ctx.Writeln("%s := buff.ReadUInt16() // read uint16", varName)
	case types.TypeUInt32:
		ctx.Writeln("%s := buff.ReadUInt32() // read uint32", varName)
	case types.TypeUInt64:
		ctx.Writeln("%s := buff.ReadUInt64() // read uint64", varName)
	case types.TypeFloat32:
		ctx.Writeln("%s := buff.ReadFloat32() // read float32", varName)
	case types.TypeFloat64:
		ctx.Writeln("%s := buff.ReadFloat64() // read float64", varName)
	case types.TypeString:
		tempVar := ctx.NextVar()
		tableIndexVar := ctx.NextVar()

		ctx.Writeln("var %s string", tempVar)
		ctx.Writeln("if ctx.IsStringTable() {")
		ctx.Writeln("    %s := buff.ReadInt() // read string index", tableIndexVar)
		ctx.Writeln("    %s = ctx.Table.At(%s)", tempVar, tableIndexVar)
		ctx.Writeln("} else {")
		ctx.Writeln("    %s = buff.ReadString() // read string", tempVar)
		ctx.Writeln("}")
		ctx.Writeln("%s := %s", varName, tempVar)
	}

	ctx.Writeln("%s = %s\n", target, resultVar)
}

func ReadArrayType(ctx GeneratorContext, at *types.SliceType, target vars.Target, set bool) {
	d := ctx.PushDebugRead("slice", at.Name())
	defer d.End()

	e := "="
	if set {
		e = ":="
	}

	sliceVar := ctx.NextVar()
	lenVar := ctx.NextVar()
	loopVar := ctx.NextLoopVar()
	innerVar := ctx.NextVar()

	ctx.Writeln("%s := buff.ReadInt() // array len", lenVar)
	ctx.Writeln("%s := make(%s, %s)", sliceVar, at.Name(), lenVar)
	loop := ctx.PushScope("for %s := 0; %s < %s; %s++ {", loopVar, loopVar, lenVar, loopVar)
	ReadType(ctx, at.InnerType, vars.AsTarget(innerVar), true)
	loop.Writeln("%s[%s] = %s", sliceVar, loopVar, innerVar)
	loop.Pop("}")

	ctx.Writeln("%s %s %s", target, e, sliceVar)
}

func ReadMapType(ctx GeneratorContext, mt *types.MapType, target vars.Target, set bool) {
	d := ctx.PushDebugRead("map", mt.Name())
	defer d.End()

	e := "="
	if set {
		e = ":="
	}

	mapVar := ctx.NextVar()
	lenVar := ctx.NextVar()
	idxVar := ctx.NextLoopVar()
	keyVar := ctx.NextMapVar()
	valVar := ctx.NextMapVar()

	ctx.Writeln("%s := buff.ReadInt() // map len", lenVar)
	ctx.Writeln("%s := make(map[%s]%s, %s)", mapVar, mt.KeyType.TypeName(), mt.ValueType.TypeName(), lenVar)

	loop := ctx.PushScope("for %s := 0; %s < %s; %s++ {", idxVar, idxVar, lenVar, idxVar)
	ReadType(ctx, mt.KeyType, vars.AsTarget(keyVar), true)
	ReadType(ctx, mt.ValueType, vars.AsTarget(valVar), true)
	loop.Writeln("%s[%s] = %s", mapVar, keyVar, valVar)
	loop.Pop("}")

	ctx.Writeln("%s %s %s", target, e, mapVar)
}

func ReadStructType(ctx GeneratorContext, t *types.StructType, target vars.Target, set bool) {
	d := ctx.PushDebugRead("struct", t.Name())
	defer d.End()

	e := "="
	if set {
		e = ":="
	}

	ubVar := ctx.NextVar()
	errVar := ctx.NextErrVar()

	ctx.Writeln("%s := &%s{}", ubVar, t.Name())
	ctx.Writeln("buff.ReadInt() // [compatibility, unused]")
	ctx.Writeln("%s := %s.UnmarshalBinaryWithContext(ctx)", errVar, ubVar)
	errCheck := ctx.PushScope("if %s != nil {", errVar)
	ctx.WriteErrorHandler(errCheck, errVar)
	errCheck.Pop("}")

	if t.IsPtr() {
		ctx.Writeln("%s %s %s", target, e, ubVar)
	} else {
		ctx.Writeln("%s %s *%s", target, e, ubVar)
	}
}

func ReadReferenceType(ctx GeneratorContext, t *types.ReferenceType, target vars.Target, set bool) {
	d := ctx.PushDebugRead("reference", t.Name())
	defer d.End()

	e := "="
	if set {
		e = ":="
	}

	ubVar := ctx.NextVar()
	blVar := ctx.NextVar()
	baVar := ctx.NextVar()
	errVar := ctx.NextErrVar()

	ctx.Writeln("%s := &%s{}", ubVar, t.Name())
	ctx.Writeln("%s := buff.ReadInt() // byte array length", blVar)
	ctx.Writeln("%s := buff.ReadBytes(%s) // byte array", baVar, blVar)
	ctx.Writeln("%s := %s.UnmarshalBinary(%s)", errVar, ubVar, baVar)
	errCheck := ctx.PushScope("if %s != nil {", errVar)
	ctx.WriteErrorHandler(errCheck, errVar)
	errCheck.Pop("}")

	if t.IsPtr() {
		ctx.Writeln("%s %s %s", target, e, ubVar)
	} else {
		ctx.Writeln("%s %s *%s", target, e, ubVar)
	}
}

func ReadInterfaceType(ctx GeneratorContext, t *types.InterfaceType, target vars.Target, set bool) {
	d := ctx.PushDebugRead("interface", t.Name())
	defer d.End()

	e := "="
	if set {
		e = ":="
	}

	tNameVar := ctx.NextVar()
	nameVar := ctx.NextVar()
	interfaceOKVar := ctx.NextOKVar()
	ubVar := ctx.NextVar()
	errVar := ctx.NextErrVar()

	ctx.Writeln("%s := buff.ReadString()", tNameVar)
	ctx.Writeln("_, %s, _ := resolveType(%s)", nameVar, tNameVar)
	typeCheck := ctx.PushScope("if _, ok := typeMap[%s]; !ok {", nameVar)
	ctx.WriteErrorHandler(typeCheck, fmt.Sprintf("fmt.Errorf(\"Unknown Type: %%s\", %s)", nameVar))
	typeCheck.Pop("}")

	ctx.Writeln("%s, %s := reflect.New(typeMap[%s]).Interface().(BinDecoder)", ubVar, interfaceOKVar, nameVar)
	intCheck := ctx.PushScope("if !%s {", interfaceOKVar)
	ctx.WriteErrorHandler(intCheck, fmt.Sprintf("fmt.Errorf(\"Type: %%s does not implement %%s.BinDecoder.\", %s, GeneratorPackageName)", nameVar))
	intCheck.Pop("}")

	ctx.Writeln("buff.ReadInt() // [compatibility, unused]")
	ctx.Writeln("%s := %s.UnmarshalBinaryWithContext(ctx)", errVar, ubVar)
	errCheck := ctx.PushScope("if %s != nil {", errVar)
	ctx.WriteErrorHandler(errCheck, errVar)
	errCheck.Pop("}")

	ctx.Writeln("%s %s %s.(%s)", target, e, ubVar, t.Name())
}

func ReadAliasType(ctx GeneratorContext, t *types.AliasType, target vars.Target, set bool) {
	d := ctx.PushDebugRead("alias", t.Name())
	defer d.End()

	e := "="
	if set {
		e = ":="
	}

	atype := t.Name()
	if t.IsPtr() {
		atype = "*" + t.Name()
	}

	varName := ctx.NextVar()

	ReadType(ctx, t.Alias, vars.AsTarget(varName), true)
	ctx.Writeln("%s %s %s(%s)", target, e, atype, varName)
}
